### ISSUE TITLE
No module named 'torch_scatter.composite'

### ISSUE THREAD

**Issue by ThyrixYang** [rusty1s/pytorch_scatter#102]
I've been using pytorch_geometric and torch_scatter and everything are fine.

But it said No module named 'torch_scatter.composite' when I try to import scatter_log_softmax.

Other modules such as scatter add and scatter mul do not have this problem.

**Comment by rusty1s** [comment]
`torch_scatter.composite` is only available on master and not yet released on PyPi. You need to install from master :)

**Comment by ThyrixYang** [comment]
Thanks!
