### ISSUE TITLE
Final linking stage fails on Windows due to build trying to /EXPORT the init function

### ISSUE THREAD

**Issue by Novare** [rusty1s/pytorch_scatter#104]
Once all other Windows-related issues I adressed in my previous pull requests are fixed, there is one issue left - the final linking stage of the install process tries to /EXPORT a function called PyInit_scatter_cuda, **which doesn't exist**. This is specifically a Windows issue and the reason behind it is explained in [the accepted answer to this post on StackOverflow](https://stackoverflow.com/questions/34689210/error-exporting-symbol-when-building-python-c-extension-in-windows).

The **tl;dr** is that on Windows, the install process is trying to build the Python-equivalent of a .DLL and it **always** tries to export the init function of the module. If it doesn't exist, it fails. Now, my first idea was to just define the neccessary functions and data as described in the [official Microsoft documentation](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019#convert-the-c-projects-to-extensions-for-python), but I saw that this project uses pybind11 to reduce the redundancy of a typical CPython implementation described in the article. Since the error happens despite the code of scatter.cpp looking exactly like the pybind11 example in the same article, this is not (neccessarily) a problem with the code itself.

As described in the StackOverflow answer, you can't tell the Extension class NOT to export the function, even though pybind11 already does it afaik. What I did then was to implement the PyInit_scatter_cuda function, but make it do nothing and not return anything. To reproduce this, add this to the bottom of your cuda/scatter.cpp:

```
void PyInit_scatter_cuda() {
    /*
     * Initialization function needed for Windows, since the linker forces us to /EXPORT one.
     * Since we use pybind11 to define and export modules on compilation, this doesn't need to do
     * anything.
     */
}
```

Then torch_scatter successfully compiled under Windows - but the tests failed due to some access violation I believe stems from the init function basically doing nothing. But I'm not entirely sure about that. Maybe you can have the init function return whatever pybind11 would normally do somehow, but I don't know enough about Python or PyBind to do that myself.

I could implement the boilerplate that pybind11 should eliminate and basically duplicate the code to make 100% sure that the functions get properly exported, but at this point I'll just compile this under Linux since it doesn't do all this weird DLL exporting business and I need to get this running soon to build StructureNet. If someone else who is more familiar with combining Python and C++ wants to pick up from here, that would be greatly appreciated.

**Comment by rusty1s** [comment]
Since we no longer use PyBind11, this should be fixed with the latest `torch-scatter` release :)
