### ISSUE TITLE
failure to build

### ISSUE THREAD

**Issue by elfayoumi** [rusty1s/pytorch_scatter#106]
Hi
thank you for the package, it is really nice.
I am having trouble building in in ubuntu 18.04 with pytorch 1.4
/home/ibrahim/Workspace/pytorch_scatter/csrc/segment_coo.cpp: In static member function ‘static torch::autograd::variable_list SegmentSumCOO::backward(torch::autograd::AutogradContext*, torch::autograd::variable_list)’:
/home/ibrahim/Workspace/pytorch_scatter/csrc/segment_coo.cpp:60:51: error: ‘struct c10::IValue’ has no member named ‘toIntVector’; did you mean ‘toIntList’?
     auto src_shape = ctx->saved_data["src_shape"].toIntVector();
                                                   ^~~~~~~~~~~

I am not sure should we change toIntVector inot toIntList?

Thanks

**Comment by rusty1s** [comment]
Mh, should work in `torch-nightly`. Simply changing the code to `toIntList` does not work.

**Comment by rusty1s** [comment]
Should be fixed in master. Can you try again?

**Comment by elfayoumi** [comment]
thanks, it is working now..
