### ISSUE TITLE
Warning unable to load binaries afetr scatter upgraded to 2.0.1

### ISSUE THREAD

**Issue by viduzz84** [rusty1s/pytorch_scatter#107]
Hi, i work with PyTorch geometric in colab. Today after the upgrade of torch-scatter package to version 2.0.1 i encountered this problem:
![001](https://user-images.githubusercontent.com/57779144/73741288-36288a80-474a-11ea-849c-3a83a25219ba.png)
this causes the failed execution:
![002](https://user-images.githubusercontent.com/57779144/73741795-49882580-474b-11ea-8732-920c1e17e745.png)

To be sure was not my fault i execute various public examples of GNN wich uses different message passing functions, for example: https://colab.research.google.com/github/zaidalyafeai/Notebooks/blob/master/Deep_GCN_Spam.ipynb and all reports the same issue.

Using torch-scatter==1.4.0 the problem disappear.

Thanks

**Comment by rusty1s** [comment]
Wow, this was fast :D I will release a new PyG version to handle `torch-scatter`. It already works in master.

**Comment by viduzz84** [comment]
you fast too! thanks for the reply

**Comment by rusty1s** [comment]
Done! See [here](https://github.com/rusty1s/pytorch_geometric/releases/tag/1.4.1).

**Comment by rusty1s** [comment]
Oh, shit. I still failed with the `torch-scatter` version on PyPi. Just one moment!

**Comment by rusty1s** [comment]
Should be fixed, but require latest versions for `torch-scatter`, `torch-sparse` and `torch-geometric`. Sorry for the inconveniences!

**Comment by viduzz84** [comment]
Now works fine, thank you
