### ISSUE TITLE
Error installing library

### ISSUE THREAD

**Issue by alishibli97** [rusty1s/pytorch_scatter#109]
**Windows 10, Python 3.6, CUDA 10.1, Pytorch 1.4.0.**

I tried several times to install the library but I can't, build failed no wheels.
This is the main error;

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

I have Visual Studio 2019.

**Comment by rusty1s** [comment]
Please see https://github.com/rusty1s/pytorch_scatter/issues/110#issuecomment-585760186
