### ISSUE TITLE
error: command 'gcc-4.9' failed with exit status 1

### ISSUE THREAD

**Issue by emanhamed** [rusty1s/pytorch_scatter#11]
Installing pytorch scatter is continuously resulting in this error when using python 2 or python 3. I tried installing from both source and pip and it is still the same. 
gcc 4.9 is installed and I'm on ubuntu 18.04

**Comment by rusty1s** [comment]
Is this still relevant? Can you show me the error logs? There are already a lot of closed issues on this topic (in pytorch_geometric) which should be helpful for you.
