### ISSUE TITLE
Compilation error on Windows 10 with VS2019

### ISSUE THREAD

**Issue by pradeep-pyro** [rusty1s/pytorch_scatter#110]
Compilation fails with the following error:
`...\pytorch_scatter\csrc\cpu\scatter_cpu.cpp(81): error C2975: 'REDUCE': invalid template argument for 'Reducer', expected compile-time constant expression`

**Comment by jl626** [comment]
I encountered the same problem with VS2017. (error C2975 and C2440)

```
...\pytorch_scatter\csrc\cpu\scatter_cpu.cpp(51): warning C4244: '*=': conversion from 'int64_t' to 'int', possible loss of data
...\pytorch_scatter\csrc\cpu\scatter_cpu.cpp(81): error C2975: 'REDUCE': invalid template argument for 'Reducer', expected compile-time constant expression
...\pytorch_scatter\csrc\cpu\reducer.h(43): note: see declaration of 'REDUCE'
...\pytorch_scatter\csrc\cpu\scatter_cpu.cpp(81): error C2440: 'specialization': cannot convert from 'int' to 'ReductionType'
...\pytorch_scatter\csrc\cpu\scatter_cpu.cpp(81): note: Conversion to enumeration type requires an explicit cast (static_cast, C-style cast or function-style cast)
...\pytorch_scatter\csrc\cpu\scatter_cpu.cpp(57): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data
```

**Comment by MichaelHillier** [comment]
I have the same problem as well. Tried multiple different versions of VS and same exact error. 

Issue is here in the cpp file:

out.fill_(Reducer<scalar_t, REDUCE>::init());

REDUCE is not yet defined with the proper enum type from the header:

enum ReductionType { SUM, MEAN, MUL, DIV, MIN, MAX };

Reducer class reference (also in the header):
template <typename scalar_t, ReductionType REDUCE> struct Reducer {
  static inline scalar_t init() {
    if (REDUCE == MUL || REDUCE == DIV)
      return (scalar_t)1;
    else if (REDUCE == MIN)
      return std::numeric_limits<scalar_t>::max();
    else if (REDUCE == MAX)
      return std::numeric_limits<scalar_t>::lowest();
    else
      return (scalar_t)0;
  }

**_Perhaps_** the problem would be solved if REDUCE in the cpp file were changed to reduce2REDUCE.at(reduce). That way the Reducer would be properly initialized with the input given to scatter_cpu; std::string reduce .

Note reduce2REDUCE.at(reduce) is also defined in the header:
const std::map<std::string, ReductionType> reduce2REDUCE = {
    {"sum", SUM}, {"mean", MEAN}, {"mul", MUL},
    {"div", DIV}, {"min", MIN},   {"max", MAX},
};
This converts the string (e.g. "sum") to the enum type (e.g. SUM).

**Comment by rusty1s** [comment]
I might have fixed this error on master, and I would be very happy if you could try it out and report if this fixes your issues!

**Comment by MichaelHillier** [comment]
No longer getting the error related to REDUCE with your new fix. Thanks for the quick fix.

However, I am getting a new error from cuda's nvcc.exe failing with exit status 1 which is a different problem I'll try and sort out.

**Comment by jl626** [comment]
Many thanks for a quick fix. 
I also have the new error, (NVCC fail with exit status 1).

**Comment by MichaelHillier** [comment]
Since posting, I've tried different CUDA versions (10.0, 10.1, 10.2) and different VS compilers (2017 and 2019) and all produce the same nvcc.exe fail with exit status 1:

5 errors detected in the compilation of "C:/Users/Mike/AppData/Local/Temp/tmpxft_0000153c_00000000-10_scatter_cuda.cpp1.ii".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2\\bin\\nvcc.exe' failed with exit status 1

**Comment by rusty1s** [comment]
What is the exact error?

**Comment by MichaelHillier** [comment]
I can't see anymore details of the error other than what I posted. But here a log file containing all the output from running "python setup.py install" if that is helpful:

[log.txt](https://github.com/rusty1s/pytorch_scatter/files/4177761/log.txt)

**Comment by rusty1s** [comment]
Seems like this is the issue for you:
```
C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h(190): error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized
C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(467): error: member "torch::jit::script::detail::ModulePolicy::all_slots" may not be initialized
C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(480): error: member "torch::jit::script::detail::ParameterPolicy::all_slots" may not be initialized
C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(494): error: member "torch::jit::script::detail::BufferPolicy::all_slots" may not be initialized
C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(507): error: member "torch::jit::script::detail::AttributePolicy::all_slots" may not be initialized
```
The problem is that I am not sure how to fix it.

**Comment by rusty1s** [comment]
Seems related with a potential fix: https://github.com/pytorch/pytorch/issues/27958

**Comment by MichaelHillier** [comment]
I applied the potential fix changing "static constexpr size_t --> static const size_t" for all the affected lines in argument_spec.h and module.h as well as the pybind11 cast.h (1449) "return *(this->value); --> return *((type*)this->value);"

I no longer received the 5 errors earlier posted. However, I was getting link errors after that. I tried python setup.py install again and I didn't get the link error from the previous build but a new one. After I executed "python setup.py install" three times it said it installed torch_scatter. The 3 link errors are related to the 3 binaries that are produced from the build:
_scatter.pyd, _segmetn_coo.pyd, and _segment_csr.pyd

After it installed I inspected these files, and all of them were 0 KB in size. So although it said it was successfully built, it did not.

I confirmed this by running the test on the README.md. When trying to import the scatter_max module 3 errors are produced: Failed to load 'scatter', 'segment_csr', and 'segment_coo' binaries.

**Comment by Thorius** [comment]
I also fixed the compilation issues (additionally build pytorch from source, just in case) and I am getting the unresolved external symbols (`LINK : error LNK2001: unresolved external symbol PyInit__scatter` and the other main functions). Interestingly, I also get similar errors when building pytorch_sparse (linker errors).

Surprisingly,  I do not get these errors when building pytorch_cluster - that seems to use `PYBIND11_MODULE` explicitly. I see that _cpp_extensions.py_ form the PyTorch API defines those explicitly but maybe, it is not quite correct. I have been trying to see where the problem could come but this is the furthest I could take it.

**Comment by rusty1s** [comment]
Hi everyone, I can finally reproduce the error and am working on a solution (I will also try to provide python wheels in the future). In the meantime, it might be best to use `torch-scatter<2` and `torch-sparse=0.4.4` on Windows.

**Comment by MichaelHillier** [comment]
I can confirm that torch-scatter 1.4.0 is working on windows. 

Some details - I am using python 3.7 and pytorch 1.3.1. To successfully import torch_scatter module you will have to add the directory where the binaries are located (e.g. {pytorch_scatter_path}\build\lib.win-amd64-3.7\torch_scatter) to your path or run python from this directory.

**Comment by rusty1s** [comment]
I identified the issue! The following lines are missing in all extensions:
```
#ifdef _WIN32
    PyMODINIT_FUNC PyInit__scatter(void) { return NULL; }
#endif
```
I will run some more tests and will release a new version soon! Sorry for all the trouble :)

**Comment by MichaelHillier** [comment]
No worries. Thanks for creating this much needed extension to pytorch :)

**Comment by Thorius** [comment]
Sounds great! Thanks for quick response and solution!

Just out of curiosity, why are the dummy `PyInit__***` functions required? Is it because of PyBind11, PyTorch, Python or something else?

**Comment by pradeep-pyro** [comment]
Thanks everyone for chiming in!

**Comment by rusty1s** [comment]
There are no binaries available for major OS/CUDA combinations, see [here](https://github.com/rusty1s/pytorch_scatter#binaries). For a CUDA installation on Windows, you **will need** CUDA10.1 (other versions are currently bugged), and Python 3.8 is currently bugged as well. Python 3.6 and Python 3.7 should work fine. For installation, simply run:
```
pip install torch-scatter==latest+cu101 -f http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-scatter.s3-website.eu-central-1.amazonaws.com
```
I am also working on HTTPS support. Please let me know if installation works for you and whether you can successfully use `torch-scatter`.

**Comment by MichaelHillier** [comment]
`pip install torch-scatter==latest+cu101 -f http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-scatter.s3-website.eu-central-1.amazonaws.com`

works for me using python 3.7, CUDA10.1, and pytorch 1.4.0. Tested the sample code in the README.md and it is working.

I'll also mention that I was able to successfully install torch-geometric. To do this I:

1. Installed torch-scatter 
`pip install torch-scatter==latest+cu101 -f http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-scatter.s3-website.eu-central-1.amazonaws.com`
2. Installed torch-sparse
`pip install torch-sparse==latest+cu101 -f http://pytorch-sparse.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-sparse.s3-website.eu-central-1.amazonaws.com`
3. Installed torch-cluster
`pip install torch-cluster`
4. Installed torch-geometric
`pip install torch-geometric`

**Comment by rusty1s** [comment]
Glad that it is working. I am trying to improve the installation procedure further :)

**Comment by Thorius** [comment]
A suggestion, while we are discussing the installation experience, maybe it would be wise to have a small bash/cmd/powershell script in the pytorch_geometric repo that simply does the steps above (or a `python setup.py build_with_dependencies`) , so that people trying it out do not get confused or have to find this. That would also make it even easier to move to a regular (no `-f install`) in the near future.

**Comment by jl626** [comment]
`pip install torch-scatter==latest+cu101 -f http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-scatter.s3-website.eu-central-1.amazonaws.com` 

doesn't work for me.  It returns HTTP 403 error. Probably permission issue?

```
 HTTP error 403 while getting https://pytorch-scatter.s3.eu-central-1.amazonaws.com/whl/torch-1.4.0/torch_scatter-latest+cu101-cp36-cp36m-win_amd64.whl (from http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html)

Could not install requirement torch-scatter==latest+cu101 from https://pytorch-scatter.s3.eu-central-1.amazonaws.com/whl/torch-1.4.0/torch_scatter-latest+cu101-cp36-cp36m-win_amd64.whl because of error 403 Client Error: Forbidden for url: https://pytorch-scatter.s3.eu-central-1.amazonaws.com/whl/torch-1.4.0/torch_scatter-latest+cu101-cp36-cp36m-win_amd64.whl

Could not install requirement torch-scatter==latest+cu101 from https://pytorch-scatter.s3.eu-central-1.amazonaws.com/whl/torch-1.4.0/torch_scatter-latest+cu101-cp36-cp36m-win_amd64.whl because of HTTP error 403 Client Error: Forbidden for url: https://pytorch-scatter.s3.eu-central-1.amazonaws.com/whl/torch-1.4.0/torch_scatter-latest+cu101-cp36-cp36m-win_amd64.whl for URL https://pytorch-scatter.s3.eu-central-1.amazonaws.com/whl/torch-1.4.0/torch_scatter-latest+cu101-cp36-cp36m-win_amd64.whl (from http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html)
```

**Comment by rusty1s** [comment]
Should work again!

**Comment by jl626** [comment]
Many thanks for your prompt fix!

**Comment by rusty1s** [comment]
You can now install using HTTPS:
```
pip install torch-scatter==latest+${CUDA} -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
```
I am also working on a conda package that should eliminate the need of `-f` installs.

**Comment by mdcramer** [comment]
I don't have torch-scatter, but I getting these exact errors:
> ```
> C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/argument_spec.h(190): error: member "torch::jit::ArgumentSpecCreator::DEPTH_LIMIT" may not be initialized
> C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(467): error: member "torch::jit::script::detail::ModulePolicy::all_slots" may not be initialized
> C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(480): error: member "torch::jit::script::detail::ParameterPolicy::all_slots" may not be initialized
> C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(494): error: member "torch::jit::script::detail::BufferPolicy::all_slots" may not be initialized
> C:/Anaconda3/envs/MoNET/lib/site-packages/torch/include\torch/csrc/jit/script/module.h(507): error: member "torch::jit::script::detail::AttributePolicy::all_slots" may not be initialized
> ```
I was able to resolve the first error by following https://github.com/facebookresearch/detectron2/issues/9#issuecomment-549013090, but I'm unable to resolve the other 4 in `module.h`.

When I run `pip install torch-scatter==latest+${CUDA} -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html` I get this:
```
Looking in links: https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html
ERROR: Could not find a version that satisfies the requirement torch-scatter==latest+${CUDA} (from versions: latest+cpu, latest+cu101, 0.3.0, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 2.0.2, 2.0.3, 2.0.3+cpu, 2.0.3+cu101, 2.0.4, 2.0.4+cpu, 2.0.4+cu101)
ERROR: No matching distribution found for torch-scatter==latest+${CUDA}
```

I've got CUDA 10.1 with Python 3.7 and pytorch 1.4.0. Maybe I'm in the wrong thread, but thank you for the help!

**Comment by rusty1s** [comment]
Windows installation indeed needs some fixes to Pytorch, see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/script/torch.sh). I am still unsure why the installation of the binaries does not work for some. Can you try to do:
```
pip install https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0/torch_scatter-latest%2Bcu101-cp37-cp37m-win_amd64.whl
```

**Comment by mdcramer** [comment]
Thank you, @rusty1s ! I'm not using pytorch_scatter, which means I'm probably in the wrong place, but your link for the Windows install was exactly the solution I needed. I'm not sure how to get `torch.sh` to run automatically, using my local paths, but I was able to go through line by line and manually fix my files.
