### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ECNUHP** [rusty1s/pytorch_scatter#111]
hello i installed this package in linux with cuda 10, but there is a error:

 Collecting torch_scatter
  Downloading https://files.pythonhosted.org/packages/28/f7/fa4e61587169924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/lang.huo/miniconda3/envs/huopei/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r7p3nxki/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r7p3nxki/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ctt53ruk --python-tag cp36
       cwd: /tmp/pip-install-r7p3nxki/torch-scatter/
  Complete output (4206 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_broadcasting.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_gather.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_scatter.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_segment.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_zero_tensors.py -> build/lib.linux-x86_64-3.6/test
  copying test/utils.py -> build/lib.linux-x86_64-3.6/test
  creating build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.6/torch_scatter
  creating build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  running build_ext
  /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/utils/cpp_extension.py:216: UserWarning:

Can you offer some advice for me ? Thank you in advance.

**Comment by rusty1s** [comment]
Can you try to install from source and show me the complete log?

**Comment by ECNUHP** [comment]
> Can you try to install from source and show me the complete log?

pip install torch_scatter
Collecting torch_scatter
  Downloading https://files.pythonhosted.org/packages/28/f7/fa4e61587169924203a32416f7835939fdd79994eaa429b4f8ef8f0e07e2/torch_scatter-2.0.2.tar.gz
Building wheels for collected packages: torch-scatter
  Building wheel for torch-scatter (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/lang.huo/miniconda3/envs/huopei/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r7p3nxki/torch-scatter/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r7p3nxki/torch-scatter/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ctt53ruk --python-tag cp36
       cwd: /tmp/pip-install-r7p3nxki/torch-scatter/
  Complete output (4206 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_broadcasting.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_gather.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_scatter.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_segment.py -> build/lib.linux-x86_64-3.6/test
  copying test/test_zero_tensors.py -> build/lib.linux-x86_64-3.6/test
  copying test/utils.py -> build/lib.linux-x86_64-3.6/test
  creating build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/scatter.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/segment_coo.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/segment_csr.py -> build/lib.linux-x86_64-3.6/torch_scatter
  copying torch_scatter/utils.py -> build/lib.linux-x86_64-3.6/torch_scatter
  creating build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/logsumexp.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/softmax.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  copying torch_scatter/composite/std.py -> build/lib.linux-x86_64-3.6/torch_scatter/composite
  running build_ext
  /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/utils/cpp_extension.py:216: UserWarning:

                                 !! WARNING !!

  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
  Please use a compiler that is ABI-compatible with GCC 4.9 and above.
  See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

  See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
  for instructions on how to install GCC 4.9 or higher.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                                !! WARNING !!

    warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
  building 'torch_scatter._scatter' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/tmp
  creating build/temp.linux-x86_64-3.6/tmp/pip-install-r7p3nxki
  creating build/temp.linux-x86_64-3.6/tmp/pip-install-r7p3nxki/torch-scatter
  creating build/temp.linux-x86_64-3.6/tmp/pip-install-r7p3nxki/torch-scatter/csrc
  creating build/temp.linux-x86_64-3.6/tmp/pip-install-r7p3nxki/torch-scatter/csrc/cpu
  creating build/temp.linux-x86_64-3.6/tmp/pip-install-r7p3nxki/torch-scatter/csrc/cuda
  gcc -pthread -B /opt/lang.huo/miniconda3/envs/huopei/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/tmp/pip-install-r7p3nxki/torch-scatter/csrc -I/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include -I/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/TH -I/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.0/include -I/opt/lang.huo/miniconda3/envs/huopei/include/python3.6m -c /tmp/pip-install-r7p3nxki/torch-scatter/csrc/scatter.cpp -o build/temp.linux-x86_64-3.6/tmp/pip-install-r7p3nxki/torch-scatter/csrc/scatter.o -O0 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_scatter -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [默认启用]
  In file included from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/util/ArrayRef.h:19:0,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/core/MemoryFormat.h:5,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:5,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                   from /tmp/pip-install-r7p3nxki/torch-scatter/csrc/scatter.cpp:1:
  /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/util/C++17.h:17:2: 错误：#error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
   #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 5 or later."
    ^
  In file included from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/util/typeid.h:27:0,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/core/ScalarType.h:6,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/core/Scalar.h:9,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/core/TensorBody.h:7,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:11,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/torch/script.h:3,
                   from /tmp/pip-install-r7p3nxki/torch-scatter/csrc/scatter.cpp:1:
  /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/c10/util/TypeIndex.h:31:2: 错误：#error "You're running a too old version of GCC. We need GCC 5 or later."
   #error "You're running a too old version of GCC. We need GCC 5 or later."
    ^
  In file included from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/core/TensorMethods.h:10:0,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/Tensor.h:12,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/Context.h:4,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/ATen/ATen.h:5,
                   from /opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,

**Comment by ECNUHP** [comment]
> Can you try to install from source and show me the complete log?

I want to know this package whether is limited to the GCC version?

I see the error log:
"You're running a too old version of GCC. We need GCC 5 or later."

**Comment by rusty1s** [comment]
Yes, you need GCC 5 or later.

**Comment by cfd1** [comment]
Hi,

I have the same issue. I can't change the system gcc, but I do have a local install of gcc 6.2.0.
The system nvcc is release 10.1 and I'm using an anaconda environment.
I have set the following environment variables to point to the newer gcc
PATH
LD_LIBRARY_PATH
DYLD_LIBRARY_PATH
CC
CXX
CUDA_HOST_COMPILER

To compile I use
python -m pip install --verbose --no-cache-dir torch-scatter
this worked for the previous version of torch-scatter, but now. 

Do you have any suggestions how to get it to pick up the newer version of gcc?

Thanks

**Comment by rusty1s** [comment]
Do you get the error that your `gcc` is too old? Normally, it should be enough to just set `CC` and `CXX` to the respective gcc path, but you should verify that by installing from source.

**Comment by cfd1** [comment]
Thanks. Compiling from source worked with a modification to the setup.py to have --compiler-bindir explicitly set to the new gcc for the nvcc_flags

**Comment by ECNUHP** [comment]
hello , after I update the gcc version to gcc 5.5.0
And I install your package successfully using command 'pip install torch-sactter'
But there is a problem after running the following program:

 import torch
>>> from torch_scatter import scatter_max
/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter/scatter.py:13: UserWarning: Failed to load `scatter` binaries.
  warnings.warn('Failed to load `scatter` binaries.')
/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter/segment_csr.py:11: UserWarning: Failed to load `segment_csr` binaries.
  warnings.warn('Failed to load `segment_csr` binaries.')
/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter/segment_coo.py:11: UserWarning: Failed to load `segment_coo` binaries.
  warnings.warn('Failed to load `segment_coo` binaries.')
>>>
>>> src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
>>> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
>>>
>>> out, argmax = scatter_max(src, index, dim=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
torch.jit.Error: Exception
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter/scatter.py", line 19
                                     dim_size: Optional[int]
                                     ) -> Tuple[torch.Tensor, torch.Tensor]:
        raise ImportError
        ~~~~~~~~~~~~~~~~~ <--- HERE
        return src, index


Could you please offer some advice for me ? Thank you in advance!

**Comment by ECNUHP** [comment]
> Thanks. Compiling from source worked with a modification to the setup.py to have --compiler-bindir explicitly set to the new gcc for the nvcc_flags

hello , can you teach me how to install this package from source and how to modify setup.py? Thank you in anvance.

**Comment by cfd1** [comment]
You need to download the package from git and then navigate to the pytorch_scatter directory

You need to set the following environment variables
```export PATH=$PATH:/usr/local/cuda/bin/ ```
```export CPATH=/usr/local/cuda/include/ ```
```export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:/path/to/gcc/lib64/ ```
```export DYLD_LIBRARY_PATH=/usr/local/cuda/lib/:/path/to/gcc/lib ```
```export CC=/path/to/gcc/bin/g++  ```
```export CXX=/path/to/gcc/bin/g++ ```

In the setup.py I added this to the list for the nvcc_flags on line 34
``` --compiler-bindir=/path/to/gcc/bin/```

then you can type
```python setup.py install```
then 
```python setup.py test``` and make sure you pass all the tests. If you fail any then something has gone wrong.

**Comment by ECNUHP** [comment]
> You need to download the package from git and then navigate to the pytorch_scatter directory
> 
> You need to set the following environment variables
> `export PATH=$PATH:/usr/local/cuda/bin/ `
> `export CPATH=/usr/local/cuda/include/ `
> `export LD_LIBRARY_PATH=/usr/local/cuda/lib64/:/path/to/gcc/lib64/ `
> `export DYLD_LIBRARY_PATH=/usr/local/cuda/lib/:/path/to/gcc/lib `
> `export CC=/path/to/gcc/bin/g++  `
> `export CXX=/path/to/gcc/bin/g++ `
> 
> In the setup.py I added this to the list for the nvcc_flags on line 34
> ` --compiler-bindir=/path/to/gcc/bin/`
> 
> then you can type
> `python setup.py install`
> then
> `python setup.py test` and make sure you pass all the tests. If you fail any then something has gone wrong.

Wow ，it's amazing! Successfully! Thank you so much for your effective reply.
Best wishes for you!

**Comment by cfd1** [comment]
I'm glad it worked. You will need to do a similar trick for the other modules as well if you are installing pytorch_geometric.

**Comment by ECNUHP** [comment]
> I'm glad it worked. You will need to do a similar trick for the other modules as well if you are installing pytorch_geometric.

OK, I got it. Thank you so much .
