### ISSUE TITLE
error scatter_max

### ISSUE THREAD

**Issue by ECNUHP** [rusty1s/pytorch_scatter#114]
hello ! I install your repo ,but there is a error in  the function about 'scatter_max' is error. And I don‘t know what the mean of this function.

 >>>src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
>>> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
>>> out, argmax = scatter_max(src, index, dim=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
torch.jit.Error: Exception
The above operation failed in interpreter.
Traceback (most recent call last):
  File "/opt/lang.huo/pytorch_scatter-master/torch_scatter/scatter.py", line 19
                                     dim_size: Optional[int]
                                     ) -> Tuple[torch.Tensor, torch.Tensor]:
        raise ImportError
        ~~~~~~~~~~~~~~~~~ <--- HERE
        return src, index

**Comment by rusty1s** [comment]
That means that installation failed (it should output a warning when importing `torch-scatter`). You should indicate the error during installation.

**Comment by ECNUHP** [comment]
> That means that installation failed (it should output a warning when importing `torch-scatter`). You should indicate the error during installation.

Thank you for your reply, I try to install it again.

**Comment by ECNUHP** [comment]
> That means that installation failed (it should output a warning when importing `torch-scatter`). You should indicate the error during installation.
there are three warning when importing:
 import torch_scatter
/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter-2.0.2-py3.6-linux-x86_64.egg/torch_scatter/scatter.py:13: UserWarning: Failed to load `scatter` binaries.
  warnings.warn('Failed to load `scatter` binaries.')
/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter-2.0.2-py3.6-linux-x86_64.egg/torch_scatter/segment_csr.py:11: UserWarning: Failed to load `segment_csr` binaries.
  warnings.warn('Failed to load `segment_csr` binaries.')
/opt/lang.huo/miniconda3/envs/huopei/lib/python3.6/site-packages/torch_scatter-2.0.2-py3.6-linux-x86_64.egg/torch_scatter/segment_coo.py:11: UserWarning: Failed to load `segment_coo` binaries.
  warnings.warn('Failed to load `segment_coo` binaries.')

**Comment by ECNUHP** [comment]
> That means that installation failed (it should output a warning when importing `torch-scatter`). You should indicate the error during installation.

There are no errors when installing this package from source ,but when  executing this procedure it still meet this error:
out, argmax = scatter_max(src, index, dim=-1)
Traceback (most recent call last):
File "", line 1, in
torch.jit.Error: Exception
The above operation failed in interpreter.
Traceback (most recent call last):
File "/opt/lang.huo/pytorch_scatter-master/torch_scatter/scatter.py", line 19
dim_size: Optional[int]
) -> Tuple[torch.Tensor, torch.Tensor]:
raise ImportError
~~~~~~~~~~~~~~~~~ <--- HERE
return src, index

**Comment by snash4** [comment]
same issues:
Cuda 10.1
pytorch 1.4.0 installed using Pip, confirmed the correct CUDA version
installed torch-scatter using Pip

So, since the installation has failed, how to correctly install it?
Please give some pointers to try.
Thanks.

_

**Comment by snash4** [comment]
compiled  from source successfully, but then the tests fail
========= 1295 failed, 475 passed, 3 warnings in 31.52s ==

**Comment by ECNUHP** [comment]
> compiled from source successfully, but then the tests fail
> ========= 1295 failed, 475 passed, 3 warnings in 31.52s ==

Maybe you can reference the post of  issue  'install error' https://github.com/rusty1s/pytorch_scatter/issues/111
