### ISSUE TITLE
why no ‘torch_scatter-latest+cu101-cp38-cp38m-win_amd64.whl’

### ISSUE THREAD

**Issue by wutaiqiang** [rusty1s/pytorch_scatter#116]
there exists：torch_scatter-latest+cu101-cp37-cp37m-win_amd64.whl

**Comment by wutaiqiang** [comment]
however the latest python version is 3.8 and the pytorch version supporting cuda is 10.1【though the latest cuda version is 10.2】,thanks for your time

**Comment by rusty1s** [comment]
There is currently an error that prevents me from shipping wheels for Python 3.8 with CUDA10.1 on Windows. I will work on it but I am not sure if its fixable.

**Comment by wutaiqiang** [comment]
sorry to trouble you again , seems that the .whl file in the website 'http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html' can not be download, could you plz send the file (torch_scatter-latest+cu101-cp37-cp37m-win_amd64.whl) to my email ？2795823986@qq.com，thanks a lot

**Comment by rusty1s** [comment]
Should work again!

**Comment by wutaiqiang** [comment]
Cool，thanks a lot
