### ISSUE TITLE
Forward pass fine, backward error, segment_csr (mean)

### ISSUE THREAD

**Issue by kshre** [rusty1s/pytorch_scatter#118]
I get the following error with segment_csr during loss.backward(), I checked that the forward pass runs fine.

RuntimeError: The size of tensor a (177) must match the size of tensor b (2) at non-singleton dimension 1
> /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/autograd/__init__.py(99)backward()
     97     Variable._execution_engine.run_backward(
     98         tensors, grad_tensors, retain_graph, create_graph,
---> 99         allow_unreachable=True)  # allow_unreachable flag
    100 
    101

**Comment by rusty1s** [comment]
Can you show me a minimal example to reproduce the error?

**Comment by kshre** [comment]
Okay I figured it out, if you use "mean" reduction and the index pointer has contiguous indices that are equal leads to some kind of divide by zero error in the backend I think.

Anyways one fix to this is to use "sum" reduction and divide by the number of indices grouped.

Here is an example where segment_csr "mean" fails during backward pass:
`import torch
from torch_scatter import segment_csr 
src = torch.randn(2, 6, 12)
src.requires_grad=True

index_pairs = torch.tensor([[ [1,  2],  [2,  3] ],
                            [ [1,  4],  [3,  5] ]])
index_pairs_flattened = torch.flatten(index_pairs, 1)

out = segment_csr(src, index_pairs_flattened, reduce="mean")

out = out[:,0::2,:]

for row in range(out.shape[0]):
  for n in range(out.shape[1]):
    start = index_pairs_flattened[row, (n*2)].item()
    end   = index_pairs_flattened[row, (n*2+1)].item()
    print(out[row,n,:] == torch.sum(src[row,start:end,:],dim=0).squeeze() / (end - start))

print(out.shape)

torch.sum(out).backward()`

and here is one where sum and division circumvents it:
`import torch
from torch_scatter import segment_csr 
src = torch.randn(2, 6, 12)
src.requires_grad=True

index_pairs = torch.tensor([[ [1,  2],  [2,  3] ],
                            [ [1,  4],  [3,  5] ]])
index_pairs_flattened = torch.flatten(index_pairs, 1)

out = segment_csr(src, index_pairs_flattened, reduce="sum")

out = out[:,0::2,:]
out = out / (index_pairs[:,:,1]-index_pairs[:,:,0]).unsqueeze(dim=2)

for row in range(out.shape[0]):
  for n in range(out.shape[1]):
    start = index_pairs_flattened[row, (n*2)].item()
    end   = index_pairs_flattened[row, (n*2+1)].item()
    print(out[row,n,:] == torch.sum(src[row,start:end,:],dim=0).squeeze() / (end - start))

print(out.shape)

torch.sum(out).backward()`

**Comment by rusty1s** [comment]
I see, the reason for that is that your index tensor is not correct. It **needs to start with a zero** and **needs to end with the size of the respective dimension**. For example,
```python
src = torch.randn(2, 6, 12)
src.requires_grad=True

ptr = torch.tensor([[0, 1, 2, 3, 6], [0, 1, 4, 5, 6]])
out = segment_csr(src, ptr, reduce="mean")
```
should work fine. Furthermore, you can skip groups by passing the same index twice to `ptr`, *.e.g.*, `torch.tensor([0, 2, 2, 5, 6])`.

In the one-dimensional case, it computes `out[i] = src[ptr[i]:ptr[i+1]].mean()`.

**Comment by boredtylin** [comment]
Does the constraint that the index tensor "needs to start with a zero and needs to end with the size of the respective dimension" holds for all reduce methods? It seems that using "max" as the reduce method in this case works fine with incorrect index tensor...

**Comment by rusty1s** [comment]
This should hold for all reduce methods. Do you have a script to reproduce what you mean?

**Comment by boredtylin** [comment]
Let's say take the example you provide above and replace the last indices of `ptr` to `5` (which would break the constraint that index should end with the size of the respective dim):
```python
src = torch.randn(2, 6, 12)
src.requires_grad=True

ptr = torch.tensor([[0, 1, 2, 3, 5], [0, 1, 4, 5, 5]])
out = segment_csr(src, ptr, reduce="mean")
torch.sum(out).backward()
```
This will, indeed, trigger a Runtime Error. However, it seems that `max` or `sum` reduce methods do not have this issue.
```python
src = torch.randn(2, 6, 12)
src.requires_grad=True

ptr = torch.tensor([[0, 1, 2, 3, 5], [0, 1, 4, 5, 5]])
out = segment_csr(src, ptr, reduce="max") #This line is changed.
torch.sum(out).backward()
```

I am using `torch_scatter==2.1.1`.

**Comment by rusty1s** [comment]
Got it. The code should definitely break for indices that do result in an out-of-index issue (such as having `ptr = [0, 1, 2, 3, 7]`), but we don't actually assert for `src.size() == ptr[-1]`.

**Comment by boredtylin** [comment]
Still have no clue why it should break for `reduce='mean'` but not `reduce='max'`, though...

**Comment by rusty1s** [comment]
That's because we need to incorporate the segment count into the backward step, which leads to a shape mismatch if `x.size(1)` does not align with `ptr[-1]`.
