### ISSUE TITLE
Build cuda without cuda?

### ISSUE THREAD

**Issue by AntoinePrv** [rusty1s/pytorch_scatter#12]
Hello,

I have build my project, and resolve its dependencies when building a [Singularity](https://www.sylabs.io/docs/) image (think Docker without sudo rights for executing).
I need sudo rights to build the image, so I do it on my machine, without GPU, and run the image on a cluster with GPU (there is a special flag to expose the GPU driver).

When I build my image, I take the PyTorch version with GPU, even though I don't have any when I do the install. This does not give me any problem and I can run GPU code when I deploy.

Now, resolving `pytorch_scatter` (_et. al._), [this](https://github.com/rusty1s/pytorch_scatter/blob/cfa8554a3ebac581dea1df7fb1d6064bcca8c3cd/setup.py#L12) resolves to False and the Cuda extension is not built. I get at run-time:
```
/usr/lib/python3.7/site-packages/torch_scatter/utils/ext.py:5: in <module>
    import scatter_cuda
E   ModuleNotFoundError: No module named 'scatter_cuda'
```

Is it possible to change the test `torch.cuda.is_available()` in [setup.py](https://github.com/rusty1s/pytorch_scatter/blob/cfa8554a3ebac581dea1df7fb1d6064bcca8c3cd/setup.py#L12) to something less strong, _i.e._ ensuring that the extension can be built but not that there is a full Cuda run-time?
I'm not even sure that's possible...

Thanks

**Comment by rusty1s** [comment]
Hi,
interesting question. I looked up the source code for the [cpp_extension file](https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py) and we could try to replace the call to `torch.cuda.is_available()` with something like `_find_cuda_home()`. Could you do me a favour and try if this fits your needs?

**Comment by AntoinePrv** [comment]
Sure, will let you know as soon as I have something.
