### ISSUE TITLE
mac import error: Symbol not found

### ISSUE THREAD

**Issue by Stevring** [rusty1s/pytorch_scatter#120]
I successfully installed torch_scatter using `pip install torch_scatter`,
but when I try to import it, the following error occurs:

from torch_scatter import scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "anaconda3/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "anaconda3/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: dlopen(anaconda3/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-darwin.so, 2): Symbol not found: __ZN6caffe26detail36_typeMetaDataInstance_preallocated_0E
  Referenced from: anaconda3/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-darwin.so
  Expected in: flat namespace
 in anaconda3/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-darwin.so

**Comment by rusty1s** [comment]
Do you have multiple PyTorch versions on your machine? This may be caused by it. The easiest would be to just use on the provided [Python wheels](https://github.com/rusty1s/pytorch_scatter#binaries).

**Comment by Stevring** [comment]
I have only pytorch 1.4.0 installed. But the python wheels works for me, thanks.
