### ISSUE TITLE
"fill_value" missed from current API

### ISSUE THREAD

**Issue by david-leon** [rusty1s/pytorch_scatter#121]
First congratulations @rusty1s for merging torch-scatter into pytorch master.
I noticed that the `fill_value` param is missed from the current API, so what's their default values now for different reduction method (max, min, mean, add)?

I ask because the previous default `fill_value` for `max` and `min` reduction methods are not appropriate (`numpy.finfo(numpy.float32).max` and `numpy.finfo(numpy.float32).min`) for me. I'd prefer them set to zero in my case.

**Comment by rusty1s** [comment]
It will add zero entries for every group index missing in the index tensor, but will not clamp the values for other indices at zero. So if you still want that behaviour, you need to clamp the values afterwards :)

**Comment by david-leon** [comment]
> t will add zero entries for every group index missing in the index tensor

So if I got this right, it means `fill_value = 0` by default, right?

>  but will not clamp the values for other indices at zero

I didn't get this, what do you mean by `clamp` here?

**Comment by rusty1s** [comment]
I mean that
```
src = torch.tensor([-2, -3, 3])
idx = torch.tensor([ 0,  0, 2])
scatter_max(src, idx)
```
now ouputs
```
[-2, 0, 3]
```
which is exactly what you would expect. It does not clamp the values below zero to zero, but it will add zeros to all the indices that are not present in the `idx` tensor.

**Comment by david-leon** [comment]
Yes that's exactly what I expect. Thanks for the clarification.

**Comment by rusty1s** [comment]
I removed the `fill_value` flag because it caused a lot of unexpected behavior for many users. If you still want the old behavior, I recommend to input the `out` tensor to `scatter` containing the initial values.

**Comment by klicperajo** [comment]
Okay, I'll just write a wrapper for that and then all will be good again in my code world. ;)

**Comment by klicperajo** [comment]
I just tried doing the same with `segment_csr`, but that doesn't seem to work since it apparently overwrites all values in the `out` tensor. Any suggestions?

**Comment by rusty1s** [comment]
If you are relying on `ptr` for aggregation, you may want to find the indices with zero aggregation elements and set them manually afterwards:
```python
count = ptr[1:] - ptr[:-1]
mask = count == 0
out[mask] = float('-inf')
```

**Comment by klicperajo** [comment]
I've tried using

```python
mask = ptr[1:] == ptr[:-1]
out[mask] = fill_value
```

and it works, but it's slower than `segment_coo`. So I'll just stick with that.
