### ISSUE TITLE
Add support for half

### ISSUE THREAD

**Issue by fuzihaofzh** [rusty1s/pytorch_scatter#126]
Is it possible to add support for half? I encountered the following problem:
RuntimeError: "scatter_max_kernel" not implemented for 'Half' (operator() at cuda/scatter_kernel.cu:129)

**Comment by rusty1s** [comment]
I already looked into it and I feel that this is a lot of work to implement for nearly no gains at all. Most of the code needs to be rewritten (something like `a + b` does not work anymore), and there are no runtimes improvements at all on most of the available GPUs. If you want to look at it, feel free to do so and we can discuss the details.

**Comment by fuzihaofzh** [comment]
Hi, thanks for your reply. I use this function as part of my code, so, it's not efficient to convert a tensor into  float32 and send it into scatter and then convert it back. The most efficient way is just to use a native support for float16. I do understand that it may incur a lot of reconstruction. I think we can list this as a new feature, if others also have this problem, we can consider to do the reimplementation.
