### ISSUE TITLE
This package provides scatter_add, scatter_max, scatter_min, why not provide the scatter_mul?

### ISSUE THREAD

**Issue by THHHomas** [rusty1s/pytorch_scatter#127]
scatter_mul(src, index, other, dim=0) 
src[index[I], j, k] *= other[I, j, k]

**Comment by rusty1s** [comment]
This got lost in the major rewrite. If you need this function, try `torch-scatter<2.0`

**Comment by Wang-Tianyu** [comment]
If there any way to use scatter_mul with torch_scatter > 2.0?
scatter_mul and scatter_add are important for normalizing graph features across each graph.
Scatter_add in the latest version is just an alias for scatter_sum.

It is possible to copy some of the code from torch-scatter<2.0 then make them work independently?

**Comment by rusty1s** [comment]
I just added `scatter_mul` back into the master branch!
