### ISSUE TITLE
Error Installing torch_sparse and torch_scatter

### ISSUE THREAD

**Issue by masterclown1** [rusty1s/pytorch_scatter#128]
I have been trying to download torch_sparse and torch_scatter through CPU and receive this issue when I run the following command:

pip install torch_sparse

Collecting torch_sparse
  Using cached torch_sparse-0.6.0.tar.gz (29 kB)
Requirement already satisfied: scipy in /anaconda3/lib/python3.6/site-packages (from torch_sparse) (1.0.1)
Building wheels for collected packages: torch-sparse
  Building wheel for torch-sparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/setup.py'"'"'; __file__='"'"'/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-wheel-bsntj5a_
       cwd: /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/
  Complete output (70 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/matmul.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/permute.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/add.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/reduce.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/narrow.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/masked_select.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/cat.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/eye.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/convert.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/coalesce.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/tensor.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/mul.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/transpose.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/utils.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/diag.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/storage.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/spspmm.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/index_select.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/select.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/spmm.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  copying torch_sparse/metis.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
  running build_ext
  /anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning:
  
                                 !! WARNING !!
  
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Your compiler (g++) is not compatible with the compiler Pytorch was
  built with for this platform, which is clang++ on darwin. Please
  use clang++ to to compile your extension. Alternatively, you may
  compile PyTorch from source using g++, and then you can also use
  g++ to compile your extension.
  
  See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
  with compiling PyTorch from source.
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
                                !! WARNING !!
  
    platform=sys.platform))
  building 'torch_sparse._spspmm' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/private
  creating build/temp.macosx-10.9-x86_64-3.6/private/var
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc
  creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/cpu
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc -I/anaconda3/lib/python3.6/site-packages/torch/include -I/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/anaconda3/include/python3.6m -c /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/spspmm.cpp -o build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_spspmm -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                   from /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                   from /anaconda3/include/python3.6m/Python.h:11,
                   from /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/spspmm.cpp:1:
  /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                                                               ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for torch-sparse
  Running setup.py clean for torch-sparse
Failed to build torch-sparse
Installing collected packages: torch-sparse
    Running setup.py install for torch-sparse ... error
    ERROR: Command errored out with exit status 1:
     command: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/setup.py'"'"'; __file__='"'"'/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-record-lk5mhl9i/install-record.txt --single-version-externally-managed --compile --install-headers /anaconda3/include/python3.6m/torch-sparse
         cwd: /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/
    Complete output (70 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/matmul.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/permute.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/add.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/reduce.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/narrow.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/masked_select.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/cat.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/eye.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/convert.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/coalesce.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/tensor.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/mul.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/transpose.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/utils.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/diag.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/storage.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/spspmm.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/index_select.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/select.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/spmm.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    copying torch_sparse/metis.py -> build/lib.macosx-10.9-x86_64-3.6/torch_sparse
    running build_ext
    /anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py:191: UserWarning:
    
                                   !! WARNING !!
    
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    Your compiler (g++) is not compatible with the compiler Pytorch was
    built with for this platform, which is clang++ on darwin. Please
    use clang++ to to compile your extension. Alternatively, you may
    compile PyTorch from source using g++, and then you can also use
    g++ to compile your extension.
    
    See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
    with compiling PyTorch from source.
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    
                                  !! WARNING !!
    
      platform=sys.platform))
    building 'torch_sparse._spspmm' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/private
    creating build/temp.macosx-10.9-x86_64-3.6/private/var
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc
    creating build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/cpu
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc -I/anaconda3/lib/python3.6/site-packages/torch/include -I/anaconda3/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/anaconda3/lib/python3.6/site-packages/torch/include/TH -I/anaconda3/lib/python3.6/site-packages/torch/include/THC -I/anaconda3/include/python3.6m -c /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/spspmm.cpp -o build/temp.macosx-10.9-x86_64-3.6/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/spspmm.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_spspmm -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/syslimits.h:7:0,
                     from /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:34,
                     from /anaconda3/include/python3.6m/Python.h:11,
                     from /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/csrc/spspmm.cpp:1:
    /anaconda3/lib/gcc/x86_64-apple-darwin11.4.2/4.8.5/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                                                                 ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/setup.py'"'"'; __file__='"'"'/private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-install-g4yzyph4/torch-sparse/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hk/mz9jwzt50r38p29kx6hjl0vm0000gn/T/pip-record-lk5mhl9i/install-record.txt --single-version-externally-managed --compile --install-headers /anaconda3/include/python3.6m/torch-sparse Check the logs for full command output.

**Comment by wutaiqiang** [comment]
you can try to download the .whl and install .whl file directly，the link is in the README.file
