### ISSUE TITLE
Question: Slight variant of scatter

### ISSUE THREAD

**Issue by Optimox** [rusty1s/pytorch_scatter#130]
Hello,

I know it's not directly related to the repo but I want to do something quite similar to scatter_max but I'm not sure how to do it optimally.

Let's say I have `x = [ 1, 2, 3, 4, 5]` and `groups = [0, 1, 2, 0, 1]`  using scatter_max the results will be aggregated to `[4, 5, 3]` but what I'd like to do is simply replace each element by the max of it's corresponding group then the results would be `[4, 5, 3, 4, 5]`

Do you know how I could to this properly?

**Comment by rusty1s** [comment]
```
out = scatter_max(src, index)
out = out[index]
```

**Comment by Optimox** [comment]
oh yeah indexing... Thank you so much for the fast reply!
