### ISSUE TITLE
OSError: /home/unreal/miniconda3/envs/pytorch/lib/python3.6/site-packages/torch_sparse/_version.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

### ISSUE THREAD

**Issue by unrealMJ** [rusty1s/pytorch_scatter#133]

**Comment by rusty1s** [comment]
That usually indicates that either you have multiple PyTorch versions installed or having an inconsistent CUDA setup.

**Comment by unrealMJ** [comment]
Yes，I just found it . Thank you for your help~ @rusty1s
