### ISSUE TITLE
scatter_inner_product and scatter_hadamard

### ISSUE THREAD

**Issue by AranKomat** [rusty1s/pytorch_scatter#135]
I wrote scatter_inner_product [here](https://gist.github.com/AranKomat/95ede74b27f16efc8c114b950f1a2a9e). I believe this is useful for hierarchical clustering (e.g. hier. k-means), some GNN and etc. I can also write scatter_hadamard, but I haven't finished it yet, since there may not be a demand for it. I hope somebody will use custom cuda kernel to write scatter_matmul and scatter_einsum.

**Comment by rusty1s** [comment]
Thanks for letting me know. This looks really good.
