### ISSUE TITLE
Use scikit-build for CMake build

### ISSUE THREAD

**Issue by cmpute** [rusty1s/pytorch_scatter#136]
Just a recommendation for [scikit-build](https://github.com/scikit-build/scikit-build), which is able to handle compilation of C++ extension. In this way you can write all the path and linker flags inside CMakeLists.txt and let cmake handle building even for python. Hopefully this will also help with cross-platform builds.

Also newer version CMake already support CUDA build, so you don't need to explicit find CUDA path in the setup script.

If you're interested, I can help with this~

**Comment by rusty1s** [comment]
Hi, I mostly followed [torchvision](https://github.com/pytorch/vision/blob/master/CMakeLists.txt) for setting this up. If you have better ways to set this up, please feel free to propose some changes :)
