### ISSUE TITLE
Can I install torch-scatter >=2.0.2 with cuda 9.0?

### ISSUE THREAD

**Issue by OrdinaryCrazy** [rusty1s/pytorch_scatter#139]
Can I install torch-scatter >=2.0.2 with cuda 9.0?

Sorry, but I do not have privilege to upgrade our nividia driver to support cuda9.2 or above

**Comment by rusty1s** [comment]
Your CUDA setup and the output of `torch.version.cuda` need to match, and as far as I am aware of, PyTorch 1.4 only comes with support for CUDA >= 9.2. I am sorry :(

**Comment by OrdinaryCrazy** [comment]
ok, I also find many of your new functions do not support cuda90 to install
