### ISSUE TITLE
Add operation scatter_one

### ISSUE THREAD

**Issue by davidlandry93** [rusty1s/pytorch_scatter#141]
Hello,

I don't know how complex my suggestion is to implement but I foud a need for a `scatter_one` function that would only use the first element found as an aggregation. Or choose one point pseudo-randomly.

This would prouve useful in pytorch_geometric, for instance in the `pool_pos` function: 

https://github.com/rusty1s/pytorch_geometric/blob/995a73784557d9a3bb396c0f2f6ff960b5f886ee/torch_geometric/nn/pool/pool.py#L20

Right now it is forwarded to `scatter_mean`.  When dealing with point clouds you sometimes want to pick one of the corresponding points, without averaging. This makes sure that the point you pick "exists".

One could use `scatter_max` to approximate this, but I worry about intorducing a bias where we "shift" the whole point cloud towards higher x, y and z values.

**Comment by rusty1s** [comment]
This is exactly what `torch.scatter_` is doing :)

**Comment by davidlandry93** [comment]
Well, thanks for that!
Keep up the good work
