### ISSUE TITLE
Unknown builtin op: torch_scatter::scatter_max

### ISSUE THREAD

**Issue by ryan2x** [rusty1s/pytorch_scatter#147]
When I tried to load TorchScript module from C++, I got the error

`
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():  
Unknown builtin op: torch_scatter::scatter_max.
Could not find any similar ops to torch_scatter::scatter_max. This op may not exist or may not be currently supported in TorchScript.
:
  File "/opt/conda/lib/python3.7/site-packages/torch_scatter/scatter.py", line 72
`

The model is trained using PyTorch 1.5.0 and latest pytorch geometric, and torch scatter 2.0.5, and I converted the trained model to TorchScript. I noted the document from https://pytorch-geometric.readthedocs.io/en/latest/notes/jit.html. But it did not mention how to load the custom operators such as torch_scatter::scatter_max. The serving environment is C++, and that's a separate environment from the training environment.

How can I resolve this error for TorchScript serving using C++?

**Comment by rusty1s** [comment]
That's correct. This information is currently missing in the tutorial. You need to also build the `torch-scatter` C++ API, see [here](https://github.com/rusty1s/pytorch_scatter#c-api). You can find a complete example of serving a model [here](https://github.com/lgray/triton-torchgeo-gat-example).

**Comment by ryan2x** [comment]
Thanks for your prompt response. After installing torch-scatter C++ API, that is libtorchscatter.so, I can get TorchScript serving using C++ working.

**Comment by bs1119** [comment]
> Thanks for your prompt response. After installing torch-scatter C++ API, that is libtorchscatter.so, I can get TorchScript serving using C++ working.

can you explain how to "installing torch-scatter C++ API" exactly? I want to do a similar thing in windows using VS2017.

**Comment by rusty1s** [comment]
See https://github.com/rusty1s/pytorch_geometric/issues/1718#issuecomment-779780517.

**Comment by zdwmeta** [comment]
Hi @rusty1s, I am able to compile and run the following code:
```
#include <iostream>
#include <torch/torch.h>
#include <torchsparse/sparse.h>

int main() {
  torch::Tensor src = torch::tensor({0.5, 0.4, 0.1, 0.6});
  torch::Tensor index = torch::tensor({0, 0, 1, 1});
  std::cout << src << std::endl;
  std::cout << index << std::endl;
  std::cout << std::get<0>(
                   scatter_min(src, index, 0, torch::nullopt, torch::nullopt))
            << std::endl;
}
```

However, when running inference with PyG script module, I am still getting the error: `Unknown builtin op: torch_scatter::scatter_min`. Do you have any idea why this could still happen?

**Comment by rusty1s** [comment]
Did you take a look at https://github.com/pyg-team/pytorch_geometric/tree/master/examples/cpp? Does it work for you?
