### ISSUE TITLE
Faster `dim_size` in `segment_coo`

### ISSUE THREAD

**Issue by klicperajo** [rusty1s/pytorch_scatter#148]
Since the indices in segment_coo are sorted, calling `index.max()` as e.g. here:
https://github.com/rusty1s/pytorch_scatter/blob/524326d01ca66c47407f1555871d14964288615e/csrc/cuda/segment_coo_cuda.cu#L187

is not necessary. It would be faster to directly use `index[-1] + 1`.

**Comment by rusty1s** [comment]
Good request. Added to master in https://github.com/rusty1s/pytorch_scatter/commit/54d23137332fae5da67aaf7e7e8834b355cdb8c6.
