### ISSUE TITLE
scatter_sum tries to assign to torch.Size

### ISSUE THREAD

**Issue by mmjb** [rusty1s/pytorch_scatter#152]
Heya,

`scatter_sum` fails in cases where no `out` tensor is specified:
```
$ python
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import torch_scatter
>>> src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
>>> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
>>> torch_scatter.scatter_sum(src, index)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mabrocks/venvs/py3-torch1.5/lib/python3.6/site-packages/torch_scatter/scatter.py", line 21, in scatter_sum
    size[dim] = int(index.max()) + 1
TypeError: 'torch.Size' object does not support item assignment
```

Solution: Change https://github.com/rusty1s/pytorch_scatter/blob/master/torch_scatter/scatter.py#L14 from `size = src.size()` to `size = list(src.size())`.

**Comment by rusty1s** [comment]
Interesting, thanks for reporting.

It does not fail for me (PyTorch >= 1.5.0), but the fix is straightforward to add. Fixed in master :)

**Comment by mmjb** [comment]
Thanks for the quick fix. Not sure why this seems to work for you - I'm not a torch expert, but it looks like it fails in torch 1.5.1:
```
>>> torch.__version__
'1.5.1'
>>> foo = torch.Size((1,2,3))
>>> foo[0] = 7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'torch.Size' object does not support item assignment
```

I thought that `torch.Size` is supposed a tuple (see e.g. https://pytorch.org/docs/stable/tensors.html#torch.Tensor.size) so assignment shouldn't work...

**Comment by rusty1s** [comment]
Yes, it shouldn't work without the explicit `list` conversion, so the suggested fix is appropriate. It's a bit weird that it works for me. It looks like it is caused by the `@torch.jit.script` command. It also fails for me when I delete it.

**Comment by ozgurlev** [comment]
Thanks for the fix as I just hit the exact same issue! I wonder if/how I can get a pyd file with this fix? I tried to build my private scatter pyd with the fixed script version but couldn't get to a working version. Any pointer / help would be appreciated. I am using torch_scatter-2.0.4 with torch-1.4.0.

**Comment by rusty1s** [comment]
You can upgrade to `torch-scatter==2.0.5` or fix this bug manually by editing `.../site-packages/torch-scatter/torch_scatter/scatter.py`.

**Comment by ozgurlev** [comment]
Thanks Rusty, I did the edit in the python file but I run this package in a non-python environment so I was trying to build a pyd file for scatter with this change, that is the part I am failing right now. May you have any tips on that?

**Comment by rusty1s** [comment]
My guess is that you can generate them by running `python setup.py install` inside the `torch-scatter` folder.

**Comment by ozgurlev** [comment]
Somehow I couldn't manage the setup work properly in my local, but on the other hand I was able to upgrade to the latest version by also upgrading PyTorch Geometric and Torch after fixing a prior issue with PyInstaller. I am all good now, thank you!
