### ISSUE TITLE
Error after upgrading to pytorch 1.6  /torch_scatter/_scatter.so: undefined symbol: _ZN5torch8autograd4Node20get_next_sequence_nrEv

### ISSUE THREAD

**Issue by JonathanSchmidt1** [rusty1s/pytorch_scatter#153]
Hello,

I upgraded pytorch, torch geometric, sparse, scatter and cluster to the 1.6 versions (cu101) which seems to have broken something:

Traceback (most recent call last):
  File "run_lightning_cgcnn.py", line 14, in <module>
    from lightning_module_cgcnn import LightningTemplateModel
  File "/home/test_user/QMC/torch_geometric/lightning_module_cgcnn.py", line 4, in <module>
    from original_message import collate_batch
  File "/home/test_user/QMC/torch_geometric/original_message.py", line 5, in <module>
    from torch_scatter import scatter_max, scatter_add, \
  File "/home/test_user/.conda/envs/torch14/lib/python3.7/site-packages/torch_scatter/__init__.py", line 12, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/test_user/.conda/envs/torch14/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/home/test_user/.conda/envs/torch14/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/test_user/.conda/envs/torch14/lib/python3.7/site-packages/torch_scatter/_scatter.so: undefined symbol: _ZN5torch8autograd4Node20get_next_sequence_nrEv

Any ideas?

**Comment by rusty1s** [comment]
That looks like you may have multiple torch-scatter versions installed, and Python is loading the wrong one (not the one you wish to load for PyTorch 1.6.0). It's best to run
```
pip uninstall torch-scatter
```
repeatedly before upgrading.

**Comment by JonathanSchmidt1** [comment]
Thank you for the fast response,
 Now I tried both uninstalling everything as well as installing it in a fresh environment. Unfortunately, the error stays the same:
OSError: /home/test_user/.conda/envs/torch16/lib/python3.8/site-packages/torch_scatter/_scatter.so: undefined symbol: _ZN5torch8autograd4Node20get_next_sequence_nrEv

**Comment by rusty1s** [comment]
Can you show me the commands with which you installed PyG?

**Comment by JonathanSchmidt1** [comment]
pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.6.0.html
Collecting torch-scatter==latest+cu101
  Downloading https://pytorch-geometric.com/whl/torch-1.6.0/torch_scatter-latest%2Bcu101-cp38-cp38-linux_x86_64.whl (11.5 MB)
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.5

(torch16) test_user@dgx2:~$ pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.6.0.html
Collecting torch-sparse==latest+cu101
  Downloading https://pytorch-geometric.com/whl/torch-1.6.0/torch_sparse-latest%2Bcu101-cp38-cp38-linux_x86_64.whl (22.9 MB)
Requirement already satisfied: scipy in ./.conda/envs/torch16/lib/python3.8/site-packages (from torch-sparse==latest+cu101) (1.5.2)
Requirement already satisfied: numpy>=1.14.5 in ./.conda/envs/torch16/lib/python3.8/site-packages (from scipy->torch-sparse==latest+cu101) (1.19.1)
Installing collected packages: torch-sparse
Successfully installed torch-sparse-0.6.7


(torch16) test_user@dgx2:~$ pip install torch-cluster==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.6.0.html
Collecting torch-cluster==latest+cu101
  Downloading https://pytorch-geometric.com/whl/torch-1.6.0/torch_cluster-latest%2Bcu101-cp38-cp38-linux_x86_64.whl (20.2 MB)
Installing collected packages: torch-cluster
Successfully installed torch-cluster-1.5.7


(torch16) test_user@dgx2:~$ pip install torch-spline-conv==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html
Looking in links: https://pytorch-geometric.com/whl/torch-1.6.0.html
Collecting torch-spline-conv==latest+cu101
  Downloading https://pytorch-geometric.com/whl/torch-1.6.0/torch_spline_conv-latest%2Bcu101-cp38-cp38-linux_x86_64.whl (6.1 MB)
Installing collected packages: torch-spline-conv
Successfully installed torch-spline-conv-1.2.0

(torch16) test_user@dgx2:~$ pip install torch-geometric

**Comment by JonathanSchmidt1** [comment]
Downgrading to 1.5 for everything worked but I can still not get it run with 1.6.

**Comment by tanjary21** [comment]
Okay, I've been struggling with this for a while now and can't seem to figure this out despite all the people you've answered. Please help.

I'm trying to run this on COLAB. I ran the following commands to make sure all the versions were coherent:

!pip install torch==1.7.0+cu101 torchvision==0.8.0+cu101 torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html
!pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
!pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
!pip install pytorch-lightning
!pip install torch-geometric


But when I finally run my script I get the following error:

Traceback (most recent call last):
  File "scripts/train.py", line 4, in <module>
    from mot_neural_solver.utils.evaluation import MOTMetricsLogger
  File "/content/mot_neural_solver/src/mot_neural_solver/utils/evaluation.py", line 15, in <module>
    from torch_scatter import scatter_add
  File "/usr/local/lib/python3.7/dist-packages/torch_scatter/__init__.py", line 14, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/usr/local/lib/python3.7/dist-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.7/dist-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtESt10shared_ptrIS0_EPSo

**Comment by rusty1s** [comment]
Any reason you do not simply use PyTorch 1.8.0, following the installation from [here](https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing)?

**Comment by tanjary21** [comment]
okay, this worked. Thank you! I ran into another issue though, perhaps you can advise.

File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 42, in overwrite_by_env_vars
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'val_percent_check'

I checked the documentation for pytorch_lightning, and indeed it does not expect an argument 'val_percent_check' upon initialization. But this project belongs to someone else and I guess its important,. Any advice?

**Comment by tanjary21** [comment]
pytorch-lightning/trainer, this is what is being initialized with 'val_percent_check' as one of the arguments

**Comment by rusty1s** [comment]
@tchaton, any advice?

**Comment by tanjary21** [comment]
I think I figured it out for anyone else that may run into the issue. Apparently the argument handles in the documentation have changed, meaning, older versions asked for something like val_percent_check, but now, that very argument goes by the name 'val_check_inerval'. This is true for several other arguments, here is a link to some that have been found. The rest will require careful inspection and comparison of the documentation for new vs old versions

https://github.com/PyTorchLightning/pytorch-lightning/issues/4546#issuecomment-723414954

**Comment by fghg123** [comment]
@tanjary21
In colab 
run !pip list 
see torch versions

**Comment by fghg123** [comment]
来信已收到。                  邓林权

**Comment by fghg123** [comment]
来信已收到。                  邓林权
