### ISSUE TITLE
A warning should be added if edge_index is not sorted and coalesced=False

### ISSUE THREAD

**Issue by JiangTanZJU** [rusty1s/pytorch_scatter#155]
If edge_index is not sorted and coalesced=False, the code works fine. But in fact, the result is wrong.
![image](https://user-images.githubusercontent.com/39088437/89896140-84de4200-dc0f-11ea-9283-d9a60fdf9681.png)

**Comment by JiangTanZJU** [comment]
By the way, I want to ask whether edge_index can be viewed as sorted as long as the first row is sorted, even if the second row is not sorted?

**Comment by rusty1s** [comment]
Yes, this is definitely an issue, but it should no longer exist when using the `SparseTensor` format in `torch-sparse` (not documented yet). You can view `edge_index` as sorted in case the row vector is sorted.
