### ISSUE TITLE
Segmentation fault in test_backward.py

### ISSUE THREAD

**Issue by stebo85** [rusty1s/pytorch_scatter#16]
Dear rusty1s,

I am trying to use pytorch_scatter, but the test runs into a segmentation fault:
python setup.py test
running pytest
Searching for pytest-cov
Best match: pytest-cov 2.6.0
Processing pytest_cov-2.6.0-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/pytest_cov-2.6.0-py3.6.egg
Searching for pytest
Best match: pytest 4.0.1
Processing pytest-4.0.1-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/pytest-4.0.1-py3.6.egg
Searching for coverage>=4.4
Best match: coverage 5.0a3
Processing coverage-5.0a3-py3.6-linux-x86_64.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/coverage-5.0a3-py3.6-linux-x86_64.egg
Searching for py>=1.5.0
Best match: py 1.7.0
Processing py-1.7.0-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/py-1.7.0-py3.6.egg
Searching for pluggy>=0.7
Best match: pluggy 0.8.0
Processing pluggy-0.8.0-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/pluggy-0.8.0-py3.6.egg
Searching for more-itertools>=4.0.0
Best match: more-itertools 4.3.0
Processing more_itertools-4.3.0-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/more_itertools-4.3.0-py3.6.egg
Searching for attrs>=17.4.0
Best match: attrs 18.2.0
Processing attrs-18.2.0-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/attrs-18.2.0-py3.6.egg
Searching for atomicwrites>=1.0
Best match: atomicwrites 1.2.1
Processing atomicwrites-1.2.1-py3.6.egg

Using /afm01/scratch/cai/uqsbollm/pytorch_scatter/.eggs/atomicwrites-1.2.1-py3.6.egg
running egg_info
writing torch_scatter.egg-info/PKG-INFO
writing dependency_links to torch_scatter.egg-info/dependency_links.txt
writing top-level names to torch_scatter.egg-info/top_level.txt
reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.6/scatter_cpu.cpython-36m-x86_64-linux-gnu.so ->
copying build/lib.linux-x86_64-3.6/scatter_cuda.cpython-36m-x86_64-linux-gnu.so ->
========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /afm01/scratch/cai/uqsbollm/pytorch_scatter, inifile: setup.cfg
plugins: cov-2.6.0
collecting ... [2, 0, 1, 1, 0]
collected 186 items

test/test_backward.py ....Segmentation fault

I have gnu/5.4.0   and cuda/9.1.85.3 loaded. The same problem occurs with cuda/9.1.85.1. When I try with older or newer cuda versions it fails with:
================================================================================================================= ERRORS =================================================================================================================
_________________________________________________________________________________________________ ERROR collecting test/test_backward.py _________________________________________________________________________________________________
ImportError while importing test module '/afm01/scratch/cai/uqsbollm/pytorch_scatter/test/test_backward.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_backward.py:6: in <module>
    import torch_scatter
torch_scatter/__init__.py:3: in <module>
    from .mul import scatter_mul
torch_scatter/mul.py:3: in <module>
    from torch_scatter.utils.ext import get_func
torch_scatter/utils/ext.py:5: in <module>
    import scatter_cuda
E   ImportError: libcudart.so.9.1: cannot open shared object file: No such file or directory
_________________________________________________________________________________________________ ERROR collecting test/test_forward.py __________________________________________________________________________________________________
ImportError while importing test module '/afm01/scratch/cai/uqsbollm/pytorch_scatter/test/test_forward.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_forward.py:5: in <module>
    import torch_scatter
torch_scatter/__init__.py:3: in <module>
    from .mul import scatter_mul
torch_scatter/mul.py:3: in <module>
    from torch_scatter.utils.ext import get_func
torch_scatter/utils/ext.py:5: in <module>
    import scatter_cuda
E   ImportError: libcudart.so.9.1: cannot open shared object file: No such file or directory

My system is 3.10.0-693.17.1.el7.x86_64 and the GPUs are Tesla V100s running with driver version 410.48.

Do you have any idea what I am doing wrong or what else I could try?

**Comment by stebo85** [comment]
Dear rusty1s,

I got it to work now with cuda/9.2.148.1 and gnu/5.4.0 after removing the build folder and recompiling. 

Thank you for developing such a great toolkit!

Cheers
Steffen

**Comment by rusty1s** [comment]
Glad that it is now working. Thanks for letting me know.
