### ISSUE TITLE
Is there any way to build pytorch_scatter with CUDA9.0?

### ISSUE THREAD

**Issue by EthanZhangYi** [rusty1s/pytorch_scatter#161]
I want to build pytorch_scatter with CUDA9.0 (restricted by the environment of the server). Is it possible? Can any one give some help?

**Comment by rusty1s** [comment]
That should be possible by building from source. Feel free to try it out and report back any issues you might encounter :)

**Comment by EthanZhangYi** [comment]
@rusty1s ,I tried to build from source through `python setup.py install`, but the cuda support is not built. As shown below, `libcudart.so` `libc10_cuda.so` and `libtorch_cuda.so` are not used by `_scatter.so`
![Selection_001](https://user-images.githubusercontent.com/13479831/92453823-4fb71680-f1f2-11ea-9ff5-d6cbe5d2161c.png)

**Comment by rusty1s** [comment]
Which PyTorch version are you using?

**Comment by EthanZhangYi** [comment]
@rusty1s 
I am using `pytorch-1.5.1`.
When I build with `FORCE_CUDA=1 python setup.py build`, the cuda support is tried to be built, but errors occur.
![image](https://user-images.githubusercontent.com/13479831/92456291-4e3b1d80-f1f5-11ea-85c9-36dd1e5b8bea.png)

**Comment by rusty1s** [comment]
Can you take a look why `libtorch` is missing in your PyTorch installation? It should be included in `pythonxxx/site-packages/torch/lib`.

**Comment by EthanZhangYi** [comment]
@rusty1s 
Pytorch is well installed. Very strange.
![image](https://user-images.githubusercontent.com/13479831/92571670-fb756a80-f2b5-11ea-8ea7-b4bf86c58e83.png)

**Comment by rusty1s** [comment]
That's really strange, but you may can get around it by manually setting the path to those binary files in the `CUDAExtension` object in `setup.py`.

**Comment by EthanZhangYi** [comment]
@rusty1s 
I tried to build with cuda-9.0, but lots of errors occur in the step below.
```
/mnt/lustre/share/cuda-9.0/bin/nvcc -DWITH_CUDA -I/mnt/lustre/zhangyi/pytorch_scatter/csrc -I/mnt/lustre/zhangyi/env_pytorch_151/lib/python3.7/site-packages/torch/include -I/mnt/lustre/zhangyi/env_pytorch_151/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/mnt/lustre/zhangyi/env_pytorch_151/lib/python3.7/site-packages/torch/include/TH -I/mnt/lustre/zhangyi/env_pytorch_151/lib/python3.7/site-packages/torch/include/THC -I/mnt/lustre/share/cuda-9.0/include -I/mnt/lustre/zhangyi/env_pytorch_151/include/python3.7m -c /mnt/lustre/zhangyi/pytorch_scatter/csrc/cuda/scatter_cuda.cu -o build/temp.linux-x86_64-3.7/mnt/lustre/zhangyi/pytorch_scatter/csrc/cuda/scatter_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -arch=sm_35 --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_scatter -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
```
![image](https://user-images.githubusercontent.com/13479831/92856158-b6704600-f425-11ea-9433-fe75b852c933.png)
The log is show bellow. Can you give some help?
[setup.log](https://github.com/rusty1s/pytorch_scatter/files/5205798/setup.log)

**Comment by rusty1s** [comment]
Maybe you can get around this problem by using the cudatoolkit from conda, see [here](https://github.com/rusty1s/pytorch_geometric/issues/1593#issuecomment-690996885).

**Comment by EthanZhangYi** [comment]
@rusty1s 
Thanks for your advice.
I tried to build from source with CUDA9.0. `torch_scatter 2.0.5` raised the error above. But `torch_scatter 1.4.0` worked.
I will try the cudatoolkit later.
