### ISSUE TITLE
Difference between scatter with "add" as aggregation and simple sum

### ISSUE THREAD

**Issue by navid-mahmoudian** [rusty1s/pytorch_scatter#163]
Hello,
I noticed that sometimes there is a difference of order 0.0002 between scatter function and simple summing of values. I think the difference between equivalent operations in float precision should be of order e-06, not e-04. Am I making a mistake? You can simply check the following script to see the difference:

```
import torch
from torch_scatter import scatter

edge_matrix = torch.tensor([[2, 3, 1], [0, 2, 3], [3, 1, 0], [2, 1, 0]], dtype=torch.long)
edge_index = torch.cat((torch.arange(edge_matrix.size(0), dtype=torch.long).repeat_interleave(edge_matrix.size(1)).view(1, -1), edge_matrix.view(1, -1).clone()), dim=0)
print("edge_index=\n", edge_index)
B = 1  # batch size
in_channels = 2
num_nodes = int(edge_index.max()) + 1
# x = torch.FloatTensor(B, num_nodes, in_channels).uniform_(0., 1000.)
x = torch.FloatTensor([[[ 37.658276, 858.623657],
                        [621.997437, 647.715332],
                        [119.122803, 979.090515],
                        [301.954987, 874.309265]]])

node_dim = 1
out_1 = scatter(x.index_select(node_dim, edge_index[0]), edge_index[1], dim=node_dim, reduce="sum")

out_2 = torch.zeros(x.size(), dtype=x.dtype)
for k in range(edge_matrix.size(1)):
    out_2 += x.index_select(node_dim, edge_matrix[:, k])

torch.set_printoptions(precision=6)
print("x=", x)
print("out_1=", out_1)
print("out_2=", out_2)

diff = out_1 - out_2
print("diff=", diff)
test = diff.abs() > 1e-5
print("diff.abs().max()=", diff.abs().max())
assert not (test.any().item()), "The order of difference is greater than e-5"
```

In this example, the graph has a regular structure with 4 nodes in which each node is connected to the other 3 nodes. The `edge_matrix` is a matrix in which row "i" shows the indices of neighboring nodes of node "i". I used this simple regular structure to be able to use sum in for loop. The `edge_index` can be constructed from `edge_matrix` as shown in the code above. As you can see there is a difference of  `0.000244` between some elements. Is it normal to have this difference for two equivalent operations for float values? I am running the code on cpu (no CUDA is used). For your convenience, you can see the output of the above code on my computer:

> edge_index=
>  tensor([[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3],
>         [2, 3, 1, 0, 2, 3, 3, 1, 0, 2, 1, 0]])
> x= tensor([[[ 37.658276, 858.623657],
>          [621.997437, 647.715332],
>          [119.122803, 979.090515],
>          [301.954987, 874.309265]]])
> out_1= tensor([[[1043.075195, 2501.115234],
>          [ 458.736084, 2712.023438],
>          [ 961.610718, 2380.648193],
>          [ 778.778503, 2485.429443]]])
> out_2= tensor([[[1043.075195, 2501.115234],
>          [ 458.736084, 2712.023438],
>          [ 961.610657, 2380.648438],
>          [ 778.778503, 2485.429688]]])
> diff= tensor([[[ 0.000000e+00,  0.000000e+00],
>          [ 0.000000e+00,  0.000000e+00],
>          [ 6.103516e-05, -2.441406e-04],
>          [ 0.000000e+00, -2.441406e-04]]])
> diff.abs().max()= tensor(0.000244)
> Traceback (most recent call last):
>   File "/home/nmahmoud/myPostDoc/sphericallearning/Codes/misc/test_graph_conv_aggregation.py", line 32, in <module>
>     assert not (test.any().item()), "The order of difference is greater than e-5"
> AssertionError: The order of difference is greater than e-5

**Comment by rusty1s** [comment]
The difference in results can be explained via numerical issues since the order of aggregation is different. Changing `edge_matrix` to
```
edge_matrix = torch.tensor([[1, 2, 3], [0, 2, 3], [0, 1, 3], [0, 1, 2]])
```
resolves this. There's not much I can do here, but its nonetheless important to be aware of this.

**Comment by navid-mahmoudian** [comment]
Thank you very much for the explanation.
