### ISSUE TITLE
libtorch_cpu.so: cannot open shared object file

### ISSUE THREAD

**Issue by shirinmous** [rusty1s/pytorch_scatter#173]
Hi,
I installed
torch==1.3.0
torch-scatter==1.3.2
torch-cluster==1.4.5
torch-sparse==0.4.3
torch-spline-conv==1.1.1
torch-geometric==1.3.2
torchvision==0.4.1
using pip in a virtual env on ubuntu 20.04 and I have cuda 10.1.
when I import one of these packages (scatter, cluster, sparse,geometric)
I got this error: ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory.
With newer versions, I didn't have any error but I need these versions.
Thanks

**Comment by rusty1s** [comment]
That's interesting. It doesn't look like an issue with the external packages but rather a PyTorch issue. Can you check whether `libtorch_cpu.so` exists, e.g., in `.../lib/python3.7/site-packages/torch/lib/libtorch_cpu.so`?

**Comment by shirinmous** [comment]
No, libtorch_cpu.so doesn't exist.
And I try with torch 1.4 and get the same error.
For torch 1.5 I got this error :
RuntimeError: Expected PyTorch version 1.4 but found version 1.5.

**Comment by shirinmous** [comment]
There is just the runtime library libtorch.so in pytorch 1.3 and 1.4.
After 1.5 this runtime library has separated into the runtime libraries libtorch_cpu.so and libtorch_cuda.so.  [#29235](https://github.com/pytorch/pytorch/issues/29235)
So if the mentioned versions of torch_geometric, torch_scatter, ... are compatible with pytorch 1.3, why do they search for libtorch_cpu.so?

**Comment by rusty1s** [comment]
I'm not exactly sure. My guess is that you have multiple versions `torch-*` versions installed, and one of them is of a later version.

**Comment by shirinmous** [comment]
Yes, I have multiple versions of torch installed but in separated envs.

**Comment by rusty1s** [comment]
Mh, that might be the reason (although not 100% sure). Can you do me a favor and try to re-install in a completely *fresh* conda installation?

**Comment by shirinmous** [comment]
I couldn't install those versions with mini conda because of PackagesNotFoundError.

**Comment by rusty1s** [comment]
What do you mean? Which command produces a `PackageNotFound` error?

**Comment by ysl208** [comment]
any updates on this? I am getting the same error.

**Comment by rusty1s** [comment]
In case of `libtorch_cpu.so` not found, you can try to add the folder holding PyTorch shared libraries to `$LD_LIRBARY_PATH`:
```
export LD_LIBRARY_PATH=.../site-packages/torch/lib:$LD_LIBRARY_PATH
```

**Comment by ardyli** [comment]
> 那很有意思。它看起来不像是外部包的问题，​​而是像 PyTorch 问题。你能检查是否`libtorch_cpu.so`存在，例如，在`.../lib/python3.7/site-packages/torch/lib/libtorch_cpu.so`？

libtorch_cpu.so File exists, or prompted this problem.

**Comment by johnhuichen** [comment]
> In case of `libtorch_cpu.so` not found, you can try to add the folder holding PyTorch shared libraries to `$LD_LIRBARY_PATH`:
> 
> ```
> export LD_LIBRARY_PATH=.../site-packages/torch/lib:$LD_LIBRARY_PATH
> ```

This fixes my problem
