### ISSUE TITLE
Error in computation for segment_coo

### ISSUE THREAD

**Issue by apoorv2904** [rusty1s/pytorch_scatter#176]
Hi,

Thank you for the extensions.

I was trying out the segment_coo. However, I notice that the following simple usage gives a very high error on GPU. The CPU version works fine.  I have attached the code block for reproducibility.

I installed using:
pip install torch-scatter==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html

Test Environment:
Pytorch version: 1.6
Cuda: 10.1

Thanks,
Apoorv
```
import torch
from torch_scatter import segment_coo

N, H, L, E = 2, 4, 1000, 64
C = 200
S = int(L / C)

x = torch.randn(N, H, L, E).cuda()
g = torch.arange(C).repeat_interleave(S, dim=0)
g = g.view(1, 1, L).repeat(N, H, 1).long().cuda()

out = segment_coo(x, g.long(), reduce='mean')
mean_x = x.view(N, H, C, -1, E).mean(-2)
err = out - mean_x
max_rel_err = (torch.abs(err) / torch.abs(mean_x)).max().item()
print(max_rel_err)
assert( max_rel_err < 1e-3)
```

**Comment by rusty1s** [comment]
That's indeed a bug. Thanks so much for spotting. It does seem to happen only on multi-dimensional indices (potentially a indexing issue). I will look into it.

**Comment by rusty1s** [comment]
This is now fixed in master. I will craft a new release soon. Thank you so much for reporting and sorry for the inconveniences!

**Comment by apoorv2904** [comment]
Thank you very much for the quick fix.
