### ISSUE TITLE
pip 20.3 resolver incompatible with how .whls are built and shared

### ISSUE THREAD

**Issue by lilleswing** [rusty1s/pytorch_scatter#179]
Hi,

I'm using the torch 1.6.0 whls listed here
`https://pytorch-geometric.com/whl/torch-1.6.0.html`

With the introduction of pip 20.3 strict resolver we are no longer able to install from this location.  e.g.
`pip install torch-sparse==latest+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html`
As latest is not an official supported version number.

Even when attempting to install a specific version runs into issues
```
pip install torch-sparse==0.6.8+cu101 -f https://pytorch-geometric.com/whl/torch-1.6.0.html

Looking in links: https://pytorch-geometric.com/whl/torch-1.6.0.html
ERROR: Requested torch-sparse==0.6.8+cu101 from https://pytorch-geometric.com/whl/torch-1.6.0/torch_sparse-0.6.8%2Bcu101-cp36-cp36m-linux_x86_64.whl has different version in metadata: '0.6.8'
```

Here is the merge into pip that caused the issue
https://github.com/pypa/pip/pull/9177

I'm not sure *how* to properly solve this issue.  You want the metadata to point to a version regardless of cuda/cpu support, but I think the best way would b e to set the version metadata in the .whl to exactly the url you upload the .whl to.

**Comment by rusty1s** [comment]
Thanks for reporting. I will look into it.

**Comment by rusty1s** [comment]
This is now resolved. You can now install the packages via:
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
```
For example, for installing for PyTorch 1.7.0 with CUDA 11.0, type:
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-torch-1.7.0+cu110.html
```
All "old" links are still intact. You can have a look at all possible combinations [here](https://pytorch-geometric.com/whl/index.html).

**Comment by amonszpart** [comment]
> This is now resolved. You can now install the packages via:
> 
> ```
> pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-${TORCH}+${CUDA}.html
> ```
> 
> For example, for installing for PyTorch 1.7.0 with CUDA 11.0, type:
> 
> ```
> pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-torch-1.7.0+cu110.html
> ```
> 
> All "old" links are still intact. You can have a look at all possible combinations [here](https://pytorch-geometric.com/whl/index.html).

typo: `https://pytorch-geometric.com/whl/torch-torch-1.7.0+cu110.html` -> `https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html`
It would be nice to include a requirements.txt version in the docs as well. Thanks!

**Comment by rusty1s** [comment]
I don't think that this is possible, since installation depends on both local PyTorch and CUDA version :(
