### ISSUE TITLE
custom_opsets for ONNX export, possible?

### ISSUE THREAD

**Issue by stratomaster31** [rusty1s/pytorch_scatter#181]
I'd like to export a model which uses torch_scatter to ONNX, but I get:

`No importer registered for op: ScatterND`

I'd like to know if there is a _custom_opset_ name, so I can use something similar to:

`torch.onnx.export(custo_opset={"torch_scatter":1})
`

Has anyone come around with any solution?

thx

**Comment by ChangCao** [comment]
Hello, have you successfully exported a model which uses torch_scatter to ONNX? and how did you do?

**Comment by rusty1s** [comment]
I don't think that's possible yet. I need to look into how one can achieve that :)

**Comment by EmreOzkose** [comment]
I have the same issue. Did you solve that?

**Comment by rusty1s** [comment]
Moving this discussion to: https://github.com/pyg-team/pytorch_geometric/discussions/3514
