### ISSUE TITLE
about SparseTensor

### ISSUE THREAD

**Issue by ZhouAo-ZA** [rusty1s/pytorch_scatter#185]
After replacing the SparseTensor class, the GNN aggregation process does not need to use the scatter function at all？

**Comment by rusty1s** [comment]
That's correct. It will either use sparse matrix multiplication or the newly introduced `segment` operations in `torch-scatter` for aggregation.

**Comment by ZhouAo-ZA** [comment]
Thank you for your reply, After that, are there other uses for functions such as scatter_add? Will they be deleted in the next version?

**Comment by rusty1s** [comment]
No, they will never be deleted.

**Comment by ZhouAo-ZA** [comment]
I experimented with graphsage and entered adj, and found that spmm is indeed much faster than scatter. Is there any special GNN model that needs to enter edge-index and call functions such as scatter_add？

**Comment by rusty1s** [comment]
Currently, all operators in `nn.conv` support `adj_t` as input. However, there are some models that still only support `edge_index`, such as pooling approaches.

**Comment by ZhouAo-ZA** [comment]
Thank you for your answer. Are there any relevant examples or model implementations in your git repository?

**Comment by rusty1s** [comment]
What do you mean exactly? You can find some examples of `SparseTensor`[here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/gcn2_ppi.py) and [here](https://github.com/rusty1s/pytorch_geometric/blob/master/examples/multi_gpu/distributed_batching.py).

**Comment by ZhouAo-ZA** [comment]
I'm very sorry, my statement is wrong, 
I mean, I want to know which models still only support edge_index,；and whether you have any relevant implementation examples. I actually want to find examples, where the scatter_add function is needed in the model，
thank you！

**Comment by rusty1s** [comment]
Everyone else, e.g. `examples/gcn.py`.
