### ISSUE TITLE
There is a OSError after install the torch_scatter

### ISSUE THREAD

**Issue by shxzhao** [rusty1s/pytorch_scatter#186]
After install torch_scatter, there is a problem:
OSError: /home/zhao/anaconda3/envs/pytorch2/lib/python3.6/site-packages/torch_scatter/_version.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

How to solve it

**Comment by rusty1s** [comment]
This usually indicates a version mismatch between PyTorch and CUDA and torch-scatter. Can you give more information to resolve this?

**Comment by shxzhao** [comment]
Thanks for you reply! My PyTorch is 1.4.0, CudaToolKit is 10.1,  torch_scatter is torch_scatter-2.0.3-cp36-cp36m-linux_x86_64.whl. The torch_scatter is download in https://pytorch-geometric.com/whl/torch-1.4.0+cu101.html.

**Comment by rusty1s** [comment]
Mh, that's weird. Can you uninstall all `torch-scatter` versions (repeatedly call `pip uninstall torch-scatter`) and run `pip install --no-index torch-scatter -f ...`.

**Comment by janosh** [comment]
Had the same problem as @shxzhao. This fixed it for me:

```sh
pip uninstall torch-scatter && pip install --no-index torch-scatter -f https://pytorch-geometric.com/whl/torch-1.7.0+cpu.html
```

Thanks @rusty1s.

**Comment by shxzhao** [comment]
Thanks! @rusty1s @janosh  But it does not work. I'll try something else.

**Comment by shxzhao** [comment]
Thanks! @rusty1s @janosh When I change the pytorch to 1.7, I succeed!

**Comment by ninjakx** [comment]
@shxzhao can you list all your dependency with version? Because I am getting the same error. Downgrading the torch from 1.8 to 1.7 and 1.6 didn't help me

**Comment by shxzhao** [comment]
@ninjakx My cuda is 10.2, pytorch is 1.7.2 torch_scatter is 2..0.5.  I hope it's helpful to you.

**Comment by zhouyupeng973** [comment]
my torch is 2.1.0 and my cuda is 12.0,which torch_scatter edition should I downlload?

**Comment by rusty1s** [comment]
You can install from https://data.pyg.org/whl/torch-2.1.0+cu121.html
