### ISSUE TITLE
CUDA 11.2 Pytorch version mismatch

### ISSUE THREAD

**Issue by kmani314** [rusty1s/pytorch_scatter#187]
Hi, I followed the instructions in the README to install torch-scatter with CUDA v11.0 (cu110), which worked, but whenever I try to run any code I get this error:
```
RuntimeError: Detected that PyTorch and torch_scatter were compiled with different CUDA versions. PyTorch has CUDA version 11.0 and torch_scatter has CUDA version 11.2. Please reinstall the torch_scatter that matches your PyTorch install.
```
(Pytorch 1.7.1+cu110)
The pytorch version appears to be consistent with what I installed, but the `cu110` version of this package appears to use CUDA v11.2 instead of 11.0. Any tips on how to get this to work?

**Comment by rusty1s** [comment]
It uses cu112 since that is your locally installed CUDA version. With CUDA 11, this is not much of a problem, and we even relaxed the version requirement in master already, see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/torch_scatter/__init__.py#L53). I suggest to do the same on your side and see if that fixes your issues.

**Comment by kmani314** [comment]
Thank you, upgrading to the latest commit fixed it.

**Comment by kmani314** [comment]
Sorry to ask again, but upgrading to the latest commit only fixed that error. Whenever I import the library, CUDA throws `RuntimeError: CUDA error: unrecognized error code` whenever I try to do anything on the GPU. Is this because of some incompatibilities bewteen CUDA versions 11 and 11.2, and if so should I downgrade? Thanks again.

**Comment by rusty1s** [comment]
How about adding the conda CUDA toolkit to `LD_LIBRARY_PATH`, e.g., `export LD_LIBRARY_PATH=your_conda_path/lib:$LD_LIBRARY_PATH`?

**Comment by kmani314** [comment]
I'm not sure what the equivalent would be with pip, but running `export LD_LIBRARY_PATH=path_to_venv/lib` or `lib64` doesn't seem to make any difference. From what I can tell from running `torch.ops.torch_scatter.cuda_version()` it's finding CUDA correctly, and `CUDA_HOME` is set in pytorch correctly.

**Comment by adity-om** [comment]
I am facing the same issue. Updating the path doesn't change the issue

**Comment by rusty1s** [comment]
Any infos about your PyTorch and CUDA version and how you tried to install `torch-scatter`?
