### ISSUE TITLE
Re-add the support for other operators (scatter_mul)

### ISSUE THREAD

**Issue by jaromiru** [rusty1s/pytorch_scatter#188]
I see that 1.4.0 version included operators like scatter_mul. These are actually very useful. Consider including them back.

**Comment by ZhouAo-ZA** [comment]
Under what circumstances will scatter_mul be used？

**Comment by jaromiru** [comment]
My usecase is for multiple-node (in a graph) selection policy, where each node is selected with some probability. The total probability of the particular combination is then the product of nodes' probabilities. Easy to see that for a batch of graphs, the scatter_mul is useful. 

I now see that the div operation is nonsensical, as it is not commutative.

**Comment by rusty1s** [comment]
I just added `scatter_mul` back into the master branch!

**Comment by jaromiru** [comment]
Amazing!
