### ISSUE TITLE
scatter_mul backward error with 0 input.

### ISSUE THREAD

**Issue by jianhao2016** [rusty1s/pytorch_scatter#189]
Hi,

Thanks a lot for adding scatter_mul back to the main branch! We really need this feature. However, I have been encountering the 'grad = nan' issue since the last versions with scatter_mul (1.4.0). This forward of scatter_mul is fine, but when I tried backward. Here is the test code I tried:

```python
import torch
from torch_scatter import scatter

edge_index = [[0, 0, 1, 1, 2, 2],
              [1, 2, 0, 2, 0, 1]]

edge_index = torch.tensor(edge_index)

# no backward error
# x = torch.DoubleTensor([1e-20, 1, 2]).view(-1, 1)
# Backward error with scatter_mul
x = torch.DoubleTensor([0, 1, 2]).view(-1, 1)


with torch.autograd.detect_anomaly():
    weight = torch.nn.Parameter(torch.DoubleTensor([[1, 2]]))
    x = torch.matmul(x, weight)
    src = x[edge_index[0], :]
    
    index = torch.LongTensor([1, 2, 0, 2, 0, 1])
    y = scatter(src, index, dim = 0, reduce = 'mul')
    out = y.sum()
    out.backward()
    print(weight.grad)
```

the gradient of weight when `x = [0, 1, 2]`, should be `[4, 8]` (same as `x = [1e-20, 1, 2]`'s output), however it has a error message:

```bash
RuntimeError: Function 'torch::autograd::CppNode<ScatterMul>' returned nan values in its 0th output.
``` 
---------------
Here is my environment: 

- python: 3.7.9
- GCC: 5.3.0
- NVCC: V10.0.130
- pytorch: 1.7.0 with cu102
- pytorch_scatter: 2.0.5, install from source by `python setup.py install`.

I tried `pip install pytorch_scatter=2.0.5`, but it didn't have the `scatter_mul` function yet. 

Thanks again for the great effort.

**Comment by rusty1s** [comment]
Should be fixed in master. The gradient computation needed an additional `nan` value check in case of division by zero.
