### ISSUE TITLE
Will you support pytorch 1.8.0(nightly) and fp16?

### ISSUE THREAD

**Issue by Veason-silverbullet** [rusty1s/pytorch_scatter#191]
Hi, @rusty1s . This project is great!!!
I want to ask whether you support pytorch 1.8.0(nightly) and fp16?

**Comment by rusty1s** [comment]
We will support PyTorch 1.8.0 once it is released. We try to stay up-to-date to the latest PyTorch release.

As for `fp16` support, we are still waiting for PyTorch to provide `fp16` capabilities to some of its functions (e.g., `clamp_`) before we can fully support it, see https://github.com/rusty1s/pytorch_scatter/pull/137.
