### ISSUE TITLE
There may be a little error in the document about segment_csr

### ISSUE THREAD

**Issue by Shiguang-Guo** [rusty1s/pytorch_scatter#192]
When reading document here(https://pytorch-scatter.readthedocs.io/en/latest/functions/segment_csr.html),I think there might be something wrong here.
First,the index of indptr may be $$x_0,\cdots,x_{m-2},y$$.
Second,it could be out $$_{i}=\sum_{j=\operatorname{indptr}[i]}^{\operatorname{indptr}[i+1]} \operatorname{src}_{j}$$but not i+i
My English is poor,please forgive me for grammar problems.

**Comment by rusty1s** [comment]
You're absolutely right. Fixed in master. Thanks!
