### ISSUE TITLE
Feature suggestion: Package source and build at load time

### ISSUE THREAD

**Issue by robin5540** [rusty1s/pytorch_scatter#193]
Pytorch has a pretty good build system for extensions via `torch.utils.cpp_extension.load`. I think building on the fly will reduce complexity in terms of which CUDA/torch/arch to build against.

I'd be happy to contribute a few PRs for this.

**Comment by robin5540** [comment]
To clarify, I don't mean replacing the existing build.

I think adding a source only wheel, that can be loaded on any* system will be quite powerful.

*: ofc, this is impossible. But hey, better portability is better portability.

**Comment by rusty1s** [comment]
Sounds interesting! I do not have much experience with `cpp_extension.load`. How does this help in better portability in comparison to just building from source?

**Comment by robin5540** [comment]
We can trigger `cpp_extension.load(cpp_source=[...])` when user imports `__init__.py`. This will build the extensions against whatever system they are using. If someone is still stuck on 1.6.0+cu100, (cough me cough), I don't have to manually clone and build. I can just install a source only wheel.

**Comment by rusty1s** [comment]
I definitely see the use-case of this, but `pip install torch-scatter` will already build against the current platform (in your case `torch-1.6.0+cu100`). Does that not work for you?

**Comment by robin5540** [comment]
Oh, assumed that cu100 isn't supported and the wheels are pre-built. My bad.

I don't see `torch-1.6.0+cu100` [here](https://pytorch-geometric.com/whl/)
but `pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cu100.html` works?!?!?!

Wait, what?

**Comment by rusty1s** [comment]
Yeah, it works by building from source, since there are no compatible wheels available.

**Comment by robin5540** [comment]
😂 Ignorant me. Didn't know this is the behavior.

(I spent 2 hours vendoring your library today 🤦 )

closing. Thank you for the super quick response.
