### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by Cwei1** [rusty1s/pytorch_scatter#196]
I am using the preuploaded binaries to install pytorch_scatter, however i am getting a metadata error, where setup.py has a version of 2.0.5, but the filename has the versioning of 2.0.5+[cudaversion]. How would I go about fixing this?

**Comment by rusty1s** [comment]
This should have been resolved already using our newly provided URLs:
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+${CUDA}.html
```
