### ISSUE TITLE
pytorch 1.7.1 and 1.8.0 binary wheels please

### ISSUE THREAD

**Issue by stas00** [rusty1s/pytorch_scatter#197]
`transformers` relies on `pytorch_scatter` and CIs take forever to build it from source, which is a big problem. 

Would it be possible to update https://pytorch-geometric.com/whl/ with pt-1.7.1 and pt-1.8.0 binary wheels please?

cuda version-wise it looks that pytorch is still [struggling with supporting cuda-11.2](https://github.com/pytorch/pytorch/issues/50232#issuecomment-777703998), so probably 110, 111 for now would be great!

Thank you very much!

**Comment by rusty1s** [comment]
For PyTorch 1.7.1, one can use the wheels for PyTorch 1.7.0. I'm currently building `torch-scatter` for PyTorch 1.8.0, which should be finished in a few hours.

**Comment by stas00** [comment]
> For PyTorch 1.7.1, one can use the wheels for PyTorch 1.7.0. 

Could you please add this note to: https://github.com/rusty1s/pytorch_scatter#pytorch-170

> I'm currently building `torch-scatter` for PyTorch 1.8.0, which should be finished in a few hours.

Fantastic! thank you very much, @rusty1s!

**Comment by rusty1s** [comment]
Added a note to the documentation. You can track compilation progress for PyTorch 1.8.0 [here](https://travis-ci.org/github/rusty1s/pytorch_scatter/builds/761617374).

**Comment by rusty1s** [comment]
Linux wheels are now available.

**Comment by stas00** [comment]
Amazing! Thank you for such a swift response, @rusty1s!
