### ISSUE TITLE
Build pytorch_scatter failed due to "class at::Tensor’ has no member named ‘isnan’"

### ISSUE THREAD

**Issue by xiaoyongzhu** [rusty1s/pytorch_scatter#198]
Hi,

Thanks for the great work here. I'm trying to build the repository and encountered this error: ` ‘class at::Tensor’ has no member named ‘isnan’`. Full stacktrace below.

Same error applies when I try to install from the pre-built binary from the README file (for multiple versions). Looks no one else has this error so I'm suspecting there might be something wrong with my end?

Thanks!

```
    /root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/profiler.h(100): warning: attribute "__visibility__" does not apply here

    /root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/include/torch/csrc/autograd/profiler.h(115): warning: attribute "__visibility__" does not apply here

    g++ -pthread -shared -B /root/miniconda3/envs/lightning/compiler_compat -L/root/miniconda3/envs/lightning/lib -Wl,-rpath=/root/miniconda3/envs/lightning/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/tmp/pip-req-build-5j87t8d6/csrc/segment_coo.o build/temp.linux-x86_64-3.7/tmp/pip-req-build-5j87t8d6/csrc/cpu/segment_coo_cpu.o build/temp.linux-x86_64-3.7/tmp/pip-req-build-5j87t8d6/csrc/cuda/segment_coo_cuda.o -L/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.7/torch_scatter/_segment_coo_cuda.so -s
    building 'torch_scatter._scatter_cpu' extension
    gcc -pthread -B /root/miniconda3/envs/lightning/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/tmp/pip-req-build-5j87t8d6/csrc -I/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/include -I/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/include/TH -I/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch/include/THC -I/root/miniconda3/envs/lightning/include/python3.7m -c /tmp/pip-req-build-5j87t8d6/csrc/scatter.cpp -o build/temp.linux-x86_64-3.7/tmp/pip-req-build-5j87t8d6/csrc/scatter.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /tmp/pip-req-build-5j87t8d6/csrc/scatter.cpp: In static member function ‘static torch::autograd::variable_list ScatterMul::backward(torch::autograd::AutogradContext*, torch::autograd::variable_list)’:
    /tmp/pip-req-build-5j87t8d6/csrc/scatter.cpp:104:34: error: ‘class at::Tensor’ has no member named ‘isnan’
         grad_in.masked_fill_(grad_in.isnan(), 0);
                                      ^~~~~
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/miniconda3/envs/lightning/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-5j87t8d6/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-5j87t8d6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hhnound9/install-record.txt --single-version-externally-managed --compile --install-headers /root/miniconda3/envs/lightning/include/python3.7m/torch-scatter Check the logs for full command output.

```

**Comment by xiaoyongzhu** [comment]
BTW - I'm installing it for Pytorch 1.5 and here's the command:
`pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.5.0+cu102.html -I`

or
`pip install git+https://github.com/rusty1s/pytorch_scatter.git`

**Comment by xiaoyongzhu** [comment]
> I see. It is indeed problematic to install for older PyTorch versions. Looking at https://pytorch-geometric.com/whl/torch-1.5.0+cu102.html, you may try to install via:
> 
> ```
> pip install --no-index torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-1.5.0+cu102.html
> ```

Thanks... I also tried that but it gives me another error complaining about the version:

```
Traceback (most recent call last):
  File "pretraining/loader.py", line 15, in <module>
    from torch_geometric.data import Data
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/root/miniconda3/envs/lightning/lib/python3.7/site-packages/torch_sparse/__init__.py", line 28, in <module>
    f'Detected that PyTorch and torch_sparse were compiled with '
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 0.0. Please reinstall the torch_sparse that matches your PyTorch install.
```

There are a few other similar issues and looks like they used the CPU version installed. This one I'm pretty sure it's GPU version so not sure why this issue happens.

**Comment by xiaoyongzhu** [comment]
@rusty1s if it helps - here's the Dockerfile I'm using as the environment (https://github.com/PyTorchLightning/pytorch-lightning/blob/master/dockers/base-conda/Dockerfile). Simply adding the following lines:

RUN \
    pip install torch-sparse  torch-cluster torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.5.0+${CUDA}.html \
    torch-geometric==1.5.0

RUN pip install --no-index torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-1.5.0+${CUDA}.html

**Comment by rusty1s** [comment]
Note that you have to replaced `${CUDA}` with your actual CUDA version, in this case `cu102`, e.g.:
```
RUN pip install --no-index torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-1.5.0+cu102.html
```

**Comment by xiaoyongzhu** [comment]
> Note that you have to replaced `${CUDA}` with your actual CUDA version, in this case `cu102`, e.g.:
> 
> ```
> RUN pip install --no-index torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-1.5.0+cu102.html
> ```

Oh I guess I forget mentioning that part... but yes I have that defined. Feel it's pretty weird since it shouldn't be that case, but it happens:(

**Comment by rusty1s** [comment]
That's indeed pretty weird. I'm clueless at the moment :(

Does give running 
```
pip install -verbose ...
```
give any further hint?

Are you required to run PyTorch 1.5.0? You may want to check if that error disappears using a newer PyTorch version.

**Comment by lkskstlr** [comment]
I had the same error using Pytorch 1.5.1 and cu102. I set PATH, CPATH as in the README and then installed torch-scatter with `pip install torch-scatter==2.0.5`. The installation ran through and the minimal example from the README runs and gives the same results. Thanks for the hints in this thread :+1:

**Comment by jasperhyp** [comment]
Had the same issue with Pytorch 1.4.0 & cu100.  Updated gcc & gxx, and then tried `pip install --verbose --no-index torch-scatter==2.0.4 -f https://pytorch-geometric.com/whl/torch-1.4.0+cu100.html` and succeeded.  Thank you guys! 👍
