### ISSUE TITLE
Can this `scatter` function be reproducible?

### ISSUE THREAD

**Issue by bicongwang** [rusty1s/pytorch_scatter#20]
I get it `scatter_add_` in official pytorch isn't reproducible because of the `atomicAdd`，the link is [Pytorch Reproducibility](https://pytorch.org/docs/stable/notes/randomness.html).

I wander can this `scatter` function be reproducible? Thx.

**Comment by rusty1s** [comment]
I do not fully understand your concerns, since `scatter_{}` ops are deterministic (except for the argmax in `scatter_max`).

**Comment by bicongwang** [comment]
Thanks for you explanation. I want to make result absolutely reproducible, but when I use `scatter` operation there is always a little different under the same configure. You have explained why it happens. However, how can I solve this problem（for more controllable test）?

**Comment by rusty1s** [comment]
This is not possible on GPU, especially not if you don't want to lose out on performance.

For higher reproducibility while testing, you can use `double` types, testing functions like `numpy.testing.assert_almost_equal` or simply the CPU version of all `scatter_{}` ops.

**Comment by bicongwang** [comment]
I know that slight numerical variations would not affect the result so much in deep learning, just for more robustness.

Thanks for you detailed answer.
