### ISSUE TITLE
Error in pip install cuda 11.2

### ISSUE THREAD

**Issue by abhigoku10** [rusty1s/pytorch_scatter#200]
@rusty1s  hi i am getting the following error when i run the installation below is the setup 
window10
cuda 11.2
pytorch1.8
vs2019
ERROR: Command errored out with exit status 1: 'c:\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Ska10\\AppData\\Local\\Temp\\pip-install-hyb8htvy\\torch-scatter_a87f35ff790549b89b18694bbd00b462\\setup.py'"'"'; __file__='"'"'C:\\Users\\zzz\\AppData\\Local\\Temp\\pip-install-hyb8htvy\\torch-scatter_a87f35ff790549b89b18694bbd00b462\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\\AppData\Local\Temp\pip-record-073o4fwt\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python36\Include\torch-scatter' Check the logs for full command output.

any idea howto solve this error

**Comment by rusty1s** [comment]
How do you try to install `torch-scatter`? This error should disappear when using the provided wheels.

**Comment by abhigoku10** [comment]
@rusty1s  i was trying to install through pip install --verbose --no-cache-dir torch-sparse/cluster/scatter , some how from your previous reponse now i am able to install it
