### ISSUE TITLE
ImportError: cannot import name 'scatter_mean' from 'torch_scatter' (unknown location)

### ISSUE THREAD

**Issue by YueeXiang** [rusty1s/pytorch_scatter#201]
torch: 1.4.0+cpu
torch-scatter:  torch_scatter-latest+cu101-cp37-cp37m-win_amd64.whl

Part of my code:

`
from torch_scatter import scatter_mean, scatter_max, scatter_add
`

When I run my code,  the error **'ImportError: cannot import name 'scatter_mean' from 'torch_scatter' (unknown location)'** comes out.
And I'm so confused about the version of torch-scatter matched with python, torch and other modules.

**Comment by rusty1s** [comment]
It seems like you are trying to install `torch-scatter` compiled for CUDA 10.1 and use it in a CPU-only PyTorch environment. This might well explain this error.
