### ISSUE TITLE
cannot install error 'torch.__config__'

### ISSUE THREAD

**Issue by FloatingMaple** [rusty1s/pytorch_scatter#203]
Collecting torch_scatter
  Using cached https://files.pythonhosted.org/packages/91/26/f2f0767a0e72c38d5d17f53117deb8aaafaf58f4ad658cee56cd5158c979/torch_scatter-2.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vezjggdv/torch-scatter/setup.py", line 9, in <module>
        from torch.__config__ import parallel_info
    ModuleNotFoundError: No module named 'torch.__config__'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vezjggdv/torch-scatter/

is this problem cause by my torch version?  how can i solute it?  thx

**Comment by rusty1s** [comment]
Is PyTorch installed on your side?

**Comment by FloatingMaple** [comment]
yeah，but it seems a very old version。
i update pytorch to 1.5.0, then get error about gcc "isnan" like this https://github.com/rusty1s/pytorch_scatter/issues/198 .
so i use parameter --no-index, anyway, it works . thx XD
