### ISSUE TITLE
torch-scatter Error!

### ISSUE THREAD

**Issue by kirima-h** [rusty1s/pytorch_scatter#205]
when I import torch-scatter,the error happend:
OSError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
DO you have some suggestion to the problem? Thanks.

**Comment by rusty1s** [comment]
Not entirely sure. PyTorch does provide `libtorch_cuda.so` and `libtorch_cpu.so` libraries, and I'm not sure why it searches for `libtorch_cuda_cu.so` instead. You may try to copy the `libtorch_cuda.so` shared library file and paste it to `libtorch_cuda_cu.so`

**Comment by kirima-h** [comment]
It's insteresting, I have tride to copy the libtorch_cuda.so shared library file and pasted it to libtorch_cuda_cu.so, but the problem happened again.

**Comment by vaydingul** [comment]
Any progress on this?

**Comment by vaydingul** [comment]
Installing torch-scatter with the following command solved my problem:

pip install **--no-index** torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+${CUDA}.html

I hope it also works for you!

**Comment by MushroomHunting** [comment]
Thanks vaydingul! This is the only thing that's worked for me. I'd previously been having problems when calling `import torch_scatter` with a `AttributeError: 'NoneType' object has no attribute 'origin'` for 1.8.1 pytorch installed with conda with `torch.version.cuda` = '11.1' .

**Comment by helblazer811** [comment]
> Thanks vaydingul! This is the only thing that's worked for me. I'd previously been having problems when calling `import torch_scatter` with a `AttributeError: 'NoneType' object has no attribute 'origin'` for 1.8.1 pytorch installed with conda with `torch.version.cuda` = '11.1' .

I am also having this same error on MacOS with pytorch 1.8.1.
