### ISSUE TITLE
Build docker image on Mac OS to run on server with CUDA installed

### ISSUE THREAD

**Issue by shimagoro** [rusty1s/pytorch_scatter#206]
I want to build a docker image with pytorch_scatter on Mac OS, and run it on Linux machine with CUDA installed.

I have following in my Dockerfile.

```
ENV CUDA_VERSION 10.1.0
ENV FORCE_CUDA="1"
ENV TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
RUN pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html
```

Inside the docker container running on my Mac, I can do import torch_scatter without any problem but on the cluster, import torch_scatter fails with 

```
File "/miniconda/lib/python3.7/site-packages/torch_scatter/__init__.py", line 17, in <module>
    raise AttributeError(e)
AttributeError: 'NoneType' object has no attribute 'origin'
```

I looked at /miniconda/lib/python3.7/site-packages/torch_scatter/ and find that there is no lib for cuda.

What is missing to make it work on servers with cuda installed?

**Comment by BestSonny** [comment]
@shimagoro  Have you solved the problem? I got the same issue. May I know how you solved the problem?

**Comment by zgojcic** [comment]
I have the same issue. It does however work if installed later in a running docker...

**Comment by cwichka** [comment]
@zgojcic @BestSonny @shimagoro - Did any one of you get the chance to solve their problem please ? I am stuck with the same issue when building with pytorch_scatter. Inside a running docker container, i can import it without any problem, however it fails on the cluster.
