### ISSUE TITLE
Question: non-contiguous `Tensor`s

### ISSUE THREAD

**Issue by Linux-cpp-lisp** [rusty1s/pytorch_scatter#207]
Does `pytorch_scatter` coerce the `input` `Tensor` to be contiguous? In other words, in:
```python
scatter(torch.ones(1).expand(100), torch.randint(0, 10, (100,)))
```
will a full size 100 contiguous copy of the `input` `Tensor` be allocated?

**Comment by rusty1s** [comment]
Yes, the `index` will be broadcasted, but `src` won't.

**Comment by Linux-cpp-lisp** [comment]
I see — thanks!
