### ISSUE TITLE
Very odd error on the introduction code

### ISSUE THREAD

**Issue by Hosein47** [rusty1s/pytorch_scatter#208]
I have torch version 1.6.0 and torch.cuda version 10.2. I followed the installation wrt my versions. When I run the first introduction code, I get this very strange error. 

####
10 data = Data(x=x, edge_index=edge_index.t().contiguous())
---> 11 Data(edge_index=[2, 4], x=[3, 1])

~/.local/lib/python3.6/site-packages/torch_geometric/data/data.py in __init__(self, x, edge_index, edge_attr, y, pos, normal, face, **kwargs)
     85                 self[key] = item
     86 
---> 87         if edge_index is not None and edge_index.dtype != torch.long:
     88             raise ValueError(
     89                 (f'Argument `edge_index` needs to be of type `torch.long` but '

AttributeError: 'list' object has no attribute 'dtype'
####

Any idea?

**Comment by rusty1s** [comment]
It seems like `edge_index` is not of type `torch.Tensor` but of type `list`. Can you show me the complete example code you are using?

**Comment by Hosein47** [comment]
First of all, I think I made a mistake and posted pytorch Geometric error here. Sorry for that. 
I used the exact starting code:

######
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1],
                           [1, 0],
                           [1, 2],
                           [2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())
>>> Data(edge_index=[2, 4], x=[3, 1])
######

**Comment by rusty1s** [comment]
I think there is a misunderstanding: `Data(edge_index=[2, 4], x=[3, 1])` the output when printing the above `data` object:
```python
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1],
[1, 0],
[1, 2],
[2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index.t().contiguous())
print(data)
```

**Comment by Hosein47** [comment]
Omg, sorry for this stupid mistake. Thanks for clarifying.
