### ISSUE TITLE
Torch scatter executes functional code upon import

### ISSUE THREAD

**Issue by TimZaman** [rusty1s/pytorch_scatter#209]
To keep imports in Python snappy, it's wise not to execute any functional code;

```py
import torch_scatter
```

Creates a cuda context on all visible gpus due to the call https://github.com/rusty1s/pytorch_scatter/blob/master/torch_scatter/__init__.py#L9

```py
suffix = 'cuda' if torch.cuda.is_available() else 'cpu'
```

This statement `torch.cuda.is_available()` should be encapsulated and not be executed upon import.

I'm a bit busy to make a PR now [sorry], just putting this here for posterity.

**Comment by rusty1s** [comment]
Interesting. Do you know of another way to check for CUDA availability without creating a CUDA context?

**Comment by TimZaman** [comment]
Best is to simply do it lazily and save in a global variable.

**Comment by TimZaman** [comment]
```py
$ time python -c "import torch_scatter"

real	0m3.838s
user	0m0.580s
sys	0m0.154s
```

**Comment by rusty1s** [comment]
Interesting, it's way faster for me. Most of the time in `import torch_scatter` is spent on importing `torch` (1.62s), and only `0.05s are used to run the remaining code in `__init__.py`.

**Comment by TimZaman** [comment]
The reason it's fast for you is probably because you're on a 1 gpu system. The functional calls describred above will create a cuda context on each gpu at import-time. That's pretty bad, because that is before anyone would have the chance to eg call [torch.cuda.set_device](https://pytorch.org/docs/stable/generated/torch.cuda.set_device.html)

**Comment by rusty1s** [comment]
Thanks :)

I think all we need to do for this is to replace the `torch.cuda.is_available` call [here](https://github.com/rusty1s/pytorch_scatter/blob/master/torch_scatter/__init__.py#L50) by `torch.version.cuda`. Can you confirm?

**Comment by rusty1s** [comment]
Should be fixed in https://github.com/rusty1s/pytorch_scatter/pull/282. Feel free to re-open if you encounter any issues.

**Comment by TimZaman** [comment]
Thanks Matt!
