### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by leftthomas** [rusty1s/pytorch_scatter#21]
/Users/leftthomas/anaconda3/lib/python3.7/site-packages/torch/lib/include/c10/core/Allocator.h:46:8: error: no template named 'unique_ptr' in namespace 'std'
  std::unique_ptr<void, DeleterFnPtr>&& move_context() {
  ~~~~~^
/Users/leftthomas/anaconda3/lib/python3.7/site-packages/torch/lib/include/c10/core/Allocator.h:67:48: error: no type named 'nullptr_t' in namespace 'std'
inline bool operator==(const DataPtr& dp, std::nullptr_t) noexcept {
                                          ~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: command 'gcc' failed with exit status 1

**Comment by mweiss17** [comment]
Hey there @leftthomas, so I have zero idea why this works, but I get the same error as you and this is the only way to install this library that works for me.

`MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ pip install torch-scatter`

I found the solution here: https://github.com/pytorch/audio/issues/57

If anybody has any insight into what exactly was going wrong that I had to specificy clang and clang++... lemme know

**Comment by leftthomas** [comment]
@mweiss17 Thanks for your solution.
