### ISSUE TITLE
torch_scatter installation

### ISSUE THREAD

**Issue by zhaodalong98** [rusty1s/pytorch_scatter#210]
Hello, pytorch-1.1.0、torchvision-0.3.0、cuda10.0，How should I install torch_scatter?My torch version is too low, so that I can not install through binary and source files

**Comment by rusty1s** [comment]
You can install `torch-scatter==1.2.0`, see [here](https://github.com/rusty1s/pytorch_scatter/releases/tag/1.2.0).

**Comment by zhaodalong98** [comment]
> You can install `torch-scatter==1.2.0`, see [here](https://github.com/rusty1s/pytorch_scatter/releases/tag/1.2.0).

With your help, I have solved the problem, thank you very much
