### ISSUE TITLE
installation on torch_scatter with cuda 11.2

### ISSUE THREAD

**Issue by bharadwajakshay** [rusty1s/pytorch_scatter#211]
I have trouble installing this repo with cuda 11.2.
`nvcc --version`  returns

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0`

Could you help me with the instructions to compile from the source and install. 

Thanks

**Comment by bharadwajakshay** [comment]
Ok, tried to install it using the command.
`pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu111.html`
but now throws an error 
`Exception has occurred: OSError
libtorch_cuda_cu.so: cannot open shared object file: No such file or directory`

**Comment by bharadwajakshay** [comment]
I tried creating a symbolic link named `libtorch_cuda_cu.so` to  `libtorch_cuda.so` in `torch/lib/`. But the issue still persists.

**Comment by rusty1s** [comment]
Which CUDA version does your PyTorch version use (as it does not come with CUDA 11.2 binaries)?

**Comment by bharadwajakshay** [comment]
Ok, this took some time to figure out, my pytorch was using 'CUDA 10.2' even though  the installed version was `11.2`. So after a lot of messing around and reinstalling, I got it to work with `Pytorch 1.8.1+cu102` and the binaries built for `10.2`. So I am going to close this issue.
