### ISSUE TITLE
Call for feature (scatter_dot_product)

### ISSUE THREAD

**Issue by speedcell4** [rusty1s/pytorch_scatter#214]
Hi. Thanks for providing such an elegant library. 
However, the scatter-version dot product operation is not provided currently.
In detail, I want to take the elements from the corresponding indices of `x` and `y`, respectively, and then compute the dot product, like the following.

```python
import torch
from torch import Tensor


def scatter_dot_product(x: Tensor, y: Tensor, index_x: Tensor, index_y: Tensor):
    return (x[index_x, ..., None, :] @ y[index_y, ..., :, None])[..., 0, 0]


if __name__ == '__main__':
    x = torch.randn((5, 3), requires_grad=True)
    y = torch.randn((5, 3), requires_grad=True)
    index_x = torch.randint(0, 5, (10,))
    index_y = torch.randint(0, 5, (10,))
    z = scatter_dot_product(x, y, index_x, index_y)
    print(f'x => {x}')
    print(f'y => {y}')
    print(f'index_x => {index_x}')
    print(f'index_y => {index_y}')
    print(f'z => {z}')

# x => tensor([[ 1.2552, -1.6125,  0.5630],
#         [ 0.5277, -0.0295, -0.9992],
#         [-1.2235, -0.7496, -0.3635],
#         [-0.6795, -1.4085,  0.2317],
#         [ 0.9238, -0.9243,  0.9383]], requires_grad=True)
# y => tensor([[ 1.0422, -0.4395,  1.4690],
#         [ 0.3440,  0.7634, -1.6526],
#         [-1.9791, -0.7835,  1.6198],
#         [ 0.4200, -0.0556,  0.9362],
#         [ 1.6092, -0.1032, -0.7982]], requires_grad=True)
# index_x => tensor([4, 1, 3, 2, 2, 3, 2, 3, 0, 3])
# index_y => tensor([1, 2, 0, 2, 2, 2, 2, 0, 0, 3])
# z => tensor([-1.9384, -2.6399,  0.2511,  2.4201,  2.4201,  2.8238,  2.4201,  0.2511,
#          2.8439,  0.0097], grad_fn=<SelectBackward>)
```

But directly performing indexing, i.e., `x[index_x]` and `y[index_y]`, will result in copying elements and thus cause the out-of-memory error, is that possible to provide a memory-efficient version of `scatter_dot_product` in the next version? That would be greatly helpful to me.
Thanks ahead~

**Comment by speedcell4** [comment]
I am not sure if the naming is correct, maybe it would be called `gather_dot_product`?

**Comment by rusty1s** [comment]
I guess the `torch-scatter` library is not meant to fuse different operations. You may look into [KeOps](https://github.com/getkeops/keops) to achieve something like that (although I'm not sure if they support irregular access).

**Comment by speedcell4** [comment]
Thanks~
