### ISSUE TITLE
Correct way to include pytorch_scatter in CMake project

### ISSUE THREAD

**Issue by kamikode** [rusty1s/pytorch_scatter#215]
I am trying to include pytorch scatter in a CMake project using add_subdirectory:

```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(torch-cpp-example)

list(APPEND CMAKE_PREFIX_PATH "libtorch")

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/pytorch_scatter)

add_executable(${PROJECT_NAME}  src/main.cpp)
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 14)

target_link_libraries(${PROJECT_NAME} torchscatter)

target_link_libraries(${PROJECT_NAME} ${TORCH_LIBRARIES})
```

However, when I put `#include <torchscatter/scatter.h>` into main.cpp, the file cannot be found. I am new to CMake, so I assume the problem is trivial and I am just doing something wrong. Thanks in advance for any help!

**Comment by rusty1s** [comment]
Here is a simple example on how to load `torchscatter` into C++: https://github.com/pytorch/vision/tree/master/examples/cpp/hello_world
You just need to replace `TorchVision` with `TorchScatter`.

**Comment by kamikode** [comment]
Thank you. It works correctly this way, I just had hoped that it would be possible to use torchscatter as a submodule instead, so users wouldn't need to compile torchscatter separately. I guess that's not supported then.

**Comment by DBraun** [comment]
Hi @rusty1s I'm having some difficulty with the example linked above.

my environment: Windows, cuda 11.3 for everything, torch 1.10, python 3.9

I built pytorch_scatter to `C:\repos\graph-project\pytorch_scatter\build` and this folder has `TorchScatterConfig.cmake` but not `TorchScatterTargets.cmake`

**C:\repos\graph-project\CMakeLists.txt:**
```
cmake_minimum_required(VERSION 3.10)
project(hello-world)

# The first thing do is to tell cmake to find the TorchVision library.
# The package pulls in all the necessary torch libraries,
# so there is no need to also add `find_package(Torch)` here.
find_package(TorchScatter REQUIRED)

add_executable(hello-world main.cpp)

# We now need to link the TorchVision library to our executable.
# We can do that by using the TorchVision::TorchVision target,
# which also adds all the necessary torch dependencies.
target_compile_features(hello-world PUBLIC cxx_range_for)
target_link_libraries(hello-world TorchScatter::TorchScatter)
set_property(TARGET hello-world PROPERTY CXX_STANDARD 14)
```

I did
```bash
C:\repos\graph-project\build>cmake .. -DCMAKE_PREFIX_PATH=C:\repos\libtorch;C:\repos\graph-project\pytorch_scatter\build
```
resulting in
```
CMake Error at pytorch_scatter/build/TorchScatterConfig.cmake:47 (include):
  include could not find requested file:

    C:/repos/graph-project/pytorch_scatter/build/TorchScatterTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)
```

The code around TorchScatterConfig.cmake:47 is
```
if(NOT TARGET ${PN}::TorchScatter)
include("${CMAKE_CURRENT_LIST_DIR}/${PN}Targets.cmake")
```
which appears to be from [here](https://github.com/rusty1s/pytorch_scatter/blob/2cabeaea26b35569e71ad510fcaa8bf24e885f55/cmake/TorchScatterConfig.cmake.in#L23).

What might my mistake be?

**Comment by DBraun** [comment]
I tried out the add_subdirectory way because you don't need to build pytorch_scatter in advance. I also modified pytorch_scatter/CMakeLists.txt to have WITHCUDA on

**C:\repos\graph-project\CMakeLists.txt:**
```
add_subdirectory(pytorch_scatter)
include_directories(C:/Python39/include)
include_directories(pytorch_scatter/csrc)
target_link_libraries(${PROJECT_NAME} "C:/Python39/libs/python39.lib")
target_include_directories(${PROJECT_NAME} PUBLIC pytorch_scatter/Release/)
target_link_libraries(${PROJECT_NAME} torchscatter)
```
and the main.cpp has
```c++
#include "scatter.h"
torch::Tensor src = torch::tensor({ 0.5, 0.4, 0.1, 0.6 });
torch::Tensor index = torch::tensor({ 0, 0, 1, 1 });
std::cout << src << std::endl;
std::cout << index << std::endl;
std::cout << scatter_mean(src, index, 0, torch::nullopt, torch::nullopt) << std::endl;
```

Then I get a missing symbol:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "class at::Tensor __cdecl scatter_mean(class at::Tensor,class at::Tensor,__int64,class c10::optional<class at::Tensor>,class c10::optional<__int64>)" (?scatter_mean@@YA?AVTensor@at@@V12@0_JV?$optional@VTensor@at@@@c10@@V?$optional@_J@4@@Z)	GraphProjectC:\repos\graph-project\build\GraphProject.obj	1	
```

But I can see `pytorch_scatter\Release\torchscatter.lib` in the linker options in Visual Studio.

So I tried
DUMPBIN /EXPORTS /out:my_log1 torchscatter.lib 
DUMPBIN /HEADERS /out:my_log2 torchscatter.lib 
DUMPBIN /SYMBOLS /out:my_log3 torchscatter.lib

but I don't see anything close to scatter_mean in the logs

**Comment by rusty1s** [comment]
Shouldn't this be still`#include <torchscatter/scatter.h>`?
