### ISSUE TITLE
Installing in a docker

### ISSUE THREAD

**Issue by zgojcic** [rusty1s/pytorch_scatter#216]
Hi, 

I am trying to build a docker image with pytoch_scatter on a Linux machine with CUDA. 

I use the following command in my Dockerfile:

`RUN pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu110.html`

When I try to import torch_scatter within the container I get the following error:

```
File "/miniconda/lib/python3.7/site-packages/torch_scatter/__init__.py", line 17, in <module>
    raise AttributeError(e)
AttributeError: 'NoneType' object has no attribute 'origin'
```
However, if I install torch_scatter in the running docker container it works just fine. 

Is there a way to fix this? I have seen that the same issue was already reported in #206

Thank you in advance.

**Comment by rusty1s** [comment]
Hopefully, https://github.com/rusty1s/pytorch_geometric/issues/2429 is useful to you.

**Comment by cwichka** [comment]
@zgojcic -  Did you get the chance to solve your problem please ? I am stuck with the same issue when building with pytorch_scatter. Inside a running docker container, i can import it without any problem, however it fails on the cluster.

I am using cuda-11.2 and pytorch-1.8.0 (from nvcr.io/nvidia/pytorch:21.02-py3)

`root@c7bddaad280e:/app# python -c "import torch; print(torch.__version__)"
1.8.0a0+52ea372
root@c7bddaad280e:/app# python -c "import torch; print(torch.version.cuda)"
11.2
`
I use the following commands in my dockerfile

`ENV PATH="/usr/local/cuda-11.2/bin:${PATH}"
ENV CPATH="/usr/local/cuda-11.2/include:${CPATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda-11.2/lib64:${LD_LIBRARY_PATH}"

RUN pip install --no-cache-dir torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+cu112.html
RUN pip install --no-cache-dir torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+cu112.html
RUN pip install --no-cache-dir torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+cu112.html
RUN pip install --no-cache-dir torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cu112.html
RUN pip install --no-cache-dir torch-geometric`

Thanks in advance.

**Comment by rusty1s** [comment]
We do not provide any wheels for `cu112`, so I guess there is some installation error when trying to build the extension packages from source.

**Comment by cwichka** [comment]
Thanks for your reply @rusty1s ! 

Unfortunately, as far as i have debugged i couldn't find any installation error when building from source. I have tried as well to change the base image am using to nvcr.io/nvidia/pytorch:20.12-py (pytorch1.8.0 and cu11.1) accordingly and use exiting PyG wheels (torch-1.8.0+cu111) but i keep getting the same issue. 

Anyway, after a lot of retrials and testings, instead of relying on pytorch nvidia images, i've created a customized one where i was finally able to run it on the cluster without any problem. In my dockerfile, i have installed the latest pytorch version along with the recent pytorch-geometric wheels (1.9.0+cu111) using nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04 as a base image.

**Comment by Haggaim** [comment]
Would you mind sharing your Dockerfile, @cwichka ? that would be greatly appreciated.
@rusty1s any pointers to more up-to-date PyG dockerfiles? the current one in the repo is pretty old
Thanks, guys!

**Comment by rusty1s** [comment]
Will look into updating the dockerfile :) Happy to take any help on this one.

**Comment by cwichka** [comment]
Sorry for my late response @Haggaim . Here is my Dockerfile 
`FROM nvcr.io/nvidia/cuda:11.1.1-cudnn8-devel-ubuntu20.04

RUN apt-get update && \
    apt-get install -y sudo \
                       python-is-python3 \
                       python3-pip 

RUN pip3 install --no-cache-dir torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

RUN pip install --no-cache-dir torch-scatter -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
RUN pip install --no-cache-dir torch-sparse -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
RUN pip install --no-cache-dir torch-cluster -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
RUN pip install --no-cache-dir torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.9.0+cu111.html
RUN pip install --no-cache-dir torch-geometric

RUN echo "alias python=python3" >> ~/.bashrc
RUN alias python=python3
RUN python -m pip install pytest

WORKDIR /app
ENTRYPOINT bash`
