### ISSUE TITLE
Implement custom reduce method

### ISSUE THREAD

**Issue by xcgoner** [rusty1s/pytorch_scatter#217]
I just wonder whether there is any way to implement some custom reduce method in scatter.
For example, say I want to get the sum of the top-k (k>1) values during the reduce, which could not be supported by any of the current reduce methods like max or sum. 
Is there anyway to do this kind of thing or write my own reduce function?
Thanks in advance.

**Comment by rusty1s** [comment]
This is not possible as far as I know without implementing your own dedicated kernel. One alternative is to convert your input tensor into a dense representation, e.g., going from `[E, D]` to `[N, max_number_of_same_indices, D]`, and apply a dense reduction there. This will consume more memory though.

**Comment by digital-idiot** [comment]
> This is not possible as far as I know without implementing your own dedicated kernel.

Hi @rusty1s would you give us some pointer regarding how to go about implementing such dedicated kernel. I am hoping this can be done with some additional `C++` and `CUDA` implementation on top of `pytorch_scatter`. If I am not mistaken, the index wise broadcasting is already there with ops like `add`, `mean` etc. In my case I am interested in **fitting curve (for interpolation) on each index group**. So any guidance would be great.

**Comment by xcgoner** [comment]
> 
> 
> > This is not possible as far as I know without implementing your own dedicated kernel.
> 
> Hi @rusty1s would you give us some pointer regarding how to go about implementing such dedicated kernel. I am hoping this can be done with some additional `C++` and `CUDA` implementation on top of `pytorch_scatter`. If I am not mistaken, the index wise broadcasting is already there with ops like `add`, `mean` etc. In my case I am interested in **fitting curve (for interpolation) on each index group**. So any guidance would be great.

Just some follow-ups.
I need custom reduce for some weird gnn model.
I found that it is actually very easy to implement custom reduce method in DGL with some simple python code. However, most of the existing gnn works are implemented by PyG. So we have to either implement the kernel in PyG/scatter, or transfer the entire model to DGL... so just choose your pain...

**Comment by rusty1s** [comment]
DGL uses a slow mechanism to allow for arbitrary aggregations (known as the degree binning approach), which groups all nodes with the same degree and perform aggregation sequentially. This is also possible to implement in PyG, but is rather in-efficient. Here is an (untested) code to achieve that:
```python
degree = scatter_add(torch.ones_like(index), index)
out = torch.empty(N, out_channels)
for d in range(1, int(degree.max())):
    mask = degree == d
    x_binned = x[mask[index]]
    if x_binned.numel() == 0:
        continue
    x_binned = x_binned.view(-1, d, x.size(-1))
    x_out = ... # Perform aggregation of `x_binned` by reducing the second dimension
    ...
    out[mask] = x_out
```

In case one wants to implement a dedicated implementation for each index group, one can adapt the `segment_csr` kernel and modify it accordingly, see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/csrc/cuda/segment_csr_cuda.cu#L62-L95), in which each thread will process exactly one index group.
