### ISSUE TITLE
Corresponding group index of the reduced tensor

### ISSUE THREAD

**Issue by digital-idiot** [rusty1s/pytorch_scatter#218]
When applying scatter aggregation operation such as `scatter_mean` how to obtain a tensor with corresponding group index of the reduced tensor. Is the order of the index is maintained? In that case, `torch.unique(<index>)` will also have the same order? See the example below. I want to get the corresponding index tenor below the output. 

![mean](https://user-images.githubusercontent.com/10576475/117677303-a1170b80-b1ae-11eb-96d4-cbe2af1aa7c0.png)

**Comment by rusty1s** [comment]
Yes :)
