### ISSUE TITLE
scatter 6000-times slower with int64 compared to int32

### ISSUE THREAD

**Issue by demmerichs** [rusty1s/pytorch_scatter#219]
As this project aims at providing convenience to the pytorch scatter operations I just wanted to link a issue I just put on the official pytorch repo also here, as I also tested the scatter operations from this project and found they suffered from the same drawbacks.

https://github.com/pytorch/pytorch/issues/58136

**Comment by rusty1s** [comment]
Thanks for letting me know. Is this also present in our own CUDA kernels, e.g., in case using`LongTensor` in `scatter_max`?
