### ISSUE TITLE
Scattering elements into output which have depth?

### ISSUE THREAD

**Issue by kevindckr** [rusty1s/pytorch_scatter#228]
Is it possible to scatter elements into the output tensor which have depth?

In an contrived example of my potential application I have `n` XY points each with an associated RGB color that I would like to discretize onto a grid.

```
n = 100
colors = torch.rand((n, 3))
points = torch.randint(0, 10, (n, 2))
x_min, x_max = torch.min(points[:, 0]).data, torch.max(points[:, 0]).data
y_min, y_max = torch.min(points[:, 1]).data, torch.max(points[:, 1]).data
```

The indices of points which fall into any given cell can be determined by using `torch.bucketize`.

```
target = torch.zeros((5, 5, 3))
eps = torch.finfo(torch.float32).eps # Bucketize on the "left"
x_steps = torch.linspace(x_min, x_max + eps, target.shape[0] + 1)
y_steps = torch.linspace(y_min, y_max + eps, target.shape[1] + 1)
x_bucket_indices = torch.bucketize(points[:, 0], x_steps)
y_bucket_indices = torch.bucketize(points[:, 1], y_steps)
```

So now when applying `scatter`(_`mean`) I have my `src`=`colors` and my `index`=`x/y_bucket_indices` (and my `out`=`target`). 

```
xy_bucket_indices = torch.stack([x_bucket_indices, y_bucket_indices])
scatter_mean(colors, xy_bucket_indices, target)
```

Though I receive the following exception

> RuntimeError: The expanded size of the tensor (3) must match the existing size (100) at non-singleton dimension 1. Target sizes: [100, 3]. Tensor sizes: [2, 100]

Which I have two possible interpretations of. Either I need to pass an `(n, n)` tensor for the indices or `scatter` doesn't "understand" how to, well, scatter elements with depth `(,3)`. 

**Does `scatter` support the kind of operation I have described?**

**Comment by rusty1s** [comment]
You need to convert your 2D-indices to one-dimensional ones first, and then apply a reshape after the `scatter` call:
```python
indices = xy_bucket_indices[0] * (xy_bucket_indices[1].max() + 1) + xy_bucket_indices[1]
scatter_mean(colors, indices, dim=0).view(x_steps.size(0), y_steps.size(0), 3)
```
