### ISSUE TITLE
error in torch_scatter.scatter_logsumexp

### ISSUE THREAD

**Issue by huangruizhe** [rusty1s/pytorch_scatter#230]
The following code:
```
import torch
import torch_scatter
a=torch.rand(3,2)
b=torch.as_tensor([[1,2],[1,3],[0,3]])
c=torch.rand(3,5)
torch_scatter.scatter_logsumexp(a, b, dim=1, out=c)
```
will result in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.8/site-packages/torch_scatter/composite/logsumexp.py", line 35, in scatter_logsumexp
    out = out.sub(max_per_src_element).exp()
RuntimeError: The size of tensor a (5) must match the size of tensor b (2) at non-singleton dimension 1
```

However, if we run this (following the above codes):
```
d = torch_scatter.scatter_logsumexp(a, b, dim=1, dim_size=5)
torch.logaddexp(c, d)
```
It works.
Just wondered why the results cannot be accumulated in the tensor specified by the `out` parameter. Or I have done something wrong. Thanks!

**Comment by rusty1s** [comment]
This is indeed a bug. I fixed it in master, see https://github.com/rusty1s/pytorch_scatter/commit/9d4cf96d3f11de0b911f78b57914da9d303d3dd7. Let me know if this resolves your issues :)

**Comment by huangruizhe** [comment]
Thanks! Shall I install torch_scatter from source?

**Comment by rusty1s** [comment]
You can either install fresh from source or just apply the changes in https://github.com/rusty1s/pytorch_scatter/commit/9d4cf96d3f11de0b911f78b57914da9d303d3dd7 in your already installed version (somewhere in `python/...site-packages/`). This does not require re-compiling C++/CUDA files.
