### ISSUE TITLE
Can the pytorch_scatter be used to implement superpixel unpooling

### ISSUE THREAD

**Issue by cyskyvein** [rusty1s/pytorch_scatter#232]
I can use the pytorch_scatter to implement the pooling operation.
Anybody known how can use this to implement the ROI-unpooling operation?
Thanks!

**Comment by rusty1s** [comment]
The inverse op of `scatter` is a simple gathering call, e.g.:
```
outputs = scatter(inputs, index, dim=0)  # Pool
new_inputs = outputs[index]  # Unpool
```
which should help you to implement ROI unpooling.
