### ISSUE TITLE
Scatter max bug with negative numbers

### ISSUE THREAD

**Issue by jbcdnr** [rusty1s/pytorch_scatter#24]
Hi,

I tracked down a bug in version `1.0.4` when computing `scatter_max` on negative numbers. Is it fixed in master? Or is it expected behaviour?

```
>>> import torch
>>> import torch_scatter
>>> torch_scatter.scatter_max(torch.tensor([-.1, -.2, -.3]), torch.tensor([0, 1, 0]))
(tensor([0., 0.]), tensor([-1, -1])) # instead of (tensor([-.1, -.2]), tensor([0, 1]))
```

For now I shift my values to positive, apply max then shift back.

Thank you

**Comment by rusty1s** [comment]
It is expected behaviour. It can be bypassed by passing, e.g., fill_value=-1e16 as additional argument.

**Comment by jzhou316** [comment]
Maybe add this to the documentation? And any explanation why? I encountered the same problem and spent so much time debugging and finally got here. It is not very noticeable since the whole program can run smoothly, but the results just don't make sense. Also, I found that scatter_min has the same problem, where we could set fill_value=1e16 to bypass.

**Comment by rusty1s** [comment]
It is fixed in master for `torch-scatter` and when using the `scatter_` wrapper of PyG.

**Comment by jzhou316** [comment]
Great! Thanks.

**Comment by bbrighttaer** [comment]
I just tried the example in README.md but had this
```python
>>> src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
>>> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
>>> out, argmax = scatter_max(src, index)
>>> out
tensor([[-9223372036854775808, -9223372036854775808,                    4,
                            3,                    2,                    0],
        [                   2,                    4,                    3,
         -9223372036854775808, -9223372036854775808, -9223372036854775808]])
```
torch==1.1.0
torch-scatter==1.3.1

**Comment by rusty1s** [comment]
I see, the `fill_value` changed recently to a large negative value. Calling `scatter_max(src, index, fill_value=0)` should print out the desired output. I will change the `README` accordingly.
