### ISSUE TITLE
Exception has occurred: TypeError scatter_max() got an unexpected keyword argument 'fill_value'

### ISSUE THREAD

**Issue by fraazor** [rusty1s/pytorch_scatter#240]
Hi,

I run torch 1.7.1 and torch-scatter 2.0.8 and I receive the following error message which is quite unclear to me since fill value is a common keyword for many versions. 

Exception has occurred: TypeError
scatter_max() got an unexpected keyword argument 'fill_value'

I upgraded to 2.0.4 from 1.4.0 which did not show this error message but also did not seem to work. Any scatter_max output was fully filled by the fill value, despite input features having legit positive values and corresponding index groups. I believed this to be an version issue but the latest version is not working with my current setup.

Has anybody seen this error with the latest torch-scatter version before?

Using the inspect function, I cannot find the argument either:
>>> inspect.getfullargspec(torch_scatter.scatter_max)
FullArgSpec(args=['src', 'index', 'dim', 'out', 'dim_size'], varargs=None, varkw=None, defaults=(-1, None, None), kwonlyargs=[], kwonlydefaults=None, annotations={'return': typing.Tuple[torch.Tensor, torch.Tensor], 'src': <class 'torch.Tensor'>, 'index': <class 'torch.Tensor'>, 'dim': <class 'int'>, 'out': typing.Union[torch.Tensor, NoneType], 'dim_size': typing.Union[int, NoneType]})
>>> torch_scatter.__version__
'2.0.8'

**Comment by rusty1s** [comment]
The `fill_value` argument was removed in `torch-scatter>=2.0.0` as it introduced a lot of problems for `scatter_max`. In `scatter_max`, we usually want to fill missing values with `zero`, while we also want to allow for negative output values.

If you want to restore the old behavior, you can define `out` before-hand and set it to your desired `fill_value`:
```python
out = src.new_zeros(output_shape)
scatter_max(src, index, dim=..., out=out)
```
