### ISSUE TITLE
torch_sparse/_convert_cpu.so: undefined symbol: _ZNK2at6Tensor5zero_Ev

### ISSUE THREAD

**Issue by shuimei** [rusty1s/pytorch_scatter#248]
code:
`In [1]: import torch`
`In [2]: from torch_geometric.data import Data`

error:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-b336892afbe1> in <module>()
----> 1 from torch_geometric.data import Data

~/anaconda3/lib/python3.7/site-packages/torch_geometric/__init__.py in <module>()
      5 from .debug import is_debug_enabled, debug, set_debug
      6
----> 7 import torch_geometric.data
      8 import torch_geometric.loader
      9 import torch_geometric.transforms

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py in <module>()
----> 1 from .data import Data
      2 from .hetero_data import HeteroData
      3 from .temporal import TemporalData
      4 from .batch import Batch
      5 from .dataset import Dataset

~/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py in <module>()
      1 from typing import (Optional, Dict, Any, Union, List, Iterable, Tuple,
      2                     NamedTuple, Callable)
----> 3 from torch_geometric.typing import OptTensor, NodeType, EdgeType
      4 from torch_geometric.deprecation import deprecated
      5

~/anaconda3/lib/python3.7/site-packages/torch_geometric/typing.py in <module>()
      2
      3 from torch import Tensor
----> 4 from torch_sparse import SparseTensor
      5
      6 # Types for accessing data ####################################################

~/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py in <module>()
     14 ]:
     15     torch.ops.load_library(importlib.machinery.PathFinder().find_spec(
---> 16         f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
     17
     18 if torch.cuda.is_available():  # pragma: no cover

~/anaconda3/lib/python3.7/site-packages/torch/_ops.py in load_library(self, path)
    108             # static (global) initialization code in order to register custom
    109             # operators with the JIT.
--> 110             ctypes.CDLL(path)
    111         self.loaded_libraries.add(path)
    112

~/anaconda3/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: /root/anaconda3/lib/python3.7/site-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZNK2at6Tensor5zero_Ev

I followed the Quick Start installation, with torch=1.10.0+cu102

**Comment by rusty1s** [comment]
This is related to a potentially false intallation of `torch-sparse`. Can you show me the installation log when running:
```
pip uninstall torch-sparse
pip uninstall torch-sparse
pip install torch-sparse -f https://data.pyg/org/whl/torch-1.10.0+cu102.html
```

**Comment by guillaumehu** [comment]
There is the same issue when running the Colab Notebooks tutorials.

**Comment by rusty1s** [comment]
Colab notebooks are fixable as suggested here: https://github.com/pyg-team/pytorch_geometric/issues/3484

**Comment by guillaumehu** [comment]
Great, thanks a lot !

**Comment by gwn6666** [comment]
> This is related to a potentially false intallation of `torch-sparse`. Can you show me the installation log when running:
> 
> ```
> pip uninstall torch-sparse
> pip uninstall torch-sparse
> pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu102.html
> ```

it works!!
thanks a lot!

**Comment by shuimei** [comment]
`Found existing installation: torch-sparse 0.6.12
Uninstalling torch-sparse-0.6.12:
  Would remove:
    /root/anaconda3/lib/python3.7/site-packages/test/*
    /root/anaconda3/lib/python3.7/site-packages/torch_sparse-0.6.12.dist-info/*
    /root/anaconda3/lib/python3.7/site-packages/torch_sparse/*
  Would not remove (might be manually added):
    /root/anaconda3/lib/python3.7/site-packages/test/test_basis.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_broadcasting.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_conv.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_fps.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_gather.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_graclus.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_grid.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_knn.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_multi_gpu.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_nearest.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_radius.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_rw.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_sampler.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_scatter.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_segment.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_weighting.py
    /root/anaconda3/lib/python3.7/site-packages/test/test_zero_tensors.py
Proceed (Y/n)?   Successfully uninstalled torch-sparse-0.6.12
~
`
`pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu102.html
Looking in links: https://data.pyg.org/whl/torch-1.10.0+cu102.html
Collecting torch-sparse
  Downloading https://data.pyg.org/whl/torch-1.10.0%2Bcu102/torch_sparse-0.6.12-cp37-cp37m-linux_x86_64.whl (2.9 MB)
     |████████████████████████████████| 2.9 MB 500 kB/s
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from torch-sparse) (1.1.0)
Installing collected packages: torch-sparse
`

but the problem remains

**Comment by rusty1s** [comment]
You also need to uninstall and update `torch-scatter`, similarly to how you did it with `torch-sparse`.

**Comment by jyl-ucsd** [comment]
I'm trying to solve the same problem under `torch 1.10.0+cu111`, but after re-installing torch-scatter and torch-sparse the problem is still unsolved.

command I used:
`
pip uninstall torch-scatter
pip uninstall torch-sparse
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
`

**Comment by rusty1s** [comment]
Can you install via
```
pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.10.0+cu111.html

**Comment by Sparrow711** [comment]
Hey! I am having the same problem. And I tried to resolve this issue using the solution mentioned in this thread. Following is the error that I receive:

/home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
Traceback (most recent call last):
  File "/home/anshal/summer_intern/Pointcept-main/exp/scannet/semseg-pt-v2m2-0-base/code/tools/train.py", line 9, in <module>
    from pointcept.engines.train import Trainer
  File "/home/anshal/summer_intern/Pointcept-main/exp/scannet/semseg-pt-v2m2-0-base/code/pointcept/engines/train.py", line 25, in <module>
    from pointcept.models import build_model
  File "/home/anshal/summer_intern/Pointcept-main/exp/scannet/semseg-pt-v2m2-0-base/code/pointcept/models/__init__.py", line 7, in <module>
    from .point_transformer_v2 import *
  File "/home/anshal/summer_intern/Pointcept-main/exp/scannet/semseg-pt-v2m2-0-base/code/pointcept/models/point_transformer_v2/__init__.py", line 8, in <module>
    from .point_transformer_v2m1_origin import *
  File "/home/anshal/summer_intern/Pointcept-main/exp/scannet/semseg-pt-v2m2-0-base/code/pointcept/models/point_transformer_v2/point_transformer_v2m1_origin.py", line 14, in <module>
    from torch_scatter import segment_csr
  File "/home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/anshal/.local/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/home/anshal/anaconda3/envs/pointcept/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
/home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
Traceback (most recent call last):
  File "/home/anshal/summer_intern/Pointcept-main/tools/train.py", line 9, in <module>
    from pointcept.engines.train import Trainer
  File "/home/anshal/summer_intern/Pointcept-main/pointcept/engines/train.py", line 25, in <module>
    from pointcept.models import build_model
  File "/home/anshal/summer_intern/Pointcept-main/pointcept/models/__init__.py", line 7, in <module>
    from .point_transformer_v2 import *
  File "/home/anshal/summer_intern/Pointcept-main/pointcept/models/point_transformer_v2/__init__.py", line 8, in <module>
    from .point_transformer_v2m1_origin import *
  File "/home/anshal/summer_intern/Pointcept-main/pointcept/models/point_transformer_v2/point_transformer_v2m1_origin.py", line 14, in <module>
    from torch_scatter import segment_csr
  File "/home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/anshal/.local/lib/python3.10/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/home/anshal/anaconda3/envs/pointcept/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/anshal/anaconda3/envs/pointcept/lib/python3.10/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK3c107SymBool10guard_boolEPKcl

I installed pytorch version 2.0.1, cuda 11.7 and torch-scatter 2.1.1

**Comment by Sruthik22** [comment]
I also have the same issue: OSError: .conda/envs/GIGN/lib/python3.9/site-packages/torch_sparse/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by rusty1s** [comment]
This usually indicates a version conflict, so something with your CUDA and PyTorch version does not match with the installed version coming from `torch-scatter`. Any additional information about your system and how you installed `torch-scatter` would let me help you better.

**Comment by Sparrow711** [comment]
I have cuda 11.7 installed on my laptop. And in the conda environment I have pytorch 2.0.1 for cuda 11.7, torch-scatter (2.1.1+pt20cu117). And I used the following command to install pytorch-scatter, pytorch-sparse and pytorch cluster:
conda install pytorch-cluster pytorch-scatter pytorch-sparse -c pyg -y

**Comment by rusty1s** [comment]
How did you install PyTorch? It is preferred that you install it from the official binaries (not from something like `conda-forge`).

**Comment by Sparrow711** [comment]
I installed Pytorch using the instructions on their site. I used the following:
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

**Comment by rusty1s** [comment]
Thanks for sharing. Can you try to run install `torch-scatter` (and so on) via `pip` (with `-f` option) rather than via `conda`? Note that you may need to uninstall the conda versions of it first. This should help me to track down the issue better.

**Comment by rookiie1918** [comment]
OSError: /home/lijuncai/app/anaconda3/envs/ljc/lib/python3.9/site-packages/torch_cluster/_grid_cuda.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
torch_version is 1.12.1+cu102

**Comment by mainguyenanhvu** [comment]
I found the solution [here](https://stackoverflow.com/a/78340193/10987905).

**Comment by viettham1998** [comment]
I also have the same issue: 
`OSError: /home/hvtham/.local/lib/python3.10/site-packages/torch_sparse/_convert_cpu.so: undefined symbol: _ZN3c1013ParallelGuardC1Eb`

My torch_version is 2.2.1+cu121

**Comment by Ir1d** [comment]
Hi @viettham1998 did you solve this?

**Comment by rookiie1918** [comment]
not yet,I change it to CPU




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rusty1s/pytorch_scatter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月1日(星期四) 上午7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rusty1s/pytorch_scatter] torch_sparse/_convert_cpu.so: undefined symbol: _ZNK2at6Tensor5zero_Ev (Issue #248)





 
Hi @viettham1998 did you solve this?

**Comment by viettham1998** [comment]
> Hi @viettham1998 did you solve this?

I solved this problem but it was so long ago that I don't remember how to fix it anymore :>

**Comment by sei-jratchford** [comment]
i also have the same issue with torch version 2.4.0+cu121, torch-scatter version 2.1.2 and torch-sparse version 0.6.18

**Comment by Zhanpeng1202** [comment]
To those who use mirror source, 
I also have the same issue with torch version 2.0.1 + cu118 and I totally follow the official instructions given by other repo. 

```{shell}
pip uninstall torch-scatter -y
pip install torch-scatter --no-index -f https://data.pyg.org/whl/torch-2.0.1+cu118.html
```

Finally i find that the Ali source or Tshinghua source would give you the wrong package,  we have to put the flag  `--no-index` on, otherwise the pip would still find the wrong one even if they has the same verison number
