### ISSUE TITLE
Installation issues with gcc >= 6

### ISSUE THREAD

**Issue by RunOrVeith** [rusty1s/pytorch_scatter#25]
Installation fails using pytorch 1.0.1, python 3.6.5, cuda 9.0, gcc 6.0:
This happens both on the current master and on 1.1.1
$CPATH and $PATH are set to include cuda.

Running `python setup.py install` results in many errors such as:

```bash
/home/veith/Projects/py3.6/lib/python3.6/site-packages/torch/lib/include/ATen/core/TensorMethods.h:1117:48:   required from here
/usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
```

The full log can be found here: 
[install_log.txt](https://github.com/rusty1s/pytorch_scatter/files/2896825/install_log.txt)

I am not sure what exactly the issue is!

**Comment by RunOrVeith** [comment]
Apparently it works using gcc-5 and g++-5.
I found this based on [this issue](https://github.com/facebookarchive/caffe2/issues/1898).

**Comment by rusty1s** [comment]
Thanks for letting me know and glad that it's now working. Sadly, there is not much I can do about it.
