### ISSUE TITLE
GCC kinda error | Installing from source

### ISSUE THREAD

**Issue by marcioluish** [rusty1s/pytorch_scatter#250]
Hi, I'm trying to install scatter from source but I just keep having this error:
My setup:

NVIDIA A100 40GB
Torch: 1.9.0
CUDA: 11.3

Yes, I've already tried to install it in other versions, like:
Torch: 1.8.0
CUDA: 11.1

<details>
  <summary>Full error traceback:</summary>

>root@a51f73afaab2:/app/master/pytorch_scatter-master# python setup.py install
>running install
>running bdist_egg
>running egg_info
>writing torch_scatter.egg-info/PKG-INFO
>writing dependency_links to torch_scatter.egg-info/dependency_links.txt
>writing requirements to torch_scatter.egg-info/requires.txt
>writing top-level names to torch_scatter.egg-info/top_level.txt
>reading manifest file 'torch_scatter.egg-info/SOURCES.txt'
>reading manifest template 'MANIFEST.in'
>writing manifest file 'torch_scatter.egg-info/SOURCES.txt'
>installing library code to build/bdist.linux-x86_64/egg
>running install_lib
>running build_py
>running build_ext
>building 'torch_scatter._segment_coo_cuda' extension
>gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DWITH_CUDA -Icsrc -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c csrc/segment_coo.cpp -o build/temp.linux-x86_64-3.8/csrc/segment_coo.o -O2 -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1013" -DTORCH_EXTENSION_NAME=_segment_coo_cuda -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14
>In file included from /opt/conda/lib/python3.8/site-packages/torch/include/torch/script.h:10,
>                 from csrc/segment_coo.cpp:2:
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h: In instantiation of ‘torch::autograd::variable_list torch::autograd::CppNode<T>::apply(torch::autograd::variable_list&&) [with T = GatherCOO; torch::autograd::variable_list = std::vector<at::Tensor>]’:
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:284:15:   required from here
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:311:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  311 |   if (num_outputs > num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:323:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  323 |   if (num_outputs != num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:334:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
>  334 |   for (int i = 0; i < num_outputs; ++i) {
>      |                   ~~^~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h: In instantiation of ‘torch::autograd::variable_list torch::autograd::CppNode<T>::apply(torch::autograd::variable_list&&) [with T = SegmentMaxCOO; torch::autograd::variable_list = std::vector<at::Tensor>]’:
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:284:15:   required from here
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:311:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  311 |   if (num_outputs > num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:323:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  323 |   if (num_outputs != num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:334:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
>  334 |   for (int i = 0; i < num_outputs; ++i) {
>      |                   ~~^~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h: In instantiation of ‘torch::autograd::variable_list torch::autograd::CppNode<T>::apply(torch::autograd::variable_list&&) [with T = SegmentMinCOO; torch::autograd::variable_list = std::vector<at::Tensor>]’:
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:284:15:   required from here
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:311:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  311 |   if (num_outputs > num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:323:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  323 |   if (num_outputs != num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:334:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
>  334 |   for (int i = 0; i < num_outputs; ++i) {
>      |                   ~~^~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h: In instantiation of ‘torch::autograd::variable_list torch::autograd::CppNode<T>::apply(torch::autograd::variable_list&&) [with T = SegmentMeanCOO; torch::autograd::variable_list = std::vector<at::Tensor>]’:
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:284:15:   required from here
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:311:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  311 |   if (num_outputs > num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:323:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  323 |   if (num_outputs != num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:334:21: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
>  334 |   for (int i = 0; i < num_outputs; ++i) {
>      |                   ~~^~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h: In instantiation of ‘torch::autograd::variable_list torch::autograd::CppNode<T>::apply(torch::autograd::variable_list&&) [with T = SegmentSumCOO; torch::autograd::variable_list = std::vector<at::Tensor>]’:
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:284:15:   required from here
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:311:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  311 |   if (num_outputs > num_forward_inputs) {
>      |       ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
>/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/custom_function.h:323:19: warning: comparison of integer expressions of different signedness: ‘long unsigned int’ and ‘int’ [-Wsign-compare]
>  323 |   if (num_outputs != num_forward_inputs) {
</details>

Any thoughts on how to solve it?

**Comment by marcioluish** [comment]
All errors have indication of gcc's *-Wsign-compare*.
The best way to solve this issue is by disabling it?

How could I do that?

**Comment by rusty1s** [comment]
You should be able to remove these warnings via `-Wno-sign-compare`. Just pushed that change here: https://github.com/rusty1s/pytorch_scatter/commit/f844f33026e1f2f25775cf7f3fb27237f8265c0b.
