### ISSUE TITLE
TapasForQuestionAnswering requires the torch-scatter library but it was not found in your environment

### ISSUE THREAD

**Issue by PhaneendraGunda** [rusty1s/pytorch_scatter#254]
Hi,

I am getting the **torch_scatter** import error while loading tapas-base model through huggingface library.

**environment**:

1. transformers -> 4.13.0.dev0
2. torch -> 1.10.0+cu111
3. torch_scatter -> 2.0.9

Installed torch_scatter through `!pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu113.html`

```
ImportError                               Traceback (most recent call last)
<ipython-input-60-e5b1eae35fa5> in <module>()
      1 from transformers import TapasForQuestionAnswering
      2 
----> 3 model = TapasForQuestionAnswering.from_pretrained("google/tapas-base")
      4 device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
      5 

1 frames
/usr/local/lib/python3.7/dist-packages/transformers/file_utils.py in requires_backends(obj, backends)
    701     name = obj.__name__ if hasattr(obj, "__name__") else obj.__class__.__name__
    702     if not all(BACKENDS_MAPPING[backend][0]() for backend in backends):
--> 703         raise ImportError("".join([BACKENDS_MAPPING[backend][1].format(name) for backend in backends]))
    704 
    705 

ImportError: 
TapasForQuestionAnswering requires the torch-scatter library but it was not found in your environment. You can install it with pip as
explained here: https://github.com/rusty1s/pytorch_scatter.

```

**Comment by rusty1s** [comment]
Can you check if `import torch_scatter` works for you?

**Comment by PhaneendraGunda** [comment]
It's working fine after restarting the Colab runtime. Thank you for your prompt response.

**Comment by hitz02** [comment]
How can we make this work in requirements.txt?

I have added torch and torch scatter both, but it requires torch to be installed first.

PS: I am using HuggingFace Spaces to create an application for TAPAS-QA

**Comment by rusty1s** [comment]
You need to install from wheel to allow that `torch` and `torch-scatter` can be installed simultaneously, e.g., via
```
https://download.pytorch.org/whl/cpu/torch-1.9.0%2Bcpu-cp38-cp38-linux_x86_64.whl
https://data.pyg.org/whl/torch-1.9.0%2Bcpu/torch_scatter-2.0.7-cp38-cp38-linux_x86_64.whl
```
(see [here](https://github.com/pyg-team/pytorch_geometric/blob/master/docs/requirements.txt)) or
```
-f https://download.pytorch.org/whl/cu113/torch_stable.html
-f https://data.pyg.org/whl/torch-1.10.0+cu113.html
torch==1.10.0+cu113
torch-scatter
```

**Comment by hitz02** [comment]
Thanks for your response @rusty1s 

I tried the latter approach and it worked
