### ISSUE TITLE
Parameters of CUDA scatter_kernel

### ISSUE THREAD

**Issue by tekdogan** [rusty1s/pytorch_scatter#255]
In the `scatter_cuda` function of `scatter_cuda.cu`,

I'm trying to contemplate the calculated values of `B`,  `E`, `K` and `N`.

```c++
  auto B = 1;
  for (auto i = 0; i < dim; i++)
    B *= src.size(i);
  auto E = src.size(dim);
  auto K = src.numel() / (B * E);
  auto N = out.size(dim);
```

So I want to illustrate each value on a simple scenario:

`src` : feature values in shape [number of nodes x number of feature size]
`index` : `edge_index` variable in shape [number of edges x 2]
`dim` : dimension of source feature tensor, equivalent of `src.dim()` _(not sure about this part)_

As I see so far;

- `B` is the multiplication of each dimension size for source feature values tensor (`x` in most tutorials). it is _number of nodes x number of feature size_ in our case.
- `E` is the last dimension of source feature values tensor. _(not sure about this part)_
- `K` is the number of elements in feature vector over `(B*E)`. no of elements is _number of nodes x number of feature size_ in our case.
- `N` is the last dimension of output feature vector.

What I don't get here is `K` cannot be an integer due to my calculations above. I am probably assuming one or more concepts wrong. Can you please explain these parameters based on a simple scenario?

Thank you!

**Comment by rusty1s** [comment]
`torch_scatter.scatter` actually supports arbitrary tensor shapes, e.g., `[dim_1, dim_2, dim_3, ..., dim_N]`, and `B` and `K` just represent the number of elements before and after dimension `dim`:

* `B`: The multiplication of each dimension less than `dim`
* `E`: The size in dimension `dim`
* `N`: The output size in dimension `dim`
* `K`: The multiplication of each dimension higher than `dim`

**Comment by tekdogan** [comment]
Thank you for your quick and explanatory answer! I'm closing the issue.
