### ISSUE TITLE
Standalone usage of atomics

### ISSUE THREAD

**Issue by tekdogan** [rusty1s/pytorch_scatter#258]
I'm trying to compile _atomics.cuh_ via nvcc compiler but having a lot of errors. I've took a look at CMake file but could not grasp the related part for _atomics.cuh_.

What I do for compiling is:

`nvcc -g --cudart shared -lcublas_static -lculibos -ldl -lpthread -lcudart -lcudadevrt -rdc=true -std=c++11 -gencode arch=compute_61,code=compute_61 scatter_cuda.cu`

Do you have any suggestion (such as importing libraries and/or passing some command line arguments) so that I become able to compile and use the atomics' utilities in a standalone manner?

**Comment by rusty1s** [comment]
This is the command that `pyhon setup.py install` produces. Hopefully, it is helpful to you:
```
nvcc -DWITH_CUDA -Icsrc -I/home/matthias/miniconda3/lib/python3.9/site-packages/torch/include -I/home/matthias/miniconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/matthias/miniconda3/lib/python3.9/site-packages/torch/include/TH -I/home/matthias/miniconda3/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/matthias/miniconda3/include/python3.9 -c csrc/cuda/scatter_cuda.cu -o build/temp.linux-x86_64-3.9/csrc/cuda/scatter_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' --expt-relaxed-constexpr -O2 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
```

**Comment by tekdogan** [comment]
Seems like I've trouble with the following parts:
- **system architecture:** `nvcc fatal   : Unsupported gpu architecture 'compute_75'` so I use `compute_61` instead
- **c++ version:** `nvcc warning : The -std=c++14 flag is not supported with the configured host compiler. Flag will be ignored.`. Because of some restrictions, I cannot use a newer version than that of CUDA toolkit 9.2.

Is there a way around for me to get through these problems without making changes in architecture and/or nvcc version? If there isn't, I am going to close the thread.

Thank you for your help, Matthias!

**Comment by tekdogan** [comment]
It reverts back to where I started; gives hundreds of syntax errors that I believe those are related to C++14-specific expressions.

**Comment by rusty1s** [comment]
Might also depend on your PyTorch version. Which version are you using?

**Comment by tekdogan** [comment]
Actually what I am trying to do is somehow purge the utility from PyTorch dependency. After your remind, I checked the code again and saw some ATen-specific expressions such as `at::Half`.

Seems like there is no way out to compile and use it without depending on torch utilities, right?

**Comment by rusty1s** [comment]
Yes, our code tightly depends on PyTorch, I'm sorry for that :) It should be nonetheless possible to decouple `atomics.cuh` from the PyTorch dependency. All you need to do is drop all half-precision functions, i.e. the ones that make use of `at::Half`.

**Comment by tekdogan** [comment]
I'm going to work on it. Thank you for your help!
