### ISSUE TITLE
undefined symbol: _ZNK2at6Tensor6narrowElll

### ISSUE THREAD

**Issue by Nightmare-n** [rusty1s/pytorch_scatter#259]
env: pytorch:1.9.1-cuda11.1
command: pip install --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.9.1+cu111.html
error: ~/.local/lib/python3.7/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK2at6Tensor6narrowElll

**Comment by rusty1s** [comment]
Can you say more about how you installed PyTorch and what's your local CUDA version (`nvcc --version`)?

**Comment by Nightmare-n** [comment]
We find the pytorch version in the image is 1.10.0.

**Comment by rusty1s** [comment]
Hopefully,
```
pip install --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu111.html
```
then works for you :)

**Comment by Nightmare-n** [comment]
Yes, it works, thanks.
