### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zjhthu** [rusty1s/pytorch_scatter#260]
Env: pytorch 1.8.0a0+1606899, CUDA version, 11.1.  NVIDIA-Docker nvcr.io/nvidia/pytorch:20.12-py3  was used.
Installing cmd: `pip3 install --no-cache-dir --no-index  torch-scatter -f https://data.pyg.org/whl/torch-1.8.0+cu111.html`
Error when `import torch_scatter`: `OSError: /opt/conda/lib/python3.8/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c106detail12infer_schema20make_function_schemaENS_8ArrayRefINS1_11ArgumentDefEEES4_`

**Comment by zjhthu** [comment]
Also, when I tried to build from source, I encountered `csrc/cuda/segment_coo_cuda.cu(217): error: no instance of overloaded function "at::Tensor::div_" matches the argument list
    argument types are: (at::Tensor, const char [6])
    object type is: at::Tensor`

**Comment by rusty1s** [comment]
Can you do me a favour and see if
```
pip3 uninstall torch-scatter
pip3 uninstall torch-scatter
pip3 install --no-cache-dir --verbose torch-scatter==2.0.8
```
works for you?

**Comment by zjhthu** [comment]
Yes, It works! But why ...

**Comment by zjhthu** [comment]
But when I built it in Docker, I encountered  
`File "/opt/conda/lib/python3.8/site-packages/torch_scatter/__init__.py", line 17, `
`in <module> raise AttributeError(e)` 
`AttributeError: 'NoneType' object has no attribute 'origin'`

which is the same as [issue 206](https://github.com/rusty1s/pytorch_scatter/issues/206) and [issue 216](https://github.com/rusty1s/pytorch_scatter/issues/216)

**Comment by rusty1s** [comment]
You may need to specify `CUDA_ARCH_LIST` in a docker container when installing from source, see [here](https://github.com/rusty1s/pytorch_scatter#from-source).

**Comment by zjhthu** [comment]
it still the same error, my dockerfile now is 
```
FROM nvcr.io/nvidia/pytorch:20.12-py3
ARG DEBIAN_FRONTEND=noninteractive
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.2+PTX 7.5+PTX"
RUN pip3 install --no-cache-dir --verbose torch-scatter==2.0.8
CMD /bin/bash
```

**Comment by rusty1s** [comment]
Can you show me the installation log of
```
RUN pip3 install --no-cache-dir --verbose torch-scatter==2.0.8
```

**Comment by zjhthu** [comment]
[here](https://github.com/rusty1s/pytorch_scatter/files/7799084/docker_build.txt) is the log.

**Comment by rusty1s** [comment]
```
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  ../c10/cuda/CUDAFunctions.cpp:100.)
```
This should explain the problem.

**Comment by zjhthu** [comment]
but actually, I have installed NVIDIA driver, `NVIDIA-SMI 460.84       Driver Version: 460.84       CUDA Version: 11.2 `, this is the results when I run nvidia-smi

**Comment by rusty1s** [comment]
Super weird. Is it possible that `docker` does not have access to this driver during installation?

**Comment by zjhthu** [comment]
I have no idea. Everything is ok if I build torch_scatter in a running docker rather than from Dockerfile, as also pointed by this [issue](https://github.com/rusty1s/pytorch_scatter/issues/206).

**Comment by rusty1s** [comment]
Sorry for the late reply.

I'm not sure whether the linked issue is related, as the user wants to install on a no-GPU machine and deploy it on a GPU machine.

I'm sadly no expert on docker, but there might be some weird interplay between docker and PyTorch that restricts PyTorch from finding a proper GPU. I'm afraid this is out of my hands :(

On a last chance: What happens if you run via `RUN FORCE_CUDA=1 pip3 install --no-cache-dir --verbose torch-scatter==2.0.8`?

**Comment by zjhthu** [comment]
It works! Thanks a lot
