### ISSUE TITLE
scatter_histogram?

### ISSUE THREAD

**Issue by aur3l14no** [rusty1s/pytorch_scatter#261]
Thanks a lot for your work.

I'm wondering would `scatter_histogram` be straightforward to implement?

**Comment by rusty1s** [comment]
Can you say something about the expected inputs and outputs of the function? I'm unsure what this actually means. Doesn't `scatter_add` already produce some kind of histogram?

**Comment by aur3l14no** [comment]
I meant something like `TORCH.HISTOGRAM`, but instead it calculates histograms for groups of indexes separately.

However on a second thought, such an operator cannot be differentiable and might not be appropriate here.
