### ISSUE TITLE
torch_scatter with Pytorch nighty

### ISSUE THREAD

**Issue by harshithapv** [rusty1s/pytorch_scatter#264]
I am trying to use torch_scatter with torch nightly from source. I compiled torch_scatter from source as follows : 
1. git clone https://github.com/rusty1s/pytorch_scatter.git
2. cd pytorch_scatter
3. export PATH=$PATH:/usr/local/cuda/bin
4. export CPATH=/usr/local/cuda/include
5. python3.8 setup.py install
pytorch_scatter successfully installs but when I use it in the model I see the following error:

> 
> Traceback (most recent call last):
>   File "/opt/user/model.py", line 5, in <module>
>     import torch_scatter
>   File "/usr/local/lib/python3.8/dist-packages/torch_scatter/__init__.py", line 16, in <module>
>     torch.ops.load_library(spec.origin)
>   File "/usr/local/lib/python3.8/dist-packages/torch/_ops.py", line 110, in load_library
>     ctypes.CDLL(path)
>   File "/usr/lib/python3.8/ctypes/__init__.py", line 369, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /usr/local/lib/python3.8/dist-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by rusty1s** [comment]
Thanks for reporting. IMO, you should check for two things:
1. Make sure that you do not have any other versions of `torch-scatter` installed (e.g., via `pip` or `conda`).
2. Make sure that `torch.cuda.version` and `nvcc --version` matches.

**Comment by harshithapv** [comment]
Thank you. I have verified both. 
No other versions of torch_scatter.
nvcc --version and torch.version.cuda are the same:
>>> torch.version.cuda
'10.2'
>>> exit()
controllers# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by rusty1s** [comment]
Thanks for confirming. This is weird :) Can you also post the log of
```
pip uninstall torch-scatter
pip uninstall torch-scatter
python3.8 setup.py install
```

**Comment by harshithapv** [comment]
I was able to fix this by using pip install torch_scatter. It takes a long time to build, but worked.
