### ISSUE TITLE
[scatter_max] RuntimeError: Not compiled with CUDA support (torch 1.10.0+cu102, torch_scatter 2.0.9, Ubuntu 20.02)

### ISSUE THREAD

**Issue by HiddenBeginner** [rusty1s/pytorch_scatter#271]
Dear authors,

Hi, I am a new user working with point cloud datasets.
`torch_scatter` is really useful for handling a set of point cloud datasets of different sizes. Thank you!

I am getting trouble using `scatter_max` and `scatter_softmax` on my GPU. The spec of my environment is as follows:
- Ubuntu 20.02
- torch 1.10.2
- torch_scatter 2.0.9
- cuda 10.2
(I am not used to writing issues, if you need more information, please let me know)

Every operation is performed successfully on the CPU, but the `scatter_max` operation yields the following error

I'd like to ask if there's anything I've missed. Thank you in advance.

~~~python
import torch
import torch_scatter

from torch_scatter import scatter, scatter_max, scatter_softmax 
print(torch.__version__)
print(torch_scatter.__version__)

x = torch.tensor([[1.], [2.], [3.], [4.]], dtype=torch.float32, device='cuda')
out = torch.empty((2, 1), dtype=torch.float32, device='cuda')
index = torch.tensor([0, 0, 1, 1], device='cuda')

ret1 = scatter(x, index, dim=0, dim_size=2, reduce='add')
print(ret1)

ret2 = scatter_max(x, index, dim=0, dim_size=2, out=out)
~~~

Output:
~~~
1.10.0+cu102
2.0.9
tensor([[3.],
        [7.]], device='cuda:0')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-765af5fc8bdf> in <module>
     13 print(ret1)
     14 
---> 15 ret2 = scatter_max(x, index, dim=0, dim_size=2, out=out)

~/anaconda3/envs/my-project/lib/python3.7/site-packages/torch_scatter/scatter.py in scatter_max(src, index, dim, out, dim_size)
     70         out: Optional[torch.Tensor] = None,
     71         dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
---> 72     return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
     73 
     74 

RuntimeError: Not compiled with CUDA support
~~~

**Comment by rusty1s** [comment]
How did you try to install `torch-scatter`? It looks like you only installed the CPU version of it.

**Comment by HiddenBeginner** [comment]
I remembered that `torch_scatter` was installed when I installed `torch_geometric`.

I reinstalled `torch_scatter` by the following command and everything is okay now.

~~~
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.0+cu102.html
~~~

Thank you so much !!!!!

**Comment by dearhannah** [comment]
Hello! I met the same problem and I tried to reinstall `torch-scatter`. However, it still produce the error. I am using `CUDA 10.1 `and `torch 1.8.1`. So I used this command to install:
`pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.1+cu101.html`
According to the following message, I think I installed a GPU version. I don't know what else I can do now.
```
Looking in links: https://data.pyg.org/whl/torch-1.8.1+cu101.html
Collecting torch-scatter
  Using cached torch_scatter-2.0.9-cp38-cp38-linux_x86_64.whl
Installing collected packages: torch-scatter
Successfully installed torch-scatter-2.0.9
```
Thank you in advance!

**Comment by bokveizen** [comment]
> Hello! I met the same problem by running the same code and I tried to reinstall `torch-scatter`. However, it still produce the error. I am using `CUDA 10.1 `and `torch 1.8.1`. So I used this command to install: `pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.1+cu101.html` According to the following message, I think I installed a GPU version. I don't know what else I can do now.
> 
> ```
> Looking in links: https://data.pyg.org/whl/torch-1.8.1+cu101.html
> Collecting torch-scatter
>   Using cached torch_scatter-2.0.9-cp38-cp38-linux_x86_64.whl
> Installing collected packages: torch-scatter
> Successfully installed torch-scatter-2.0.9
> ```
> 
> Thank you in advance!

For people who meet similar problems, it is because the installed version has a higher version than the available ones in the link. Specifically, in https://data.pyg.org/whl/torch-1.8.1+cu101.html, you can only have torch_scatter==2.0.8. Hence, you should do
`pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu101.html`
