### ISSUE TITLE
the same error like #239       Building C++ API from source failed

### ISSUE THREAD

**Issue by 2017ND** [rusty1s/pytorch_scatter#273]
[#239](https://github.com/rusty1s/pytorch_scatter/issues/239)

I use libtorch1.8.0-cuda102 RTX6000  cuda102， and when I try to build pytorch_scatter2.0.8 from source I hit this error, (however  I build  pytorch_scatter2.0.6 from source sucessfully):
cmake .. -DWITH_CUDA=ON
make -j20
[  9%] Building CXX object CMakeFiles/torchscatter.dir/csrc/cpu/segment_coo_cpu.cpp.o
[ 18%] Building CXX object CMakeFiles/torchscatter.dir/csrc/cpu/scatter_cpu.cpp.o
[ 36%] Building CXX object CMakeFiles/torchscatter.dir/csrc/cpu/segment_csr_cpu.cpp.o
[ 36%] Building CUDA object CMakeFiles/torchscatter.dir/csrc/cuda/segment_csr_cuda.cu.o
[ 45%] Building CXX object CMakeFiles/torchscatter.dir/csrc/version.cpp.o
[ 54%] Building CUDA object CMakeFiles/torchscatter.dir/csrc/cuda/segment_coo_cuda.cu.o
[ 63%] Building CUDA object CMakeFiles/torchscatter.dir/csrc/cuda/scatter_cuda.cu.o
[ 72%] Building CXX object CMakeFiles/torchscatter.dir/csrc/scatter.cpp.o
[ 90%] Building CXX object CMakeFiles/torchscatter.dir/csrc/segment_coo.cpp.o
[ 90%] Building CXX object CMakeFiles/torchscatter.dir/csrc/segment_csr.cpp.o
/data/workspace/niujw/1-code/Cylinder3D-folder/torch_scatter/pytorch_scatter/csrc/cuda/utils.cuh(12): error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
            function "__half::__half(__half &&)"

/data/workspace/niujw/1-code/Cylinder3D-folder/torch_scatter/pytorch_scatter/csrc/cuda/utils.cuh(18): error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
            function "__half::__half(__half &&)"

/data/workspace/niujw/1-code/Cylinder3D-folder/torch_scatter/pytorch_scatter/csrc/cuda/utils.cuh(12): error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
            function "__half::__half(__half &&)"

/data/workspace/niujw/1-code/Cylinder3D-folder/torch_scatter/pytorch_scatter/csrc/cuda/utils.cuh(18): error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
            function "__half::__half(__half &&)"

/data/workspace/niujw/1-code/Cylinder3D-folder/torch_scatter/pytorch_scatter/csrc/cuda/utils.cuh(12): error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
            function "__half::__half(__half &&)"

/data/workspace/niujw/1-code/Cylinder3D-folder/torch_scatter/pytorch_scatter/csrc/cuda/utils.cuh(18): error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
            function "__half::__half(__half &&)"

2 errors detected in the compilation of "/tmp/tmpxft_00004c6c_00000000-6_segment_coo_cuda.cpp1.ii".
CMakeFiles/torchscatter.dir/build.make:131: recipe for target 'CMakeFiles/torchscatter.dir/csrc/cuda/segment_coo_cuda.cu.o' failed
make[2]: *** [CMakeFiles/torchscatter.dir/csrc/cuda/segment_coo_cuda.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
2 errors detected in the compilation of "/tmp/tmpxft_00004c6d_00000000-6_segment_csr_cuda.cpp1.ii".
CMakeFiles/torchscatter.dir/build.make:145: recipe for target 'CMakeFiles/torchscatter.dir/csrc/cuda/segment_csr_cuda.cu.o' failed
make[2]: *** [CMakeFiles/torchscatter.dir/csrc/cuda/segment_csr_cuda.cu.o] Error 1
2 errors detected in the compilation of "/tmp/tmpxft_00004c6f_00000000-6_scatter_cuda.cpp1.ii".
CMakeFiles/torchscatter.dir/build.make:117: recipe for target 'CMakeFiles/torchscatter.dir/csrc/cuda/scatter_cuda.cu.o' failed
make[2]: *** [CMakeFiles/torchscatter.dir/csrc/cuda/scatter_cuda.cu.o] Error 1
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/torchscatter.dir/all' failed
make[1]: *** [CMakeFiles/torchscatter.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rusty1s** [comment]
I believe you will need to use PyTorch > 1.8.0 to install the latest `torch-scatter` that introduced half-precision support. Can you try if upgrading to PyTorch 1.9 fixes the issues for you?

**Comment by 2017ND** [comment]
thanks, i will try.
