### ISSUE TITLE
OSError: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

### ISSUE THREAD

**Issue by shivance** [rusty1s/pytorch_scatter#275]
I am trying to install torch_scatter but it is gives this error
```
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anshuman/anaconda3/envs/Py38/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/anshuman/anaconda3/envs/Py38/lib/python3.8/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/anshuman/anaconda3/envs/Py38/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/anshuman/anaconda3/envs/Py38/lib/python3.8/site-packages/torch_scatter/_scatter_cpu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
```

My guess is it has something to do with cudatoolkit. But I have it installed

**Comment by rusty1s** [comment]
Please share more information about how you installed PyTorch (`torch.__version__` and `torch.cuda.version`) and `torch-scatter`. Please share any information logs of running `pip install --verbose torch-scatter -f ...` as well.

**Comment by shivance** [comment]
Hey @rusty1s , turns out that <a href="https://github.com/stan-dev/pystan/issues/294">this</a> issue solved my problem.
It occurred because of missmatch in c-compiler and cxx-compiler version of anaconda and system.

Thanks for reply though.

**Comment by lonngxiang** [comment]
same error;torch__version__   is 1.12.1,torch-scatter is 2.0.9
