### ISSUE TITLE
Any method to stack all the tensors located in the same region?

### ISSUE THREAD

**Issue by MyNiuuu** [rusty1s/pytorch_scatter#285]
Thanks for the brilliant project! I am looking for a method to collect and stack all the tensors located in the same region instead of calculating the sum/mean of them. Does pytorch_scatter have this functionality?

**Comment by rusty1s** [comment]
Can you take a look at `torch_geometric.utils.to_dense_batch` from PyG? This might be what you are looking for (but expects sorted indices).
