### ISSUE TITLE
install fails for torch==1.8.1 and cuda 10.2

### ISSUE THREAD

**Issue by elias-ramzi** [rusty1s/pytorch_scatter#286]
Hi,

Thank you for the great repo !

I tried installing the latest version of `torch-scatter` using:
```
pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-1.8.1+cu102.html
```
But torch-scatter was compiled with the wrong version of cuda (it uses the version on the server instead of the conda version of cuda).

It work for `torch-scatter==2.0.8`, ie:
```
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu102.html
```

Is it easily fixable ?

Thank you for any help !

**Comment by rusty1s** [comment]
Thanks for the issue. Note that `torch-scatter==2.0.8` is the last supported version for PyTorch 1.8. You can see that by looking at https://data.pyg.org/whl/torch-1.8.1+cu102.html directly. As such,
```
pip install torch-scatter==2.0.8 -f https://data.pyg.org/whl/torch-1.8.1+cu102.html
```
is the recommended way to install `torch-scatter` for PyTorch 1.8. It is safe to us as well :)

**Comment by elias-ramzi** [comment]
Hi,
Thanks for the response I didn’t see it was the last supported version for torch 1.8!
