### ISSUE TITLE
Add reduce=argmin/argmax

### ISSUE THREAD

**Issue by byphilipp** [rusty1s/pytorch_scatter#287]
![image](https://user-images.githubusercontent.com/59995258/164412770-b4d46e7a-ea24-4b73-951b-fc1ebb8de429.png)

**Comment by byphilipp** [comment]
torch_scatter.scatter_min and torch_scatter.scatter_max may be used

**Comment by chenzhekl** [comment]
Hi @byphilipp, I am having the same need. Would you mind sharing how you solved this problem?
