### ISSUE TITLE
Scatter without reduce

### ISSUE THREAD

**Issue by talha1503** [rusty1s/pytorch_scatter#289]
Hi there! I wanted to use scatter, without reducing for any operation. Is there any way in which we can use pytorch_scatter to achieve the same?

For Example:
src: [374,200]
index: [374]
out: [22, 27, 200]

Here, my index tensor will be [0,0,0,0,0,0, 1,1,1,1,1,1,1,1, 2,2,2,2, ... 21, 21,21] . So I wanted to copy elements from src tensor from 0th dimension into output tensor such that, from index tensor.

Currently, I am doing it in this way: 

```
max_node_val = torch.mode(batch, dim = 0).indices.item()
bincount = torch.bincount(batch)
output = list(torch.split(x, list(bincount), 0))
final_tensor = torch.cat([torch.cat([x,torch.zeros(max_node_val-x.size(0), 200)]).unsqueeze(0) for x in output], dim = 0)
```

Could you please help me out?

**Comment by rusty1s** [comment]
I think this is supported by [`torch_geometric.utils.to_dense_batch`](https://pytorch-geometric.readthedocs.io/en/latest/modules/utils.html#torch_geometric.utils.to_dense_batch). Let me know if that works for you!

**Comment by talha1503** [comment]
Thank you so much! Will try this out :D
