### ISSUE TITLE
A failure in running `python setup.py test` at cuda 10

### ISSUE THREAD

**Issue by J0hnLee** [rusty1s/pytorch_scatter#29]
`python setup.py test`

_____________________________________ test_std[dtype2-device2-True] _____________________________________

dtype = torch.float32, device = device(type='cuda', index=0), bias = True

    @pytest.mark.parametrize('dtype,device,bias', product(dtypes, devices, biass))
    def test_std(dtype, device, bias):
        src = tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]], dtype, device)
        index = tensor([[0, 0, 0, 0, 0], [1, 1, 1, 1, 1]], torch.long, device)
    
        out = scatter_std(src, index, dim=-1, unbiased=bias)
        std = src.std(dim=-1, unbiased=bias)[0].item()
        expected = torch.tensor([[std, 0], [0, std]], dtype=out.dtype)
>       assert torch.allclose(out, expected)
E       RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

test/test_std.py:20: RuntimeError
____________________________________ test_std[dtype3-device3-False] _____________________________________

dtype = torch.float32, device = device(type='cuda', index=0), bias = False

    @pytest.mark.parametrize('dtype,device,bias', product(dtypes, devices, biass))
    def test_std(dtype, device, bias):
        src = tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]], dtype, device)
        index = tensor([[0, 0, 0, 0, 0], [1, 1, 1, 1, 1]], torch.long, device)
    
        out = scatter_std(src, index, dim=-1, unbiased=bias)
        std = src.std(dim=-1, unbiased=bias)[0].item()
        expected = torch.tensor([[std, 0], [0, std]], dtype=out.dtype)
>       assert torch.allclose(out, expected)
E       RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor

test/test_std.py:20: RuntimeError
___________________________________ test_std[dtype7-device7-False] _____________________________________

dtype = torch.float64, device = device(type='cuda', index=0), bias = False

    @pytest.mark.parametrize('dtype,device,bias', product(dtypes, devices, biass))
    def test_std(dtype, device, bias):
        src = tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]], dtype, device)
        index = tensor([[0, 0, 0, 0, 0], [1, 1, 1, 1, 1]], torch.long, device)
    
        out = scatter_std(src, index, dim=-1, unbiased=bias)
        std = src.std(dim=-1, unbiased=bias)[0].item()
        expected = torch.tensor([[std, 0], [0, std]], dtype=out.dtype)
>       assert torch.allclose(out, expected)
E       RuntimeError: expected type torch.cuda.DoubleTensor but got torch.DoubleTensor

test/test_std.py:20: RuntimeError

----------- coverage: platform linux, python 3.6.7-final-0 -----------
Name                              Stmts   Miss  Cover
-----------------------------------------------------
torch_scatter/__init__.py            10      0   100%
torch_scatter/add.py                  4      0   100%
torch_scatter/div.py                 14      0   100%
torch_scatter/max.py                 15      0   100%
torch_scatter/mean.py                 6      0   100%
torch_scatter/min.py                 15      0   100%
torch_scatter/mul.py                 14      0   100%
torch_scatter/std.py                 14      0   100%
torch_scatter/sub.py                  3      0   100%
torch_scatter/utils/__init__.py       0      0   100%
torch_scatter/utils/ext.py            5      0   100%
torch_scatter/utils/gen.py           13      0   100%
-----------------------------------------------------
TOTAL                               113      0   100%

================================= 4 failed, 191 passed in 3.76 seconds ==================================

**Comment by rusty1s** [comment]
Thanks! Fixed in master.
