### ISSUE TITLE
Fail installation. 

### ISSUE THREAD

**Issue by TonyPeng-2018** [rusty1s/pytorch_scatter#291]
Hello, here is the error I met. pytorch 1.5.1, python3.7.12
command: pip install torch-scatter==2.0.5 

Running setup.py install for torch-scatter did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.7
      creating build\lib.win-amd64-3.7\torch_scatter
      copying torch_scatter\placeholder.py -> build\lib.win-amd64-3.7\torch_scatter
      copying torch_scatter\scatter.py -> build\lib.win-amd64-3.7\torch_scatter
      copying torch_scatter\segment_coo.py -> build\lib.win-amd64-3.7\torch_scatter
      copying torch_scatter\segment_csr.py -> build\lib.win-amd64-3.7\torch_scatter
      copying torch_scatter\utils.py -> build\lib.win-amd64-3.7\torch_scatter
      copying torch_scatter\__init__.py -> build\lib.win-amd64-3.7\torch_scatter
      creating build\lib.win-amd64-3.7\torch_scatter\composite
      copying torch_scatter\composite\logsumexp.py -> build\lib.win-amd64-3.7\torch_scatter\composite
      copying torch_scatter\composite\softmax.py -> build\lib.win-amd64-3.7\torch_scatter\composite
      copying torch_scatter\composite\std.py -> build\lib.win-amd64-3.7\torch_scatter\composite
      copying torch_scatter\composite\__init__.py -> build\lib.win-amd64-3.7\torch_scatter\composite
      running build_ext
     (dir)\anaconda3\envs\cuda10_2python3_7\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
      creating build\temp.win-amd64-3.7
      creating build\temp.win-amd64-3.7\Release
      creating build\temp.win-amd64-3.7\Release\Users
      creating build\temp.win-amd64-3.7\Release\Users\(dir)
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local\Temp
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local\Temp\pip-install-edrecxqb
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local\Temp\pip-install-edrecxqb\torch-scatter_306a620853db4e288bf13c164f4c500f
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local\Temp\pip-install-edrecxqb\torch-scatter_306a620853db4e288bf13c164f4c500f\csrc
      creating build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local\Temp\pip-install-edrecxqb\torch-scatter_306a620853db4e288bf13c164f4c500f\csrc\cpu
      error: could not create 'build\temp.win-amd64-3.7\Release\Users\(dir)\AppData\Local\Temp\pip-install-edrecxqb\torch-scatter_306a620853db4e288bf13c164f4c500f\csrc\cpu': The filename or extension is too long
      Error in atexit._run_exitfuncs:
      Traceback (most recent call last):
        File "C:\Users\(dir)\anaconda3\envs\cuda10_2python3_7\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
          return stream.closed
      ValueError: underlying buffer has been detached
      [end of output]

Thank you.

**Comment by TonyPeng-2018** [comment]
Fixed by command: pip install torch-scatter==2.0.5 -f https://pytorch-geometric.com/whl/torch-1.5.0%2Bcu102.html

**Comment by rusty1s** [comment]
Super :)
