### ISSUE TITLE
question about the installation problem

### ISSUE THREAD

**Issue by shaoniana1997** [rusty1s/pytorch_scatter#293]
Hello,i am trying to install pytorch_scatter and i have one problem. Specifically,i don't know which cuda version that i should choose!
The cuda version in nvidia-smi is 11.0,
The cuda version in cat /usr/local/cuda/version.txt and nvcc-V is 10.0.130
And when i trying to install pytorch_scatter, can you tell me which cuda version that i should choose???????

**Comment by rusty1s** [comment]
You should use the one from PyTorch:
```python
import torch
print(torch.cuda.version)
```

**Comment by shaoniana1997** [comment]
ok,thank you for you nice help! I will try that!
