### ISSUE TITLE
FileNotFoundError: Could not find module .... _scatter_cuda.pyd (or one of its dependencies)

### ISSUE THREAD

**Issue by Cbezz** [rusty1s/pytorch_scatter#296]
Hi,

I recently installed pytorch_scatter on torch 1.11.0 (torch-vision 0.12.0), cuda 11.3, using pip (on windows).
When I try and run code from another repository (https://github.com/xmlyqing00/AFB-URR) where pytorch-scatter is a dependency I get the error mentioned in the title.

Have I done something wrong? Has this error happened to anyone else?
Thanks

**Comment by Cbezz** [comment]
I'm not sure how but I somehow had the cpu version of pytorch installed

**Comment by imk-asyk** [comment]
@rusty1s same problem (downloaded from conda-forge, cpu-only)

**Comment by imk-asyk** [comment]
@Cbezz Try installing visual C++ 14.0+? It seems to be missing some dependent DLLs of the .pyd file without that
