### ISSUE TITLE
Memory efficient version of scatter operations 

### ISSUE THREAD

**Issue by berkekisin** [rusty1s/pytorch_scatter#297]
Hello!
Current implementation of scatter operations requires an index in source tensor for each value that will be scattered and updates the corresponding index in result tensor with atomic operations so there is one thread  for each index of source Tensor.
Suppose we have a source tensor "x" , two tensors "edge_start" and "edge_end". If we want to use scatter operations for message passing we have to compute the intermediate tensor "x[edge_start]". This computation is memory  and runtime inefficient since the tensor  "x[edge_start]" only needed for one iteration of message passing. 

In our research we had a memory bottleneck from scatter operations as we tried to process some coloring benchmark instances therefore
we developed a new implementation of scatter operations which parallelizes the threads along edges and avoids the computation "x[edge_start]". The code is available in my GitHub profile.
Link of repo: [https://github.com/berkekisin/Pytorch_scatter_edge](url)
With the help of this implementation the training of our model is 20% faster and we can also process big benchmark instances.
Note that the current implementation only includes scatter_max but we used your reducer  and code structure, for that reason its easy to add other reduction types and merge this in Torch Scatter.
We would like to contribute this extension to Torch Scatter library to make it accessible to the wider
Graph Learning community.

**Comment by rusty1s** [comment]
Thanks for sharing, very interesting. As far as I can tell, this is somewhat related to a generalized sparse matrix multiplication in COO format (PyG and `torch-sparse` supports this via CSR layout, see [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html)). I am happy to accept a PR on this one though, although this is probably better place in `torch-sparse` and marked as sparse-matrix multiplication. WDYT?

**Comment by berkekisin** [comment]
I agree with you. How should we merge this, If it would be better or needed, we could also set up a call with you.

**Comment by berkekisin** [comment]
That sounds good, I also think this fits better in torch sparse. I forked torch sparse and would now create a new file called spmm_coo.py and put my function there, I hope this is the right way to do it. I suggest we first put this in torch sparse before [pyg-lib](https://github.com/pyg-team/pyg-lib), we can move it to pyg-lib after that too.
