### ISSUE TITLE
Undefined symbol error

### ISSUE THREAD

**Issue by shiwentao00** [rusty1s/pytorch_scatter#30]
Hi there, 

Everything is fine with the installation process(I'm using gcc 4.9). The 'undefined symbol' run-time error occurred when I trying to run an example program. I tried all the methods mentioned in those threads and the methods in the installation guide (cleaning pip cache, reinstalling packages), I still got this error:

`Traceback (most recent call last):
  File "py_geo_test.py", line 2, in <module>
    from torch_geometric.data import Data
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_geometric/data/data.py", line 2, in <module>
    from torch_geometric.utils import (contains_isolated_nodes,
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_geometric/utils/__init__.py", line 2, in <module>
    from .scatter import scatter_
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_geometric/utils/scatter.py", line 1, in <module>
    import torch_scatter
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /home/derick/.conda/envs/pytorch/lib/python3.6/site-packages/torch_scatter/scatter_cpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
`

**Comment by rusty1s** [comment]
Hi, Please post the log when installing from source.

**Comment by rusty1s** [comment]
Related: https://discuss.pytorch.org/t/undefined-symbol-when-import-lltm-cpp-extension/32627/4

**Comment by wentaoveggiebird** [comment]
@rusty1s Thanks for the reply. Where is that log file supposed to be?

**Comment by rusty1s** [comment]
Sorry, I misread that installation succeeds. Did you try to build the extension with `-D_GLIBCXX_USE_CXX11_ABI=1`?

**Comment by rkube** [comment]
I'd like to bump this issue.
Installed torch_scatter with "-D_GLIBCXX_USE_CXX_ABI=1" by setting extra_compile_args = ['-D_GLIBCXX_USE_CXX11_ABI=1'] in setup.py

It builds fine. When import it, I get the following error:
(ml) [rkube@adroit4 ~]$ ipython
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch                                                                                                                                                                                              
i
In [2]: import torch_scatter                                                                                                                                                                                      
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-d3a1bea51b5c> in <module>
----> 1 import torch_scatter

~/.local/lib/python3.7/site-packages/torch_scatter/__init__.py in <module>
      1 from .add import scatter_add
      2 from .sub import scatter_sub
----> 3 from .mul import scatter_mul
      4 from .div import scatter_div
      5 from .mean import scatter_mean

~/.local/lib/python3.7/site-packages/torch_scatter/mul.py in <module>
      1 from torch.autograd import Function
      2 
----> 3 from torch_scatter.utils.ext import get_func
      4 from torch_scatter.utils.gen import gen
      5 

~/.local/lib/python3.7/site-packages/torch_scatter/utils/ext.py in <module>
      1 import torch
----> 2 import torch_scatter.scatter_cpu
      3 
      4 if torch.cuda.is_available():
      5     import torch_scatter.scatter_cuda

ImportError: /home/rkube/.local/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs


(ml) [rkube@adroit4 torch_scatter-1.3.1]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168

(ml) [rkube@adroit4 torch_scatter-1.3.1]$ gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

**Comment by rkube** [comment]
I tracked the issue down to a compiler bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1546704
