### ISSUE TITLE
Issues installing with Cuda 11.2

### ISSUE THREAD

**Issue by J-Himes** [rusty1s/pytorch_scatter#302]
I'm currently trying to install with Cuda version 11.2, Python version 3.6, and PyTorch version 1.10.2, but "pip install torch-scatter" fails, it does so with cudatoolkit=11.3 and cudatoolkit=10.2. I was able to get things working on my personal laptop, the only difference being Cuda version 10.1 instead of 11.2. Is there a hard compatibility issue with this setup, or any known issues with 11.2 compatibility? I've attached a file with the output I received as well.

Thank you very much for any help, I really appreciate it.
[output.txt](https://github.com/rusty1s/pytorch_scatter/files/8932882/output.txt)

**Comment by rusty1s** [comment]
How did you try to install `torch-scatter`? Do you need to install from source? Otherwise, you should always install from wheels (via the `-f` option) for a smoother installation experience.

**Comment by J-Himes** [comment]
> How did you try to install `torch-scatter`? Do you need to install from source? Otherwise, you should always install from wheels (via the `-f` option) for a smoother installation experience.

I used "pip install torch-scatter", which is what worked for me when I installed it with cuda 10.1, but it didn't work with 11.2. How would I be able to install it with -f? Sorry, I'm not familiar with what command you're referring to.

**Comment by rusty1s** [comment]
Please try
```
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.2+cu113.html
```

**Comment by J-Himes** [comment]
> Please try
> 
> ```
> pip install torch-scatter -f https://data.pyg.org/whl/torch-1.10.2+cu113.html
> ```

That worked! Thank you so much! Saved me from so much stress, I really appreciate it, thank you.
