### ISSUE TITLE
'NoneType' object has no attribute 'origin'

### ISSUE THREAD

**Issue by bruno686** [rusty1s/pytorch_scatter#307]
hello, when I used torch_scatter, I suffered from this problem below.
`Traceback (most recent call last):
  File "/home/bruno/anaconda3/envs/tf/lib/python3.7/site-packages/torch_scatter/__init__.py", line 14, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bruno/文档/RGCN/main.py", line 7, in <module>
    from utils import load_data, generate_sampled_graph_and_labels, build_test_graph, calc_mrr
  File "/home/bruno/文档/RGCN/utils.py", line 7, in <module>
    from torch_scatter import scatter_add
  File "/home/bruno/anaconda3/envs/tf/lib/python3.7/site-packages/torch_scatter/__init__.py", line 17, in <module>
    raise AttributeError(e)
AttributeError: 'NoneType' object has no attribute 'origin'`

the packages version:
torch                                    1.7.1
torch-geometric             1.7.0
torch-scatter                    2.0.6
torch-sparse                     0.6.9

Thanks!

**Comment by rusty1s** [comment]
Can you share some insights on how to installed `torch-scatter`? It looks like there was an installation issue. You should be able to install it
```
pip install torch-scatter==2.0.6 -f https://data.pyg.org/whl/torch-1.7.1+cpu.html
```

**Comment by bruno686** [comment]
> 

I just install it by pip, pip install torch_scatter==2.06.

**Comment by bruno686** [comment]
I just install it by pip, pip install torch_scatter==2.0.6.

**Comment by bruno686** [comment]
I just install it by pip, pip install torch_scatter==2.0.6.

**Comment by bruno686** [comment]
I just install it by pip, pip install torch_scatter==2.0.6.
However, when I used your introduction, the problem still exists.

**Comment by rusty1s** [comment]
Can you first uninstall the package before re-installing? Can you show me the output log of installation?
