### ISSUE TITLE
Installation with recent conda wheels

### ISSUE THREAD

**Issue by jannisborn** [rusty1s/pytorch_scatter#309]
Thanks a lot @rusty1s for the great library and the timely updates!

The README states that `torch_scatter` can be installed with conda given that the user has a functional torch version >= 1.8. 

Our installation workflow relied on this, but since today our builds are failing. It looks like it's related to the recent release on the conda `pyg` channel.

This issue affects only installation on Linux.

Minimal working example:
```sh
conda create -n tmp  python=3.7 -y
conda activate tmp
pip3 install torch torchvision torchaudio #official torch installation instructions
python3 -c "import torch; print(torch.__version__)" # gives 1.12.0+cu102
conda install pytorch-scatter -c pyg #recommended in README
```

Afterwards, when importing `torch_scatter` I get:
```sh
  File "/home/ubuntu/miniconda3/envs/tmp/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_cuda.so: cannot open shared object file: No such file or directory
```

Notably, when installing torch_scatter via conda, torch gets **downgraded**:
```sh
The following NEW packages will be INSTALLED:
...
  pytorch            pkgs/main/linux-64::pytorch-1.10.2-cpu_py37hfa7516b_0
  pytorch-scatter    pyg/linux-64::pytorch-scatter-2.0.9-py37_torch_1.10.0_cu113
...
```
Here,  pytorch uses CPU wheels but torch_scatter is looking for cuda wheels...

Debugging machine:
```sh
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

Any idea of what is going on here @rusty1s ?

**Comment by rusty1s** [comment]
Yes, we are currently in the process of upgrading to PyTorch 1.12 (just got released yesterday).

**Comment by jannisborn** [comment]
Thanks! Sorry, I thought the upgrade was completed since the PR was merged and I also saw an update on the anaconda site.

How do we find out when it will be possible to install `torch-scatter` via conda for torch==1.12?

**Comment by jannisborn** [comment]
The problem persists. It's still downgrading torch to `1.10.2-cpu`:
```sh
  pytorch            pkgs/main/linux-64::pytorch-1.10.2-cpu_py37hfa7516b_0
  pytorch-scatter    pyg/linux-64::pytorch-scatter-2.0.9-py37_torch_1.10.0_cu102
```

and then the import fails as before

**Comment by rusty1s** [comment]
Interesting, For me `conda install pytorch-scatter -c pyg` does not work while `conda install pytorch-scatter -c pyg -c conda-forge` does work.

**Comment by rusty1s** [comment]
I think I pushed a potential fix. Can you test again once https://github.com/rusty1s/pytorch_scatter/runs/7133968078?check_suite_focus=true is finished?

**Comment by jannisborn** [comment]
Thanks!! Will do and report here.

**Comment by jannisborn** [comment]
I tested again and it's behaving as before unfortunately. Not all builds have finished but I'm using torch 1.12 and those workflows finished already, so I think I'm using the latest version you just pushed.

I also tried both, with and without passing `-c conda-forge`

**Comment by rusty1s** [comment]
What does it mean to use the latest version if it's not working?

**Comment by jannisborn** [comment]
It means that I believe that it should have been able to access the binaries that you just pushed.

Anyways, now all workflows finished and the status is as before, I'm forced to downgrade torch and then the pulled binaries dont work :/

**Comment by rusty1s** [comment]
One last option would be
```
conda install pytorch-scatter -c pyg -c pytorch -c nvidia -c conda-forge
```

**Comment by rusty1s** [comment]
Otherwise, can you test in a fresh environment. I tested on different machines and on GitHub, and they can all install the correct package now. Let me know :)

**Comment by jannisborn** [comment]
Perfect, this one works! Thanks a lot!! 
Interesting that it's really a matter of adding more channels here. 

For future readers: Order of the channels matters (I had them in wrong order at first and installation also failed then)

**Comment by jannisborn** [comment]
Also our GA workflows using `ubuntu-latest` are passing now with the updated list of channels. So it's presumably something others will encounter too. Thanks a lot for the quick help @rusty1s and the great library!
