### ISSUE TITLE
torch/csrc/python_headers.h:9:20: fatal error: Python.h: no such directory or file

### ISSUE THREAD

**Issue by marasilence** [rusty1s/pytorch_scatter#31]
Running setup.py install for torch-scatter ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-r_rfcwb7/torch-scatter/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-v_j6975m/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/max.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/add.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/div.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/min.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/std.py -> build/lib.linux-x86_64-3.6/torch_scatter
    copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.6/torch_scatter
    creating build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/utils.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_backward.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_std.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.6/test
    copying test/test_forward.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/__init__.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.6/torch_scatter/utils
    running build_ext
    building 'torch_scatter.scatter_cpu' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/cpu
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/lib/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/lib/include/THC -I/usr/include/python3.6m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.6/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/csrc/api/include/torch/python.h:6:0,
                     from /usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/extension.h:6,
                     from cpu/scatter.cpp:1:
    /usr/local/lib/python3.6/dist-packages/torch/lib/include/torch/csrc/python_headers.h:9:20: fatal error: Python.h: 没有那个文件或目录
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by marasilence** [comment]
my cuda version is 9.0

**Comment by rusty1s** [comment]
Can you fill [this](https://github.com/rusty1s/pytorch_geometric/blob/master/.github/ISSUE_TEMPLATE/installation.md) out? Otherwise, it's hard to help you.

**Comment by marasilence** [comment]
I have solved this problem by installing python3.6-dev, thanks anyway! @rusty1s

**Comment by rusty1s** [comment]
So [this](
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory) seems to be related. Cool!
