### ISSUE TITLE
A little question about `scatter_cpu`

### ISSUE THREAD

**Issue by clearhanhui** [rusty1s/pytorch_scatter#318]
Hi, I am reading the source code of this project. I wonder if it supports parallel compiling instructions like `#pragma omp parallel for` to improve the following code snippet?
https://github.com/rusty1s/pytorch_scatter/blob/master/csrc/cpu/scatter_cpu.cpp#L69

**Comment by rusty1s** [comment]
We have an open PR out for this, see https://github.com/rusty1s/pytorch_scatter/pull/270.

**Comment by clearhanhui** [comment]
Thanks
