### ISSUE TITLE
Missing the document for gather_csr function

### ISSUE THREAD

**Issue by Apoiuty** [rusty1s/pytorch_scatter#319]
Hey, could you please update the document for the function `gather_csr`. I find no explaination what the function does in the [document](https://pytorch-scatter.readthedocs.io/en/latest/index.html) and source code. Thank you.

**Comment by rusty1s** [comment]
The interface of `gather_csr` is similar to `segment_csr` in the sense that one replicates features according to the offsets defined in `ptr`. It is similar to [`torch.repeat_interleave`](https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html). I will try to update the doc to describe this.

**Comment by Apoiuty** [comment]
@rusty1s Thanks for your help. I have figured it out.
