### ISSUE TITLE
Segmentation fault when testing

### ISSUE THREAD

**Issue by by2101** [rusty1s/pytorch_scatter#32]
Hi, rusty1s,

I've install the pytorch_scatter in a conda virtual env. And I encoountered segmentation fault when testing.
I've checked version, cuda=10.0, torch=1.0.1.post2,gcc=7.3

Thank you!

**Comment by Lavenderjiang** [comment]
Hi by2101, I wonder how you resolve this issue? I've been stuck on it for days, after reinstalling many times

**Comment by rusty1s** [comment]
This is just a guess, but you can try to downgrade your gcc version, *e.g.*, to version 5.4.
