### ISSUE TITLE
Latency overhead in scatter with half precision

### ISSUE THREAD

**Issue by PabloVD** [rusty1s/pytorch_scatter#320]
Hi,
I'm working with a Graph Neural Network which makes use of `scatter` from torch_scatter to aggregate the hidden features from the nodes of the full graph. During inference, I want to run it in half precision, so I move all inputs and the model itself to 16 bits using `.half()` beforehand. 
However, there is an extra overhead in the latency of more than 15 ms which was absent when I run it with standard float32. Profiling, I noticed that the overhead appears at the pooling operation.
Nevertheless, I managed to fix it, converting the inputs of the pooling operation to float32 before the aggregation, and converting back to half precision its outputs, as:
```python
h = h.to(torch.float32)
pool = scatter(h, batch, dim=0, reduce="mean")
pool = pool.half()
```
In that way, this extra overhead disappears, and the model in half precision is actually faster than the version in single precision (as I expected).
What could be the cause of the overhead? Is there a way to fix it which does not require converting the data back and forth?
Many thanks.

**Comment by rusty1s** [comment]
Sorry for late reply. For `scatter_add` and `scatter_mean`, we use PyTorch functions internally (see [here](https://github.com/rusty1s/pytorch_scatter/blob/master/torch_scatter/scatter.py#L38)), so that is likely an issue of the PyTorch implementation.
