### ISSUE TITLE
`segment_csr` crashes Python when provided invalid `indptr`

### ISSUE THREAD

**Issue by ArchieGertsman** [rusty1s/pytorch_scatter#322]
When I run the following code:
```
a = torch.arange(10)
indptr = torch.tensor([0]) # invalid ptr
segment_csr(a, indptr)
```
Python crashes on OSX with the following message:
![image](https://i.imgur.com/VGNPKtR.png)

I'm on version `2.0.9` of `torch_scatter`. 
I think `segment_csr` should check for bad input like this.

**Comment by rusty1s** [comment]
Yes, the input needs to be
```
a = torch.arange(10)
indptr = torch.tensor([0, 10]) # invalid ptr
segment_csr(a, indptr)
```
In general, it is hard to check for invalid inputs in advance since this will lead to costly device transfers (e.g., querying `indptr[0]` and `indptr[-1]`).
