### ISSUE TITLE
How to install torch scatter cpu version on Arm64 machine?

### ISSUE THREAD

**Issue by linnuannuan** [rusty1s/pytorch_scatter#324]
I can't seem to install torch-scatter cpu version on a arm64 machine, no wheels are supported, and the way to install torch-scatter from source code provided in "readme.md" seems to be a cuda version.

**Comment by rusty1s** [comment]
Installation from source works just fine for me on Arm64. Can you post the installation log here?

**Comment by linnuannuan** [comment]
Thanks for your kindness help, i use pip install torch-scatter instead when i fix my pip configuration.
