### ISSUE TITLE
No documentation for composite functions (e.g. scatter_softmax)

### ISSUE THREAD

**Issue by frankier** [rusty1s/pytorch_scatter#327]
It looks like this commit: https://github.com/rusty1s/pytorch_scatter/commit/356d0fe868e69a002224ff4aaca374233a4479b4 removed these from the docs. What happened? Was there a problem with those docs?

**Comment by rusty1s** [comment]
I am actually not sure anymore, we should definitely bring them back.

**Comment by rusty1s** [comment]
Just fixed this, thanks for reporting :)
