### ISSUE TITLE
Prepare torch-scatter==1.13.0+cu116 for testing purpose 🙏 

### ISSUE THREAD

**Issue by ydshieh** [rusty1s/pytorch_scatter#328]
Hi @rusty1s 

Would it be possible to have torch-scatter==1.13.0+cu116 for testing purpose, for the upcoming torch 1.13 (soon) 🙏 Thank you.

**Comment by rusty1s** [comment]
Currently, the only way to do it would be to manually install from source. Does that work for you?

**Comment by ydshieh** [comment]
I will give it a try, thank you @rusty1s  :-)

**Comment by ydshieh** [comment]
Dear @rusty1s , I re-open this issue in order to know if there will be an official way to install `torch-scatter` soon.

Currently, there is no

```bash
https://pytorch-geometric.com/whl/torch-1.13.0+cpu.html
https://data.pyg.org/whl/torch-1.13.0+cpu.html
```
and I am not very sure if you are the person who uploads those files to these 2 pages.

**Comment by rusty1s** [comment]
Yes, working on it.

**Comment by eaplatanios** [comment]
@rusty1s is there an ETA on the torch 1.13.0 binaries? I'm asking so I can plan on whether to try and work around or wait it out.

**Comment by rusty1s** [comment]
Probably early next week. Sorry for the delay.

**Comment by eaplatanios** [comment]
It looks like this has partially landed. Thanks @rusty1s! However, it seems that Python 3.7 wheel files are missing for Windows. Would it be possible to include those? Thanks!

**Comment by rusty1s** [comment]
Sadly no, I was not able to build them on CUDA :(

**Comment by eaplatanios** [comment]
Could you please share what problem you ran into? I may be able to help.

**Comment by eaplatanios** [comment]
Also, I don't see the CPU wheel files available either for Windows and Python 3.7.

**Comment by rusty1s** [comment]
let me try to re-run, will ping here.

**Comment by eaplatanios** [comment]
Thanks! Appreciate it!

**Comment by rusty1s** [comment]
I'll tried, see https://github.com/rusty1s/pytorch_spline_conv/pull/34. Sadly, it fails for CUDA 11.6 :(

Here are all the logs: https://github.com/rusty1s/pytorch_spline_conv/actions/runs/3478680836.

**Comment by eaplatanios** [comment]
Thanks @rusty1s! I'm going to look into this today. One potentially useful thing to try would be to compile using CUDA 11.3 (based on [this](https://discuss.pytorch.org/t/cuda-11-6-extension-problem/145830) thread). With CUDA you're supposed to be able to run programs compiled for 11.3 using 11.6, so that should be fine.

**Comment by eaplatanios** [comment]
I can verify I was able to compile them using CUDA 11.3. I haven't tried yet with 11.6 but given the backwards compatibility guarantees of CUDA this should be fine.

**Comment by eaplatanios** [comment]
I might try CUDA 11.6 if I find some time and will post here if I do.

**Comment by rusty1s** [comment]
Sadly, this doesn‘t work. I am seeing this error: https://github.com/rusty1s/pytorch_spline_conv/actions/runs/3478216455/jobs/5815306959. Interestingly, this is only related to CUDA 11.3 and Python 3.7. Shall I test CUDA 11.7?

**Comment by eaplatanios** [comment]
This is weird. I was able to compile with CUDA 11.3 and what you see as an error I only see as a warning:
```
>> python setup.py build_ext bdist_wheel

running build_ext
C:\Users\eaplatanios\.conda\envs\mage-test\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
C:\Users\eaplatanios\.conda\envs\mage-test\lib\site-packages\torch\utils\cpp_extension.py:387: UserWarning: The detected CUDA version (11.3) has a minor version mismatch with the version that was used to compile PyTorch (11.6). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'torch_spline_conv._basis_cpu' extension
creating build
creating build\temp.win-amd64-cpython-37
creating build\temp.win-amd64-cpython-37\Release
creating build\temp.win-amd64-cpython-37\Release\csrc
creating build\temp.win-amd64-cpython-37\Release\csrc\cpu
...
```

**Comment by rusty1s** [comment]
Agree, let me take a look again.

**Comment by rusty1s** [comment]
I just fixed that by upgrading `setuptools`. Wheels should be ready in an hour.

**Comment by eaplatanios** [comment]
That's great! Thanks @rusty1s!
