### ISSUE TITLE
Error in running python setup.py test

### ISSUE THREAD

**Issue by aikprot** [rusty1s/pytorch_scatter#33]
Hello everyone, 
I am having trouble running torch-scatter. 
I have installed Anaconda3, Cuda 10.0 and Pytorch 1.0.1 on Windows 10 in an attempt to follow pytorch_geometric installation guide. 
I have tried to install it as mentioned in the guide pip install --upgrade torch-scatter but was not correctly installed and then tried a second way to test if the installation succeeded 
$ git clone https://github.com/rusty1s/pytorch_scatter
$ cd pytorch_scatter
$ python setup.py install  # Check for CUDA compilation or link error.
$ python setup.py test  # Verify installation by running test suite.
but still get the screen shown in the attached picture.
![pytorch_scatter](https://user-images.githubusercontent.com/46448420/54602624-d8645480-4a4a-11e9-8df6-f4abe76d48b2.PNG)

I have also tried to run an example separately in another test file as shown below:
--import torch
--from torch_scatter import scatter_max
--src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
--index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
--out, argmax = scatter_max(src, index)

and got this error: ImportError: cannot import name 'scatter_max' from 'torch_scatter'
Could you please recommend what to do next?
Thank you in advance

**Comment by ankur6ue** [comment]
Also getting a bunch of compile errors on Windows 10. I was able to successfully build pytorch 1.01 from source on my windows system. 

cpu/scatter.cpp(51): error C3861: 'toString': identifier not found
cpu/scatter.cpp(51): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(62): note: No constructor could take the source type, or constructor overload resolution was ambiguous
cpu/scatter.cpp(78): error C2450: switch expression of type 'at::Type' is illegal
cpu/scatter.cpp(78): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
cpu/scatter.cpp(68): error C3861: 'toString': identifier not found
cpu/scatter.cpp(68): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(78): note: No constructor could take the source type, or constructor overload resolution was ambiguous
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
