### ISSUE TITLE
Error building tag 2.0.9 from source with pytorch 1.13.0

### ISSUE THREAD

**Issue by alepack89** [rusty1s/pytorch_scatter#337]
Hi

I'm trying to build from source pytorch scatter 2.0.9 with pytorch 1.13.0 with CUDA support.
I get the following error:

csrc/cuda/utils.cuh(12):
 error: more than one user-defined conversion from "const c10::Half" to "__half" applies:
            function "__half::__half(float)"
/usr/local/cuda/include/cuda_fp16.hpp(201): here
            function "__half::__half(__half &&)" (declared implicitly)

The problem seems to be the cast (__half)var in both the functions defined in file 'csrc/cuda/utils.cuh'
Replacing 
 (__half)var
with
 var.operator __half()
seems to solve the problem.

Can you reproduce this issue or am I doing something wrong?

Thank you very much

**Comment by rusty1s** [comment]
Can you try to install from master? I think this should have been fixed there. I really need to release a new version with this fix, sorry for your trouble.

**Comment by rusty1s** [comment]
I just pushed `torch-scatter==2.1.0` :)
