### ISSUE TITLE
Is scatter_add any better than pytorch version?

### ISSUE THREAD

**Issue by lopsided** [rusty1s/pytorch_scatter#34]
Hi,

I was looking for some way to speed up my scatter_add operations and came across this library. Although after switching over to this scatter_add version I'm not seeing any speed increases. From looking at the code it looks like it just adds a bit of extra checking before using the native pytorch scatter_add. Does that mean that the pytorch version is now as efficient? If so are there any other benefits to using this library? (For scatter_add I mean, I haven't looked into the other methods).

Cheers,
Tom

**Comment by rusty1s** [comment]
Hi,
regarding `scatter_add`, this library just adds some syntactic sugar to the native `scatter_add` of PyTorch, *e.g.*, automatically expanding `index` tensors and automatically generating `out` tensors.

**Comment by lopsided** [comment]
OK great. Thanks for the quick reply.
