### ISSUE TITLE
Suggestion: allow second-order derivative for the segment_* reductions

### ISSUE THREAD

**Issue by bigd4** [rusty1s/pytorch_scatter#341]
Dear developers,
Thank you for the great work on this library.  
Recently I used segment_coo in my model but got None when I tried to got the second-order derivative. It seems that it was a reported problem as #299 . Could you please fix this so fewer people make mistakes?

**Comment by rusty1s** [comment]
Yeah, I re-opened this issue. Closing this one here to avoid duplicates. Currently, I don't see how we can support this though. Seems to be some hidden option in the C++ PyTorch backend :(
