### ISSUE TITLE
Compiling scatter C++ API keeps using old python versions.

### ISSUE THREAD

**Issue by ZKC19940412** [rusty1s/pytorch_scatter#346]
Hi, when I am trying to compile torch scatter C++ API, I did the cmake as suggested in the readme. However, when the cmake trying to find python3, it keeps finding an old version of python. I have tried numerous ways (like add set() or inlcude_directories or -D tags when doing the cmake line), but it either keeps finding the old python3.8 or bugged out by saying it can not find a python3.10, when python3.10 is the env I configed for my applications. Would you mind providing some examples on how to modify cmakes or other suggestions so that I can force the cmake (particularly the find_package() function) to use my python3.10 to compile scatter C++ API?

Thank you so much for the help.

**Comment by rusty1s** [comment]
Can you try something like `LD_LIBRARY_PATH=/path/to/python:$LD_LIBRARY_PATH`?

**Comment by ZKC19940412** [comment]
Thanks. By switching to a different machine via a docker image, I managed to have consistent python3.10 for both python with Found Python3 and Found Torch. However, when I compile my applications till the end, I met undefined reference to 'scatter::cuda_version()' . Just wonder have you encountered similar issue and can give some suggestions again?

Thank you so much for all your help.

**Comment by guicho271828** [comment]
should be closed?
