### ISSUE TITLE
Compiler errors on Windows 10

### ISSUE THREAD

**Issue by ankur6ue** [rusty1s/pytorch_scatter#35]
Getting the following compiler errors on my Windows 10 system. I was able to successfully build pytorch 1.01 on my system. I added the following compiler flags by copying the extra_compiler_args from pytorch's setup.py

extra_compile_args += ['/MD', '/Z7',
                          '/EHa', '/DNOMINMAX',
                          '/wd4267', '/wd4251', '/wd4522', '/wd4522', '/wd4838',
                          '/wd4305', '/wd4244', '/wd4190', '/wd4101', '/wd4996',
                          '/wd4275']

Doing so suppresses some warnings, but the errors remain. Please help! This is a great library and not being able to build on windows is unfortunate..

running install
running bdist_egg
running egg_info
writing torch_scatter.egg-info\PKG-INFO
writing dependency_links to torch_scatter.egg-info\dependency_links.txt
writing top-level names to torch_scatter.egg-info\top_level.txt
reading manifest file 'torch_scatter.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'torch_scatter.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'torch_scatter.scatter_cpu' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Anaconda3\lib\site-packages\torch\include -IC:\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda3\lib\site-packages\torch\include\TH -IC:\Anaconda3\lib\site-packages\torch\include\THC -IC:\Anaconda3\include -IC:\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpcpu/scatter.cpp /Fobuild\temp.win-amd64-3.7\Release\cpu/scatter.obj /MD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu /MD
cl : Command line warning D9025 : overriding '/EHs' with '/EHa'
scatter.cpp
C:\Anaconda3\lib\site-packages\torch\include\c10/core/TensorTypeId.h(38): warning C4273: 'c10::toString': inconsistent dll linkage
C:\Anaconda3\lib\site-packages\torch\include\c10/core/TensorTypeId.h(35): note: see previous definition of 'toString'
C:\Anaconda3\lib\site-packages\torch\include\torch/csrc/jit/tracer.h(137): warning C4273: 'torch::jit::tracer::addInputs': inconsistent dll linkage
C:\Anaconda3\lib\site-packages\torch\include\torch/csrc/jit/tracer.h(122): note: see previous definition of 'addInputs'
C:\Anaconda3\lib\site-packages\torch\include\torch/csrc/jit/tracer.h(144): warning C4273: 'torch::jit::tracer::addInputs': inconsistent dll linkage
C:\Anaconda3\lib\site-packages\torch\include\torch/csrc/jit/tracer.h(128): note: see previous definition of 'addInputs'
cpu/scatter.cpp(15): error C2450: switch expression of type 'at::Type' is illegal
cpu/scatter.cpp(15): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
cpu/scatter.cpp(8): error C3861: 'toString': identifier not found
cpu/scatter.cpp(8): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(15): note: No constructor could take the source type, or constructor overload resolution was ambiguous
cpu/scatter.cpp(28): error C2450: switch expression of type 'at::Type' is illegal
cpu/scatter.cpp(28): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
cpu/scatter.cpp(21): error C3861: 'toString': identifier not found
cpu/scatter.cpp(21): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(28): note: No constructor could take the source type, or constructor overload resolution was ambiguous
cpu/scatter.cpp(45): error C2450: switch expression of type 'at::Type' is illegal
cpu/scatter.cpp(45): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
cpu/scatter.cpp(34): error C3861: 'toString': identifier not found
cpu/scatter.cpp(34): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(45): note: No constructor could take the source type, or constructor overload resolution was ambiguous
cpu/scatter.cpp(62): error C2450: switch expression of type 'at::Type' is illegal
cpu/scatter.cpp(62): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
cpu/scatter.cpp(51): error C3861: 'toString': identifier not found
cpu/scatter.cpp(51): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(62): note: No constructor could take the source type, or constructor overload resolution was ambiguous
cpu/scatter.cpp(78): error C2450: switch expression of type 'at::Type' is illegal
cpu/scatter.cpp(78): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
cpu/scatter.cpp(68): error C3861: 'toString': identifier not found
cpu/scatter.cpp(68): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'c10::Error'
cpu/scatter.cpp(78): note: No constructor could take the source type, or constructor overload resolution was ambiguous
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by rusty1s** [comment]
https://github.com/rusty1s/pytorch_geometric/issues/122
