### ISSUE TITLE
Incorrect documentation for scatter_softmax

### ISSUE THREAD

**Issue by 25349023** [rusty1s/pytorch_scatter#350]
Hi, the documentation for `scatter_softmax` says that " $\sum_j$ is over $j$ such that $index_j = i$. "  

However, this function is not a reduce op but a **map** op, so the length of $out$ would be the same as $src$. Hence the summation $\sum_j$ here should be **over $j$ such that $index_j = index_i$**.

**Comment by rusty1s** [comment]
Can you point me to the place where this is wrong? We currently do not provide documentation for `scatter_softmax` :(

**Comment by rusty1s** [comment]
I am not able to edit documentation for past releases :(
