### ISSUE TITLE
release 2.1.0 is tag with 2.0.1, which is confusing

### ISSUE THREAD

**Issue by houqi** [rusty1s/pytorch_scatter#351]
Release 2.1.0 is tagged with 2.0.1

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/1913192/215317786-4c2c5952-b527-4778-bc2b-9bba25207cc2.png">

and tags 2.0.1 is latest

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/1913192/215317755-273e603b-9be4-4b5b-9871-4d09e0a14b23.png">

should it be 2.1.0?

**Comment by rusty1s** [comment]
Thanks for reporting. Fixed now :)
