### ISSUE TITLE
Could you share the main idea behind AtomicAddIntegerImpl?

### ISSUE THREAD

**Issue by 1049451037** [rusty1s/pytorch_scatter#353]
Hi, thank you for your great work!

I'm reading your source code and confused about the [atomics.cuh](https://github.com/rusty1s/pytorch_scatter/blob/master/csrc/cuda/atomics.cuh). Especially the do while loop and bit operations. Could you give me some intuition?

**Comment by rusty1s** [comment]
You can read more about it [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#atomic-functions). The main idea is to use `atomicCAS` to implement other form of atomic operations.

**Comment by 1049451037** [comment]
I get it! Thank you so much!

**Comment by 1049451037** [comment]
Hi, I still have a question. Now that Nvidia provides 16-bits short int atomicCAS [here](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomiccas), AtomicAddIntegerImpl<scalar, 1> and AtomicAddIntegerImpl<scalar, 2> may have some better implementation. With uint32_t we will lock 4 bytes, which will affect nearby operations with 1 bytes or 2 bytes because of unnecessary lock.
