### ISSUE TITLE
 Relation between at::Half and __half

### ISSUE THREAD

**Issue by SakuraRiven** [rusty1s/pytorch_scatter#356]
Hi, we want to create atomicMax function with __half inputs by following this repo which uses at::Half type. When it comes to the __half type, however, we do not how to obtain the hsum.x. Are there some ways to convert as::Half and __half each other?

Thanks : )

**Comment by rusty1s** [comment]
I think you can already convert `__half` to `at::Half` by simply doing `at::Half(value)`, see https://github.com/pytorch/pytorch/blob/master/c10/util/Half.h#L396. Let me know if this works.

**Comment by SakuraRiven** [comment]
@rusty1s Hi, actually, we want to create atomicMax just in normal .cu file without at::Half defination. So, are there some ways to correctly replace at::Half by __half in above function?

We have tried two methods:
### 1
```
  unsigned int *address_as_ui = (unsigned int *)((char *)address - ((size_t)address & 2));
  unsigned int old = *address_as_ui;
  unsigned int assumed;
  do {
    assumed = old;
    __half hsum = __float2half(fmaxf(__half2float(__ushort_as_half(reinterpret_cast<size_t>(address) & 2 ? (old >> 16) : (old & 0xffff))), __half2float(val)));
    old = (size_t)address & 2 ? (old & 0xffff) | (__half_as_ushort(hsum) << 16)
                              : (old & 0xffff0000) | __half_as_ushort(hsum);
    old = atomicCAS(address_as_ui, assumed, old);
  } while (assumed != old);
```
and it produces wrong results.
### 2
Another is
```
  unsigned short* address_as_ushort = reinterpret_cast<unsigned short*>(address);
  unsigned short old = *address_as_ushort, assumed;
  do {
    assumed = old;
    old = atomicCAS(address_as_ushort, assumed, __half_as_ushort(__float2half(fmaxf(__half2float(val), __half2float(__ushort_as_half(assumed))))));
  } while (assumed != old);
```
but has compile error that
```
 error: no instance of overloaded function "atomicCAS" matches the argument list
            argument types are: (unsigned short *, unsigned short, unsigned short)```

**Comment by rusty1s** [comment]
Hopefully, this might be helpful to you: https://github.com/ycchen-tw/tasr/blob/46946dd7f0e95ad1f0bec5c196a878dc9e90c0ef/onnxruntime/onnxruntime/core/providers/rocm/atomic/common.cuh#L25

Need to google that as well since I am no expert on half-precision handling :(

**Comment by SakuraRiven** [comment]
@rusty1s  Hi, we tried two implementations and one of them is from your link. They produced the same results.

We found that the outputs of __first__ ```scatter_max``` layer are similar to GT. However, the outputs of __second__ ```scatter_max``` layer are significantly different from GT. Maybe the problem is in TensorRT and we open an issue [here](https://github.com/NVIDIA/TensorRT/issues/2710) if you are interested.

**Comment by SakuraRiven** [comment]
@rusty1s Hi, our half implementations are finally correct after we solving the plugin bug. More details could be found in this [issue](https://github.com/NVIDIA/TensorRT/issues/2710).

Thanks again for your help : )

**Comment by rusty1s** [comment]
Super, thanks for letting me know :)
