### ISSUE TITLE
[Question] Support for PyTorch 2.0 compile

### ISSUE THREAD

**Issue by L-Reichardt** [rusty1s/pytorch_scatter#359]
Is there support planned in the future to make torch-scatter compatible with PyTorch 2.0s compilation?

**Comment by rusty1s** [comment]
Just landed :)

**Comment by L-Reichardt** [comment]
Thank you for the quick answer and pointing me to those functions. I was not aware they existed.

**Comment by L-Reichardt** [comment]
Since behavior is a little different, this is how I solved it. Maybe not clean, but seems to work equally.

```
unq_inv = unq_inv.unsqueeze(dim=-1).expand_as(features)
_ = torch.zeros_like(features[:torch.max(unq_inv)+1, :])
features =  _.scatter_reduce_(dim=0, index=unq_inv, src=features, reduce="mean", include_self=False)
```
