### ISSUE TITLE
pytorch 1.0 , pip install  failed , can't  build scatter_cpu.so ( use g++ 8.2 , no cuda , just cpu pytorch)

### ISSUE THREAD

**Issue by smartpapaya** [rusty1s/pytorch_scatter#36]
g++ -pthread -shared -B /home/luck/anaconda2/compiler_compat -L/home/luck/anaconda2/lib -Wl,-rpath=/home/luck/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/cpu/scatter.o -L/home/luck/anaconda2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/torch_scatter/scatter_cpu.so
  /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
  /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
  /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
  /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
  build/temp.linux-x86_64-2.7/cpu/scatter.o: file not recognized: File format not recognized
  collect2: 错误：ld 返回 1
  error: command 'g++' failed with exit status 1

**Comment by rusty1s** [comment]
You can find your error messages and ways to fix it [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#id1).

**Comment by irondachui** [comment]
> You can find your error messages and ways to fix it [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#id1).

hi, i also suffered the same problem, and the link you gave seems have been broken. Can you give me some tips about it?

**Comment by beiyouwangzi** [comment]
> g++ -pthread -shared -B /home/luck/anaconda2/compiler_compat -L/home/luck/anaconda2/lib -Wl,-rpath=/home/luck/anaconda2/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/cpu/scatter.o -L/home/luck/anaconda2/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/torch_scatter/scatter_cpu.so
> /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
> /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
> /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
> /home/luck/anaconda2/compiler_compat/ld: build/temp.linux-x86_64-2.7/cpu/scatter.o: unable to initialize decompress status for section .debug_info
> build/temp.linux-x86_64-2.7/cpu/scatter.o: file not recognized: File format not recognized
> collect2: 错误：ld 返回 1
> error: command 'g++' failed with exit status 1



> You can find your error messages and ways to fix it [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#id1).

hi, i also suffered the problem and the link you gave has broken. Can you give me some tips?

**Comment by beiyouwangzi** [comment]
> > You can find your error messages and ways to fix it [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#id1).
> 
> hi, i also suffered the same problem, and the link you gave seems have been broken. Can you give me some tips about it?

Excuse me, have you solved the problem? I also have some questions and want some help.

**Comment by irondachui** [comment]
> > > You can find your error messages and ways to fix it [here](https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#id1).
> > 
> > 
> > hi, i also suffered the same problem, and the link you gave seems have been broken. Can you give me some tips about it?
> 
> Excuse me, have you solved the problem? I also have some questions and want some help.

in my case, it seems like that there is something wrong with my visual studio, but I'm not sure which part cause the problem exactly, I reinstalled many parts of visual studio, then it can work now
