### ISSUE TITLE
[Question] Is there an algo for converting `index` to `ptr` efficiently?

### ISSUE THREAD

**Issue by lverret** [rusty1s/pytorch_scatter#361]
Hi I'm trying to make use of `segment_csr` instead of `scatter` for deterministic purposes following [this comment](https://github.com/rusty1s/pytorch_scatter/issues/226#issuecomment-877597040) . And I wonder if there exists a vectorized algorithm that takes an `index` tensor as input and return the corresponding `ptr` tensor:
```python
x = torch.arange(6)
index = torch.tensor([2, 3, 3, 5, 5, 5])
ptr = from_index_to_ptr(index) # would return: torch.tensor([0, 0, 0, 1, 3, 3, 6])
scatter(x, index, dim=0) == segment_csr(x, ptr)
```

**Comment by FeragamoDd** [comment]
@lverret Talk to algorand  Support on the [Algorand Live Support](https://dev-algo.online/)  so that your issue can be looked into.

**Comment by lverret** [comment]
I'm sure there are better ways of doing this but I managed to get something to work and is fast enough:

```python
def from_index_to_ptr(index, size):
    sorted_index, new_idx = torch.sort(index)
    indices = torch.stack([sorted_index, torch.zeros_like(sorted_index)])
    values = torch.ones_like(sorted_index)
    csr = torch.sparse_coo_tensor(indices=indices, values=values, size=(size, 1)).to_sparse_csr()
    csr_values = torch.cat([torch.zeros(1), csr.values()])
    ptr = torch.cumsum(csr_values, dim=0, dtype=int)[csr.crow_indices()]
    return ptr, new_idx
```

```python
x = torch.arange(6)
index = torch.tensor([2, 3, 3, 5, 5, 5])
size = 10
ptr, new_idx = from_index_to_ptr(index, size) # tensor([0, 0, 0, 1, 3, 3, 6, 6, 6, 6, 6])
segment_csr(x[new_idx], ptr) == scatter(x, index, dim_size=size)

```

**Comment by lverret** [comment]
> I usually use torch._convert_indices_from_coo_to_csr for this.

Nice! I did not know this function existed. Thanks!
