### ISSUE TITLE
Superpix Unpool

### ISSUE THREAD

**Issue by Joazs** [rusty1s/pytorch_scatter#363]
I have a superpixel split index map, a two-dimensional feature matrix. How do I perform superpixel unpooling?
superpix map:[B,H,W]
feature matrix:[B,N,C]

**Comment by rusty1s** [comment]
I might be missing information, but you should be able to reshape the map to `[B, H*W, 1]` and then use `torch.gather` to map the feature matrix to shape `[B, H*W, C]`.
