### ISSUE TITLE
Packages not available on pyg conda channel for most recent Pytorch versions for Windows

### ISSUE THREAD

**Issue by DManowitz** [rusty1s/pytorch_scatter#364]
The readme indicates that there should be builds for Pytorch 2.0 and 1.13, at least, for the 3 GPU options for each of these builds for Linux and Windows.  However, I do not see such builds available via the pyg conda channel.  I see the .whl files available for these builds on data.pyg.org, but I do not see these options available via conda.  Similarly, I do not see the conda packages for these builds for pytorch_cluster, pytorch_sparse, or pytorch_spline_conv.

**Comment by rusty1s** [comment]
These should be available from `pyg` channel, see https://anaconda.org/pyg./pytorch-scatter/files

**Comment by DManowitz** [comment]
Agreed that they should be.  However, I am not seeing them, at least for
Windows.

**Comment by rusty1s** [comment]
That is correct. We failed to build conda packages for Windows currently :( An alternative is to install via PyPi on Windows.

**Comment by jamesmyatt** [comment]
What's required to fix the windows builds?

**Comment by DManowitz** [comment]
The issue has not been fully resolved yet.  In the `pyg` channel, only the pyg package has a Windows build as up-to-date as the Linux or MacOS build.

**Comment by DManowitz** [comment]
Still not seeing current (or other recent) Windows builds in the conda channel.
