### ISSUE TITLE
segment_coo fails to be compiled by Pytorch 2.0

### ISSUE THREAD

**Issue by hitchhicker** [rusty1s/pytorch_scatter#366]
Hello!

I am testing this library for Pytorch 2.0, I encounter a problem if I use `torch_geometric.compile()`.

The code to reproduce my problem:
```
from torch_scatter import segment_coo
from torch_geometric import compile
import torch

class MyModel(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
    def forward(self, src):
        index = torch.tensor([0, 0, 1, 1, 1, 2])
        index = index.view(1, -1)
        out = segment_coo(src, index, reduce="sum")
        return out

model = MyModel().to("cuda")
compiled_model = compile(model)
src = torch.randn(10, 6, 64)
compiled_model(src)
```

I got the following error:
```
 File "/private/home/bokai/miniconda3/envs/ocp-dev-pyt2-2023mar31/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1194, in run_node
   return node.target(*args, **kwargs)
 File "/private/home/bokai/miniconda3/envs/ocp-dev-pyt2-2023mar31/lib/python3.9/site-packages/torch/_ops.py", line 502, in __call__
   return self._op(*args, **kwargs or {})
The tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
above exception was the direct cause of the following exception:
(most recent call last):
 File "/private/home/bokai/miniconda3/envs/ocp-dev-pyt2-2023mar31/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1152, in get_fake_value
   return wrap_fake_exception(
 File "/private/home/bokai/miniconda3/envs/ocp-dev-pyt2-2023mar31/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 808, in wrap_fake_exception
   return fn()
 File "/private/home/bokai/miniconda3/envs/ocp-dev-pyt2-2023mar31/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1153, in <lambda>
   lambda: run_node(tx.output, node, args, kwargs, nnmodule)
 File "/private/home/bokai/miniconda3/envs/ocp-dev-pyt2-2023mar31/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1206, in run_node
   raise RuntimeError(
Failed running call_function torch_scatter.segment_sum_coo(*(FakeTensor(FakeTensor(..., device='meta', size=(10, 6, 64)), cpu), FakeTensor(FakeTensor(..., device='meta', size=(1, 6), dtype=torch.int64), cpu), None, None), **{}):
tensor has a non-zero number of elements, but its data is not allocated yet. Caffe2 uses a lazy allocation, so you will need to call mutable_data() or raw_mutable_data() to actually allocate memory.
```

The versions of libraries:
 - torch==2.0.0
 - torch-geometric==2.4.0
 - torch-scatter==2.1.1+pt20cu117
 - torch-sparse==0.6.17+pt20cu117
 where I have installed the torch-geometric from the current code source.

It looks like that the problem is quite related to this [issue](https://github.com/pyg-team/pytorch_geometric/issues/7004) from torch-geometric, but when I use the latest code, the problem does not get resolved.

Am I missing something or it is known issue that you are investing right now?

Thanks for your help!

**Comment by rusty1s** [comment]
It is a known problem, that‘s why we disable the usage of `torch-scatter` within `torch_geometric.compile`. I am actually not sure how straightforward it is to fix though.

**Comment by drprojects** [comment]
Hi, I am running into the same issue, but am not sure how to understand your answer @rusty1s. Do you mean that a model depending on `torch-scatter` operations should still compile with `torch_geometric.compile` (though related operations are skipped) or that it is currently not possible ?

Thanks in advance for the precision !

**Comment by d4l3k** [comment]
We're also running into this issue. Is there any timelines/plans to resolve this?

**Comment by rusty1s** [comment]
Our current workaround with `torch_geometric.compile` is that we disable the usage of any functions in `torch-scatter` or `torch-sparse` and instead rely on upstreamed versions of it (e.g., `torch.scatter_reduce_`) which work in combination with `torch.compile`. I don't think `torch.compile` can integrate external functions (or at least I am not aware how).

**Comment by MichaelSluydts** [comment]
We are also experiencing this issue and drprojects his question seems to have gotten lost. Both we and the original poster are already are using torch_geometric.compile, yet we're still getting segment_coo errors. I assume removing torch-scatter will fix it, but could you clarify whether we are expecting torch_geometric.compile to work out of the box even with torch-scatter and why it might not?

**Comment by rusty1s** [comment]
> whether we are expecting torch_geometric.compile to work out of the box even with torch-scatter and why it might not?

At least from my studies, it is not (yet) possible to combine external functions such as `torch_scatter` in combination with `torch.compile`. I would need to dig a bit deeper on the concrete issue though :(

**Comment by MichaelSluydts** [comment]
Yeah, I fully understand that, but isn't your torch_geometric.compile supposed to disable them? I tried that function as well as putting the typing lines in a few different places but the segment_coo crash remains. So I think both me and OP are a bit confused whether that is the purpose of the function and if we are missing something. Should I just uninstall torch-scatter? Bit afraid to destroy my environment. :)

**Comment by rusty1s** [comment]
There's no need to uninstall it.

`torch_geometric.compile` mostly works by swapping out `torch_scatter` routines by their equivalent PyTorch counterpart. Since there does not exist a counterpart for `segment_coo`, there is nothing `torch_geometric.compile` can actually do to disable this. The alternative is to use `torch_geometric.utils.scatter` instead of `segment_coo`.

**Comment by MichaelSluydts** [comment]
Aha that was indeed the part that I was missing :) We were trying to maintain internal compatibility with an upstream architecture, but maybe has sailed long ago, I guess we will have to investigate the performance tradeoffs. Thanks!

**Comment by drprojects** [comment]
Thanks for the clarifications @rusty1s ! I will try moving to `torch_geometric.utils.scatter` rather than `torch_scatter` then.
