### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by guicho271828** [rusty1s/pytorch_scatter#367]
segment_coo and segment_csr both uses `Reducer` in reducer.cuh.
It seems to support `"mul"` and `"div"`, but it is currently undocumented

**Comment by rusty1s** [comment]
Can you clarify what you mean with them being undocumented?

**Comment by guicho271828** [comment]
Literally, https://pytorch-scatter.readthedocs.io/en/latest/functions/segment_coo.html does not show `mul`

**Comment by rusty1s** [comment]
It currently does not support `mul` and `div` due to missing backward steps for these functions :(

**Comment by guicho271828** [comment]
oh, ok, I didn't check the backward pass indeed. thanks for explanation!
