### ISSUE TITLE
scatter_logsumexp: NaNs on untouched indices

### ISSUE THREAD

**Issue by aabbas90** [rusty1s/pytorch_scatter#368]
Hi, 

I am trying to perform [scatter_logsumexp](https://pytorch-scatter.readthedocs.io/en/1.4.0/functions/logsumexp.html#scatter-logsumexp) on a strict subset of indices of the `out` tensor. I am getting NaNs at the indices where `out` is supposed to be untouched. Example:

```
import torch
from torch_scatter import scatter_logsumexp

src = torch.Tensor([0.0, 1.0, 4.0])
index = torch.tensor([1, 1, 4])
out = torch.zeros((6, ), dtype = torch.float32)

scatter_logsumexp(src, index, out = out)
print(out)
tensor([   nan, 1.5514,    nan,    nan, 4.0181,    nan]) # Only indices 1, 4 should be changed
print(torch_scatter.__version__)
'2.1.1+pt20cu118'
```

Another issue even if the NaN issue is resolved is about efficiency. We would ideally like to only operate those locations of `out` which are referred to in `index`. Otherwise for a very large sized `out` we are doing redundant calculations. 

Thanks,
Ahmed

**Comment by rusty1s** [comment]
Thanks for reporting. I fixed this in https://github.com/rusty1s/pytorch_scatter/pull/369.

**Comment by aabbas90** [comment]
Thanks for the quick fix. But there is an issue with backpropagation now:

```
import torch
from torch_scatter import scatter_logsumexp

src = torch.Tensor([0.0, 1.0, 4.0])
src.requires_grad = True
src.retain_grad()
index = torch.tensor([1, 1, 4])
out = torch.zeros((6, ), dtype = torch.float32)

scatter_logsumexp(src, index, out = out)

loss = torch.square(out - torch.ones_like(out)).sum()
loss.backward()
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [6]], which is output 0 of ExpBackward0, is at version 7; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
print(src.grad)
```

**Comment by rusty1s** [comment]
Yes, that's because we need to write in-place to `out`. 
```python
out = scatter_logsumexp(src, index)
```
should fix this.

**Comment by yzhangcs** [comment]
@rusty1s Hi, is there any pregress on how to cure backpropagation problems?

**Comment by rusty1s** [comment]
I think this issue is only present if you pass in `out`, and there is not much I can do about this. It should work without specifying that. AFAIK, there are no numerical issues in our implementation, as we correctly compute `exp` by first subtracting by the max element.
