### ISSUE TITLE
How to mask csr index pointer?

### ISSUE THREAD

**Issue by raphaelsulzer** [rusty1s/pytorch_scatter#372]
Hi,

Let's say I have a source tensor `src` and index pointer tensor `indptr`.

```
src = torch.Tensor([5,7,6, 4,3,2, 1,5,7,9, 6,3, 1, 5,2,3,7])
indptr = torch.LongTensor([0,3,10,12,13,17])
out=segment_csr(src,indptr)
# out: tensor([18., 31.,  9.,  1., 17.])
```

Now I would like to apply a mask to `indptr` BEFORE applying `segment_csr`. E.g.:

```
src = torch.Tensor([5,7,6, 4,3,2, 1,5,7,9, 6,3, 1, 5,2,3,7])
indptr = torch.LongTensor([0,3,10,12,13,17])
mask = [1, 3]
indptr = indptr[mask]
out=segment_csr(src,indptr)
# desired out: tensor([18.,  9.])
```

Is there any way to achieve this without "rebuilding" the `src` and `indptr` tensor?
The reason is that my source tensor can become very large, but I only need to reduce the masked elements which are much less.

**Comment by rusty1s** [comment]
I am afraid this isn't possible currently :(

**Comment by raphaelsulzer** [comment]
OK, thank you for the fast response!
