### ISSUE TITLE
New binaries needed 

### ISSUE THREAD

**Issue by cm2435** [rusty1s/pytorch_scatter#379]
Hello!

Sorry to bother, but I am working on deploying a TAPAS model to a triton inference server. As mentioned in #306 #254 this needs torch scatter to work. Unfortunately looking through the pytorch/cuda support matrix for Nvidia triton inference servers

https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-04.html#undefined

I cannot find any that align with the cuda versions that pytorch_scatter has wheels for. Best case is I can use pytorch 2, but that needs a binary with cuda 12.1.0. Versions from the matrix that use cu118 or other supported builds however use PyTorch 1.13.0, which does not have a 11.8 cuda binary on the supplied list. 

I have tried all of the methods for installation including exec'ing into the docker container installing anaconda and using that install method, but no dice.

Any advice on what to do? Any help would be greatly appreciated.

**Comment by rusty1s** [comment]
I don't think `torch-scatter` is no longer needed on PyTorch >= 2.0, since we have upstreamed that functionality to PyTorch directly via `torch.scatter_reduce`. As such, you can probably just replace the `torch-scatter` call in your model with the PyTorch variant. Alternatively, `pip install torch-scatter` should always work whenever we do not provide a wheel for a certain PyTorch/CUDA combination.

**Comment by cm2435** [comment]
**Description of the System:**
Unfortunately, I do not own the model, it is a TAPAS model from the Transformers library [Tapas Documentation](https://huggingface.co/docs/transformers/model_doc/tapas), so I can't edit its implementation.

For reproducibility, I did a fresh Conda install with the following system specs:
- Ubuntu 22.04
- CUDA 12.0
- PyTorch 1.9.0

**Minimum Reproducible Code:**
```python
from transformers import AutoTokenizer, TapasForQuestionAnswering

tokenizer = AutoTokenizer.from_pretrained("google/tapas-base-finetuned-wtq")
model = TapasForQuestionAnswering.from_pretrained("google/tapas-base-finetuned-wtq")
```
Error Message:
ImportError: TapasModel requires the torch-scatter library but it was not found in your environment. You can install it with pip as explained here: [https://github.com/rusty1s/pytorch_scatter](https://github.com/rusty1s/pytorch_scatter).


Issue Explanation:
The error occurs because the TapasModel requires the torch-scatter library, which is missing in the environment.

Additional Context:
As a result, torch scatter is still needed for support, but Nvidia's Triton Inference Server support matrix for specific versions of PyTorch and CUDA do not align with any of the currently released binaries. You can find more information about the support matrix in the [Nvidia PyTorch Release Notes](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-04.html#undefined).

Installing the mismatched torch-scatter binary with the wrong CUDA version will result in a common error indicating that the package won't run if there are CUDA mismatches in the system.

**Comment by cm2435** [comment]
I ended up just regressing to wrapping the model in a fast API server since the performance bottleneck isn't huge, but still, for future use cases this may still be useful to try support?

**Comment by igor-krawczuk** [comment]
mainly asking to clarify (and for the publics benefit I guess): [I see torch 2.0](https://pytorch.org/docs/stable/tensors.html) has `scatter`,`scatter_add` etc. , but for the `scatter_max`and other reductions, for an in-place replacement one has to wrap `scatter_reduce`?
