### ISSUE TITLE
Removing `import torch` in `setup.py` somehow?

### ISSUE THREAD

**Issue by guicho271828** [rusty1s/pytorch_scatter#381]
Currently `setup.py` contains `import torch`.
This makes `pip install torch torch_scatter` or `pip install torch_scatter` fail in a vanilla environment;
It must install them separately, like `pip install torch ; pip install torch_scatter`, which makes automation cumbersome.

**Comment by sbonner0** [comment]
I am currently facing the same issue, even in an environment in which torch is already installed.

**Comment by rusty1s** [comment]
There currently exists no way around this since we need PyTorch to compile the package/install it in the first place. The only workaround is to utilize our provided wheels, e.g., a `requirements.txt` file such as
```
--index-url https://download.pytorch.org/whl/cu118
-f https://data.pyg.org/whl/torch-2.0.0+cu118.html
torch
torch-scatter
```
should work.

**Comment by Midnighter** [comment]
The solution to this problem is to define a `pyproject.toml` with at least a section that looks like:

```toml
[build-system]
requires = [
  "torch"
]
```

That ensures that the requirements are installed before even running the setup script. You might use the opportunity to migrate away from `setup.py` entirely.
