### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda' 

### ISSUE THREAD

**Issue by ASEXPIAO** [rusty1s/pytorch_scatter#385]
Description:
I encountered an error while running the final step of Model Training in the TaBERT project (https://github.com/facebookresearch/TaBERT/tree/main). The error message is as follows:

arduino
Copy code
(py362) root@977f8f12678f:/data/ljh/zyb/TaBERT-main# python train.py --task vanilla --data-dir data/train_data/vanilla_tabert --output-dir data/runs/vanilla_tabert --table-bert-extra-config '{}' --train-batch-size 8 --gradient-accumulation-steps 32 --learning-rate 2e-5 --max-epoch 10 --adam-eps 1e-08 --weight-decay 0.0 --fp16 --clip-norm 1.0 --empty-cache-freq 128
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    from table_bert.vanilla_table_bert import VanillaTableBert
  File "/data/ljh/zyb/TaBERT-main/table_bert/__init__.py", line 10, in <module>
    from table_bert.vanilla_table_bert import VanillaTableBert
  File "/data/ljh/zyb/TaBERT-main/table_bert/vanilla_table_bert.py", line 18, in <module>
    from torch_scatter import scatter_max, scatter_mean
  File "/root/miniconda3/envs/py362/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/root/miniconda3/envs/py362/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/root/miniconda3/envs/py362/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'
Environment:

Operating System: Linux Ubuntu 18.04
Running in Docker container
Conda virtual environment packages:
yaml
Copy code
Package             Version
------------------- -----------
boto3               1.23.10
botocore            1.26.10
certifi             2021.5.30
cffi                1.15.1
charset-normalizer  2.0.12
click               8.0.4
colorama            0.4.5
dataclasses         0.8
fairseq             0.8.0
fastBPE             0.1.0
filelock            3.4.1
idna                3.4
importlib-metadata  4.8.3
importlib-resources 5.4.0
jmespath            0.10.0
joblib              1.1.1
lxml                4.9.3
numpy               1.19.5
pandas              1.1.5
pip                 21.2.2
portalocker         2.7.0
pycparser           2.21
python-dateutil     2.8.2
pytz                2023.3
regex               2023.6.3
requests            2.27.1
s3transfer          0.5.2
sacrebleu           2.3.1
sacremoses          0.0.53
sentencepiece       0.1.99
setuptools          58.0.4
six                 1.16.0
tabulate            0.8.10
tokenizers          0.5.2
torch               1.3.0+cu100
torch-scatter       1.3.2
tqdm                4.64.1
transformers        2.8.0
typing_extensions   4.1.1
urllib3             1.26.16
wheel               0.37.1
zipp                3.6.0
Additional Information:

CUDA version: The command nvcc -V correctly shows CUDA version as "nvcc: NVIDIA (R) Cuda compiler driver, Cuda compilation tools, release 10.0, V10.0.130."
PyTorch CUDA version: The installed PyTorch CUDA version matches the Docker CUDA version and is "10.0.130."
Attempted solutions: I have tried reinstalling both torch and torch_scatter and even created a new conda virtual environment, but the error persists.
Possible Cause:
The error could be related to not using a Docker image with pre-installed CUDA but instead manually installing CUDA within the Docker container.

Questions:

Is the absence of a pre-installed CUDA-enabled Docker image causing this issue, even though the nvcc command shows no errors?
If not using a CUDA-enabled Docker image is the problem, are there any additional steps to properly install CUDA within the Docker container?
Please provide any guidance or solutions to resolve this issue. Thank you!

**Comment by ASEXPIAO** [comment]
I checked the solutions in https://github.com/rusty1s/pytorch_scatter/issues/170, but none of them worked. Google search results for this problem are limited to only two pages. I have attempted all the methods I could find, but the issue persists. Some users suggested that the problem might be due to installing the CPU version of torch_scatter using 'pip install', instead of the GPU version for torch_scatter version 1.3.0. However, I couldn't find the GPU version of torch_scatter 1.3.0

**Comment by rusty1s** [comment]
How did you try to install `torch-scatter`? Can you try to run with `FORCE_CUDA pip install torch-scatter`. Otherwise, you may want to install via our wheels via the `-f` option.

**Comment by ASEXPIAO** [comment]
> How did you try to install `torch-scatter`? Can you try to run with `FORCE_CUDA pip install torch-scatter`. Otherwise, you may want to install via our wheels via the `-f` option.
I installed torch-scatter version 1.3.2 directly using pip install torch-scatter==1.3.2, and I used the -i option to specify the mirror source.

**Comment by ASEXPIAO** [comment]
Thank you! I have solved my problem, and you are my savior.
