### ISSUE TITLE
torch_scatter installation using pip and providing index url still doesn't download the whl

### ISSUE THREAD

**Issue by RickSanchezStoic** [rusty1s/pytorch_scatter#389]
running this command has no affect on whl download, starting from torch 1.12:
`pip install torch_scatter -f https://data.pyg.org/whl/torch-1.12.0%2Bcpu`

It fails to find the whl, and the tar gets downloaded instead.

**Comment by rusty1s** [comment]
Try
```
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.0%2Bcpu.html

**Comment by RickSanchezStoic** [comment]
Yeah, but that doesn't work either.

**Comment by rusty1s** [comment]
What does the error message say?

**Comment by RickSanchezStoic** [comment]
It downloads the tar file instead of wheel. The issue is that the tar one requires you to have torch installed, while the whl one doesn't

**Comment by rusty1s** [comment]
What is the output of
```
pip install --verbose --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.12.0%2Bcpu.html
```
and what OS are you using?

**Comment by RickSanchezStoic** [comment]
I am on debian, but this fails on colab too which is ubuntu. But yeah this `pip install --verbose --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.12.0%2Bcpu.html` works!

**Comment by rusty1s** [comment]
See here for an example on how to install on Colab: https://colab.research.google.com/drive/1h3-vJGRVloF5zStxL5I0rSy4ZUPNsjy8?usp=sharing
