### ISSUE TITLE
Torch 2.1.0 compatibility

### ISSUE THREAD

**Issue by mariajahja** [rusty1s/pytorch_scatter#391]
Hello -- first of all, thanks for this great package! I'm trying to use it with a dev version of torch `2.1.0` with `cu118`, but am unfortunately hitting this following error:
```
torch_scatter/_scatter_cuda.so: undefined symbol:
```
I understand this is due to the package version incompatibility as I installed via `-f https://data.pyg.org/whl/torch-2.0.1+cu118.html`.

I was wondering if there was any advice on getting around this incompatibility. Or perhaps, what the timeline might be to supporting Torch 2.1.0. Thanks for any tips!

**Comment by rusty1s** [comment]
You should be able to install from source in the meantime via
```
pip install torch-scatter
```
We will be providing binaries once PyTorch 2.1 officially lands.

**Comment by mariajahja** [comment]
Thanks for the quick reply! My use case requires binaries so I will be on the lookout after the release.
