### ISSUE TITLE
Backward behaviour of scatter_max

### ISSUE THREAD

**Issue by elias-ramzi** [rusty1s/pytorch_scatter#399]
Hi, 

thank you for the great repo!

I had a question regarding the backward behaviour of scatter_max.
Is it similar to the one of `torch.max`, _i.e._ only one index gets the gradient. Or like the one of `torch.amax`, _i.e._ in case of equality all indexes get gradient?

This difference is explained for torch here: https://pytorch.org/docs/stable/generated/torch.amax.html.

Thank you for your help!

**Comment by rusty1s** [comment]
Only one index gets the gradient.

**Comment by elias-ramzi** [comment]
Thanks!
