### ISSUE TITLE
cuda.h: No such file or directory

### ISSUE THREAD

**Issue by nnzhan** [rusty1s/pytorch_scatter#4]
Hi Matthias

when I run "pip install torch-scatter", it reports 
"""
/home/zhwu/anaconda2/lib/python2.7/site-packages/torch/utils/ffi/../../lib/include/THC/THCGeneral.h:12:18: fatal error: cuda.h: No such file or directory #include "cuda.h"
"""

I have included cuda path in my .bashrc. My platform is anaconda for python 2.7 and cuda-8.0. I have also try to build from your release code 1.0.3, it still doesn't work.

Zonghan

**Comment by rusty1s** [comment]
Please add /usr/local/cuda/include to CPATH.

**Comment by nnzhan** [comment]
Thanks, it works
