### ISSUE TITLE
Compatibility Issue with torch_scatter and PyTorch 2.1.1

### ISSUE THREAD

**Issue by Buddies-as-you-know** [rusty1s/pytorch_scatter#414]
### Description
I'm encountering a compatibility issue with the `torch_scatter` package when using PyTorch version 2.1.1 and CUDA version cu118. The error message I receive is related to an undefined symbol in `_scatter_cuda.so`.

### To Reproduce

1. Set up an environment with PyTorch 2.1.1 and CUDA 11.8 (cu118).
2. Install `torch_scatter` (attempted with version 2.1.2+pt20cu118).
3. Run a script or a module that imports and uses `torch_scatter`.
4. See error: `OSError: /home/iplslam/EEG_Classification/.venv/lib/python3.10/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZN5torch8autograd13_wrap_outputsERKSt6vectorIN2at6TensorESaIS3_EERKSt13unordered_setIPN3c1010TensorImplESt4hashISB_ESt8equal_toISB_ESaISB_EESJ_NS9_8ArrayRefINS9_8optionalIS3_EEEERKSt10shared_ptrINS0_4NodeEESt8functionIFS5_S5_S5_EE`

### Expected behavior
I expect `torch_scatter` to work seamlessly with PyTorch 2.1.1 and CUDA 11.8 without encountering this symbol resolution error.

### Environment
- PyTorch Version (e.g., 1.0): 2.1.1
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): poetry
- Python version: 3.10
- CUDA/cuDNN version: 11.8
```pyproject.toml
torch = "2.1.1+cu118"
torchvision = "0.16.1+cu118"
torchaudio = "2.1.1+cu118"
pyg_lib = {path= "./wheels/pyg_lib-0.3.0+pt21cu118-cp310-cp310-linux_x86_64.whl"}
torch_scatter = {path= "./wheels/torch_scatter-2.1.2+pt20cu118-cp310-cp310-linux_x86_64.whl"}
torch_sparse = {path= "./wheels/torch_sparse-0.6.18+pt21cu118-cp310-cp310-linux_x86_64.whl"}
torch_cluster = {path= "./wheels/torch_cluster-1.6.2+pt21cu118-cp310-cp310-linux_x86_64.whl"}
torch_spline_conv = {path= "./wheels/torch_spline_conv-1.2.2+pt21cu118-cp310-cp310-linux_x86_64.whl"}
```
### Additional context
Could you please provide guidance on the compatible version of `torch_scatter` for PyTorch 2.1.1 with CUDA 11.8, or suggest a workaround for this issue? 

Thank you for your assistance.

**Comment by rusty1s** [comment]
It looks like you installed `torch-scatter` for PyTorch 2.0.

**Comment by Buddies-as-you-know** [comment]
Which one should I install?

**Comment by rusty1s** [comment]
```
torch_scatter = {path= "./wheels/torch_scatter-2.1.2+pt21cu118-cp310-cp310-linux_x86_64.whl"}

**Comment by Buddies-as-you-know** [comment]
Thank you.
