### ISSUE TITLE
Compatibility issue with my torch built from source with torch-scatter installed via pip

### ISSUE THREAD

**Issue by zlwu92** [rusty1s/pytorch_scatter#415]
Hi,

I am encountering a compatibility issue with my PyTorch built from source https://github.com/pytorch/pytorch/blob/v2.1.0,
then my installed pytorch version is 
![image](https://github.com/rusty1s/pytorch_scatter/assets/104770161/8b725777-e28c-4009-99f9-02e759b22ce5)
my cuda version is 12.0
Then I use pip to install torch-scatter, torch-sparse, torch-cluster via
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-2.1.0+cu121.html \
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-2.1.0+cu121.html  \
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-2.1.0+cu121.html \

Then I write a python test code to run a GNN model with import torch_cluster, torch_sparse, torch_scatter

It gives me an error with 
![image](https://github.com/rusty1s/pytorch_scatter/assets/104770161/a60bf4c2-6932-42c5-8417-9ae62b3914e8)
What could be the reason for this problem?
Could you please give me some guidance? Thanks.

**Comment by rusty1s** [comment]
If you install PyTorch from source, you also need to install the extensions from source, e.g., by just dropping the `-f` argument.
