### ISSUE TITLE
missing macos arm wheels for pytorch 2.2

### ISSUE THREAD

**Issue by kleinhenz** [rusty1s/pytorch_scatter#422]
The [pytorch 2.1 wheels](https://data.pyg.org/whl/torch-2.1.0+cpu.html) include universal2 wheels which work on arm macs while the [pytorch 2.2 wheels](https://data.pyg.org/whl/torch-2.2.0+cpu.html) only include x86_64.

**Comment by rusty1s** [comment]
That's strange. We increased the mac OS version we use to build the wheels which might explain this. I am very confused the universal builds work with ARM at all.
