### ISSUE TITLE
cannot successfully install "torch_scatter"

### ISSUE THREAD

**Issue by zhangguanghui1** [rusty1s/pytorch_scatter#43]
I cannot successfully install "torch_scatter".
When I run the command line : pip3 install torch_scatter, an error always occurs, just like below. I tried to solve the problem, but I don't find the correct method. Could you help me? Thanks a lot!

The error:
...
cpu/scatter.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Failed building wheel for torch-scatter
Running setup.py clean for torch-scatter
Failed to build torch-scatter
Installing collected packages: torch-scatter
Running setup.py install for torch-scatter ... error
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-ijd9s63n/torch-scatter/setup.py';exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-4tkx7v_s-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/mul.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/mean.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/sub.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/min.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/std.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/init.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/max.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/div.py -> build/lib.linux-x86_64-3.5/torch_scatter
copying torch_scatter/add.py -> build/lib.linux-x86_64-3.5/torch_scatter
creating build/lib.linux-x86_64-3.5/test
copying test/test_multi_gpu.py -> build/lib.linux-x86_64-3.5/test
copying test/utils.py -> build/lib.linux-x86_64-3.5/test
copying test/test_std.py -> build/lib.linux-x86_64-3.5/test
copying test/init.py -> build/lib.linux-x86_64-3.5/test
copying test/test_forward.py -> build/lib.linux-x86_64-3.5/test
copying test/test_backward.py -> build/lib.linux-x86_64-3.5/test
creating build/lib.linux-x86_64-3.5/torch_scatter/utils
copying torch_scatter/utils/ext.py -> build/lib.linux-x86_64-3.5/torch_scatter/utils
copying torch_scatter/utils/init.py -> build/lib.linux-x86_64-3.5/torch_scatter/utils
copying torch_scatter/utils/gen.py -> build/lib.linux-x86_64-3.5/torch_scatter/utils
running build_ext
building 'torch_scatter.scatter_cpu' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/cpu
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/zgh/.local/lib/python3.5/site-packages/torch/lib/include -I/home/zgh/.local/lib/python3.5/site-packages/torch/lib/include/TH -I/home/zgh/.local/lib/python3.5/site-packages/torch/lib/include/THC -I/usr/include/python3.5m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.5/cpu/scatter.o -Wno-unused-variable -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cpu/scatter.cpp:1:29: fatal error: torch/extension.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-ijd9s63n/torch-scatter/setup.py';exec(compile(getattr(tokenize, 'open', open)(file).read().replace('\r\n', '\n'), file, 'exec'))" install --record /tmp/pip-4tkx7v_s-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ijd9s63n/torch-scatter/
You are using pip version 8.1.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by rusty1s** [comment]
Hi, install the latest PyTorch version.

**Comment by zhiqiangzhongddu** [comment]
I have installed the Pytorch--1.1.0 (should be the latest version) with Python--3.6, Cuda--9.0 on Win10, but still can't install the package. 
Should I check any other parts?

**Comment by rusty1s** [comment]
The error message should be different now, I guess?

**Comment by zhiqiangzhongddu** [comment]
Thank you so much for your super quick reply. 

On py3.6, Cuda--9.0 error:
 error: command 'C:\\Users\\zhiqiang.zhong\\AppData\\Local\\Continuum\\anaconda3\\envs\\py36\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1

    ----------------------------------------
Command "C:\Users\zhiqiang.zhong\AppData\Local\Continuum\anaconda3\envs\py36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZHIQIA~1.ZHO\\AppData\\Local\\Temp\\pip-install-7q_renqx\\torch-scatter\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ZHIQIA~1.ZHO\AppData\Local\Temp\pip-record-s7asnk5v\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ZHIQIA~1.ZHO\AppData\Local\Temp\pip-install-7q_renqx\torch-scatter\

On Py3.7 Cuda--10, error:
 C:\Users\zhiqiang.zhong\AppData\Local\Continuum\anaconda3\envs\py37\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
      warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
    building 'torch_scatter.scatter_cpu' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command "C:\Users\zhiqiang.zhong\AppData\Local\Continuum\anaconda3\envs\py37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZHIQIA~1.ZHO\\AppData\\Local\\Temp\\pip-install-gfzinbwh\\torch-scatter\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ZHIQIA~1.ZHO\AppData\Local\Temp\pip-record-hozbls4o\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ZHIQIA~1.ZHO\AppData\Local\Temp\pip-install-gfzinbwh\torch-scatter\

**Comment by rusty1s** [comment]
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```
Did you do this?

**Comment by zhiqiangzhongddu** [comment]
I think I installed it already as https://www.scivision.dev/python-windows-visual-c-14-required/ mentioned. But, same error.

**Comment by zhiqiangzhongddu** [comment]
after re-install Visual Studio related packages, 
there is a new error for Py37,

 scatter.obj : warning LNK4197: export 'PyInit_scatter_cpu' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.7\Release\cpu\scatter_cpu.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\cpu\scatter_cpu.cp37-win_amd64.exp
    Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "C:\Users\zhiqiang.zhong\AppData\Local\Continuum\anaconda3\envs\py37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ZHIQIA~1.ZHO\\AppData\\Local\\Temp\\pip-install-ur686ng4\\torch-scatter\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ZHIQIA~1.ZHO\AppData\Local\Temp\pip-record-qa3ur92f\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ZHIQIA~1.ZHO\AppData\Local\Temp\pip-install-ur686ng4\torch-scatter\

Does it help you to have a better understanding?

**Comment by rusty1s** [comment]
Maybe [this one](https://stackoverflow.com/questions/14372706/visual-studio-cant-build-due-to-rc-exe) helps.

**Comment by zhiqiangzhongddu** [comment]
@rusty1s thanks, it works with Python-3.7 on Win-10 now.

**Comment by rusty1s** [comment]
Cool :)
