### ISSUE TITLE
A problem of install

### ISSUE THREAD

**Issue by xiaosa269** [rusty1s/pytorch_scatter#432]
Hello,

Thank you very much for your pytorch_scatter library. I'm using CUDA: 11.1 and torch: 1.8.1. After installing torch, I conducted some tests, and it seems that the GPU is accessible.

However, after installing pytorch-scatter using conda install pytorch-scatter -c pyg, when I entered Python for testing, the following issue occurred:
(frnet) xhy@sun:~/code/FRNet-master$ python
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available() 
False

After uninstalling pytorch-scatter using conda uninstall pytorch-scatter, I tested torch again:
(frnet) xhy@sun:~/code/FRNet-master$ python
Python 3.8.0 (default, Nov  6 2019, 21:49:08) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'cuda'

Could you please advise on why this is happening? Your assistance would be greatly appreciated. Thank you very much.

**Comment by rusty1s** [comment]
Try `torch-scatter==2.0.8` for PyTorch 1.8, see [here](https://data.pyg.org/whl/torch-1.8.1%2Bcu111.html).
