### ISSUE TITLE
Question about install C++ API 

### ISSUE THREAD

**Issue by yhd-ai** [rusty1s/pytorch_scatter#433]
I install torch_scatter via pip. And in which path should I conduct your code
`mkdir build
cd build
# Add -DWITH_CUDA=on support for CUDA support
cmake -DCMAKE_PREFIX_PATH="..." ..
make
make install`

should I download your source code? I am sorry I am not familiar with C++

**Comment by rusty1s** [comment]
This is only relevant for the C++ API. Since you are using Python, `pip install` is sufficient.

**Comment by yhd-ai** [comment]
Hi, but I need to install C++ API cuz I script my own model via torch.jit.script. When I using it in c++ I got the error like #147
