### ISSUE TITLE
OSError: dlopen.. when import torch_scatter

### ISSUE THREAD

**Issue by mlv42** [rusty1s/pytorch_scatter#437]
I get the error : 

OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch_scatter/_version_cpu.so, 0x0006): Symbol not found: __ZN3c1017RegisterOperatorsD1Ev
  Referenced from: <85F5D618-9A81-323E-B8CF-4EA588421020> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch_scatter/_version_cpu.so
  Expected in:     <D6FBF042-0075-33D1-9A58-1D627AC1294E> /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib

when I import torch_scatter. 
I have:
- python 3.9.5
- torch 2.2.1

and I have installed torch_scatter using this line of code: 

pip install torch-scatter -f https://data.pyg.org/whl/torch-2.2.2+cpu.html

on a Mac. 

How can I fix it? I am sorry but I am not familiar with how these kind of issues work.

**Comment by rusty1s** [comment]
How did you install PyTorch? Are you using the `conda-forge` package?

**Comment by mlv42** [comment]
I used `pip install torch` and no, I am not using `conda-forge` . Should I?

**Comment by rusty1s** [comment]
No, that sounds good then. Is this ARM or Intel mac?

**Comment by mlv42** [comment]
It's an Intel Mac

**Comment by rusty1s** [comment]
Got it. What happens if you simply install via
```
pip uninstall torch-scatter
pip install torch-scatter
```

**Comment by mlv42** [comment]
I get the error:

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torch-scatter
  Running setup.py clean for torch-scatter
Failed to build torch-scatter
ERROR: Could not build wheels for torch-scatter, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages.


when I run `pip install torch-scatter` after I run `pip uninstall torch-scatter`.

**Comment by rusty1s** [comment]
Sorry for late reply:

Can you run with
```
pip install --verbose torch-scatter
```
This should give a more descriptive error message.

**Comment by EliasLMann** [comment]
I had this same issue however I am python 3.10, Intel Mac. Im using macOS 14.14.1 and was getting a MacOSX SDK error:

`python3.10/site-packages/torch/include/ATen/core/function_schema.h:596:50: error: 'value' is unavailable: introduced in macOS 10.13`

 I set the macOS deployment target to 10.14 (something that isn't too recent but greater than 10.13 should work). Then installed successfully.

```
export MACOSX_DEPLOYMENT_TARGET=10.14
pip install --no-cache-dir torch-scatter -f https://data.pyg.org/whl/torch-2.2.1+cpu.html
```

I think this is because some C++17 dependencies used in this package do not work with earlier macOS versions.

**Comment by unclemusclez** [comment]
check https://github.com/rusty1s/pytorch_scatter/issues/448
 try : `pip install torch-scatter -f https://data.pyg.org/whl/torch-2.2.1+cpu.html`
 
 you are installing the wrong version of torch scatter.
