### ISSUE TITLE
Is it possible to run pytorch_scatter with latest Pytorch Nightly Release v2.5.0.

### ISSUE THREAD

**Issue by JJDOESIT** [rusty1s/pytorch_scatter#449]
Before I was running pytorch_scatter with Pytorch v2.3.0, cuda version 12.1. When upgrading Pytorch to latest nightly build, I receive: 

```undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs```

I believe most likely due to a version mismatch as in the documentation I only see support up to v2.3.0. Any suggestions or any way to bypass the error?

**Comment by rusty1s** [comment]
For PyTorch nightly, you need to build `torch-scatter` from source.

**Comment by JJDOESIT** [comment]
Building from source worked. Weird because I tried it yesterday from source and it didn't work but today it did. Thanks a lot.
