### ISSUE TITLE
PyTorch CUDA version and system CUDA version not match

### ISSUE THREAD

**Issue by ColdenChan** [rusty1s/pytorch_scatter#45]
hi, i have a problem: my torch.version.cuda is 9.0.176, but my nvcc --version is 10.0  what can I do to fix the problem? thank you.

**Comment by rusty1s** [comment]
You need to link/replace your environment variables to CUDA 9.0. I guess you have two folders in `/usr/local/` named `cuda9` and cuda10`?

**Comment by ColdenChan** [comment]
I installed the wrong version of pytorch. Now, I update my pytorch to 10.0.130, and it works. Thank you.
