### ISSUE TITLE
can not install torch_scatter on WIN10 with CUDA 10.0 pytorch 1.1.0

### ISSUE THREAD

**Issue by Mario-Liu** [rusty1s/pytorch_scatter#46]
I followed the Installation tuturial [https://rusty1s.github.io/pytorch_geometric/build/html/notes/installation.html#frequently-asked-questions](url) and checked every step carefully. But never succeed in Step 3 Install all needed packages:  **pip install torch-scatter**. Anyone can help me?

here is the setup:
Setup: CUDA 10.0, cudNN 7.4.2, VS 2017 , PyTorch 1.1.0 ,WIN10, Anaconda  

 `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\nvcc.exe -c cuda/scatter_kernel.cu -o build\temp.win-amd64-3.6\Release\cuda/scatter_kernel.obj -Xcompiler /wd4819 -Xcompiler /MD -Id:\anaconda\lib\site-packages\torch\include -Id:\anaconda\lib\site-packages\torch\include\torch\csrc\api\include -Id:\anaconda\lib\site-packages\torch\include\TH -Id:\anaconda\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -Id:\anaconda\include -Id:\anaconda\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cuda -D_GLIBCXX_USE_CXX11_ABI=0

    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.0\\bin\\nvcc.exe' failed with exit status 2
    ----------------------------------------

ERROR: Command "'d:\anaconda\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\lzt\\AppData\\Local\\Temp\\pip-install-zmhx_cj7\\torch-scatter\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\lzt\AppData\Local\Temp\pip-record-wou7zo1z\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\lzt\AppData\Local\Temp\pip-install-zmhx_cj7\torch-scatter\
`

**Comment by rusty1s** [comment]
Related https://github.com/rusty1s/pytorch_geometric/issues/362
