### ISSUE TITLE
Undefined symbol error

### ISSUE THREAD

**Issue by vixp24** [rusty1s/pytorch_scatter#461]
Hi there, 

I'm am trying to install torch_scatter on an NVIDIA Jetson (JP6.0) as a dependency, but keep running into this error upon importing torch_scatter in python:

`OSError: /home/vp/anaconda3/envs/env1/lib/python3.10/site-packages/torch_scatter/_version_cpu.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb`

I am working in a conda environment, and have got CUDA 12.2 on the system, with PyTorch successfully installed (with Jetson wheels). "torch.version.cuda" reports 12.2 as expected. 

Could the cuda-toolkit version be problematic here? Are all of these packages compatible with each other?

I have seen an identical issue reported [here](https://discuss.pytorch.org/t/undefined-symbol-zn3c1017registeroperatorsd1ev/197979/10) recently. 

Versions of installed packages:
torch                     2.4.0a0+07cecf4168.nv24.5
torch_scatter             2.1.2
cuda-toolkit              12.2.2

Any help is appreciated!

Thanks,

**Comment by SUN-zx** [comment]
did you solve it? I  had the same problem

**Comment by vixp24** [comment]
I just resolved it. The issue seemed to be that I did not have the correct `/usr/local/cuda/bin` and `/usr/local/cuda/include` directories exported with environment variables as instructed in the README - which I suspect caused installation of the wrong wheel files (not for aarch64). After exporting the correct directories, and running the following, pip finds that there are no compatible wheels for aarch64 and goes ahead to build torch_scatter from source. 

`pip install torch-scatter -f https://data.pyg.org/whl/torch-2.4.0+cu122.html --no-cache-dir`

While the build is happening, you should see the C++ compiler and some other cuda process running during the build.

After this, importing torch_scatter worked with no issues! Goodluck @SUN-zx 

Thanks,

**Comment by fplandes** [comment]
Note sure this will directly help, but to solve an issue related to installing pyg_lib, torch_sparse and torch_scatter, I recently answered here: https://stackoverflow.com/questions/78346857/how-to-install-glibcxx-3-4-29-in-miniconda/79509513#79509513
