### ISSUE TITLE
Doubts with scatter_add

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_scatter#52]
Hi,

I have doubts related to how to use the scatter_add. I have this toy example:

```
x = torch.tensor([[100., 200.],
        [500., 600.],
        [500., 600.],
        [100., 200.],
        [700., 800.],
        [700., 800.],
        [500., 600.]])

ind =torch.tensor([0, 0, 1, 1, 1, 2, 2])

output = out = scatter_add(x, ind, dim=1, out=None)

expected_output = torch.tensor[1400, 2900, 2600]
```

I'm getting this error:

`RuntimeError: shape '[1, 2]' is invalid for input of size 7`

How can I obtain my expected output using scatter_add?

**Comment by rusty1s** [comment]
You want to `scatter_add` in the first dimension, so `scatter_add(x, ind, dim=0)` should do the trick :)

**Comment by dhorka** [comment]
If I am doing in the first dimension I obtaining this:

```
tensor([[ 600.,  800.],
        [1300., 1600.],
        [1200., 1400.]])
```

This is not the expected result... I know that I can sum over rows to obtain the expected results but it is not the goal. I am doing scatter as example to understand how ind and dim works... Because, if i change the add to another operation like std, this approach should not work...

**Comment by rusty1s** [comment]
But this is the expected result? I do not understand. The `input` and `index` tensor must match in shape, and if we are only given a one-dimensional `index` tensor, we repeat it for every other dimension. So in case `index` is one-dimensional, we require `index.size(0) == input.size(dim)`.

**Comment by dhorka** [comment]
I understand what you are saying. But I am trying to do another thing.  My expected result is this one: torch.tensor[1400, 2900, 2600]. I know that, my index vector is not the correct one but I do not know how to generate the index vector properly to obtain this expected result. The idea is: do a scatter_sum for using the index vector provided but if the there is more than one dimension sum all dimensions to the position indicated for the index vector. In this example I am using sum, but imagine the same case using std. I am expecting for each  position of x obtain one std such as torch.tensor[std1, std2, std3]

**Comment by rusty1s** [comment]
I am still not sure I fully understand, but for `scatter_add` you can `scatter_add` in the desired dimension, and sum up all other dimensions. So for your example above, this is what you want:
```python
scatter_add(x, ind, dim=0).sum(dim=1)
```

**Comment by dhorka** [comment]
I want this without to do the last .sum(). My idea was to use a scatter_add because is more easy to explain (sorry for that I see that my explanation it is not good enough).

I do not want to use this last sum, because my example it is only a toy example. I want to do the same but with std.

**Comment by rusty1s** [comment]
So then reshape your tensors:
```python
scatter_std(x.flatten(), ind.flatten(), dim=0)
```

**Comment by dhorka** [comment]
I see, but then, what is the purpose of the attr dim. In what cases will it be useful?

**Comment by rusty1s** [comment]
Well, it is useful for only scattering in one dimension, *e.g.*, for aggregating features in Graph Neural Networks. The scatter op is a reduction op, and a `dim` attribute comes in very handy there.

**Comment by dhorka** [comment]
I see thanks! That it is all for my side.
