### ISSUE TITLE
[Feature Request] Return the scatter indexes

### ISSUE THREAD

**Issue by vguizilini** [rusty1s/pytorch_scatter#55]
Great package, very interesting and very useful!

One question: would it be possible for the scatter operation to return the indexes used to select the points, or even the points themselves, without reduction? Or is there a better, and still efficient, operation that can be used to achieve this?

Many thanks.

**Comment by rusty1s** [comment]
I do not fully understand. The indices which are used to select the points are part of the input. For scatter_max and scatter_min, we additionally return the argmax and argmin respectively.

**Comment by vguizilini** [comment]
I am trying to create a 2D grid that receives information from a 3D pointcloud, each point contributing to the grid based on their spatial location. Your scatter operations are exactly what I need, so I can reduce the points that belong to the same grid cell, but I plan to use more complex reduction operations (histograms, pointnets, etc). You are right, I give the indices as input, but the naive way of recovering the points for each grid cell is *very* slow:

pointcloud.shape = (N3) % 3D coordinates for a pointcloud
grid.shape = (M2) % Flattened from a 2D grid, with spatial coordinates
indices.shape = (N1) % Index for each point in the pointcloud, mapping it to the grid
for i in range(grid.shape[0]):
    points = pointcloud[indices == i]

This is exactly what I need, but the scatter_op takes milliseconds, while this one takes seconds, even with numba, and I am only gathering the indexes that belong to the same grid cell, not even doing the reduction operation.  At the same time, this is exactly what you do for the custom scatter_ops, except that you do a reduction operation on top of that. If you could simply return the points used for the reduction operation, while keeping the efficiency your package achieves, that's all I need. 

Or maybe I am looking at this the wrong way and there is a more clever way to recover these indexes, if that's the case I would love to know the alternative. Thanks for your time!

**Comment by rusty1s** [comment]
So instead of a scatter op, you want to split your data according to the index (cluster) it belongs to, and the output should be a python list holding subset point matrices. This is not what this package is trying to achieve, but there is a regular PyTorch function called [`split`](https://pytorch.org/docs/stable/torch.html#torch.split), where you can pass in the size of each section (cluster) as a list. Note that points needs to be sorted based on their index though.
