### ISSUE TITLE
"ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'" on Windows 10

### ISSUE THREAD

**Issue by Junyoungpark** [rusty1s/pytorch_scatter#56]
Hi, Thanks for the awesome library. I used to use torch-scatter a lot on windows and linux.
Here I tried to install and play with torch-scatter. But I got a fatal error

``` python
import torch_scatter
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\joon0\dev\pytorch_scatter\torch_scatter\__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "C:\Users\joon0\dev\pytorch_scatter\torch_scatter\mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "C:\Users\joon0\dev\pytorch_scatter\torch_scatter\utils\ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'

I install torch-scatter from source via the following commend

```
$ python setup.py install
```
On my machine, It has GPU and cuda. BUT I installed pytorch-cpu, NOT gpu version. 

Here's building log.
[log.txt](https://github.com/rusty1s/pytorch_scatter/files/3415898/log.txt)

**Comment by rusty1s** [comment]
Can you try to uncomment [these lines](https://github.com/rusty1s/pytorch_scatter/blob/master/setup.py#L17-L21) and try again:
```
$ rm -rf build/ && python setup.py install
```

**Comment by Junyoungpark** [comment]
It is already uncommented. U mean 'comment' these lines?
If so, here's the result.

[log_commented.txt](https://github.com/rusty1s/pytorch_scatter/files/3415934/log_commented.txt)

**Comment by rusty1s** [comment]
Well, as far as see, installation succeeded. So this definitely helped. Are you sure there are not multiple torch-scatter versions installed? You should make sure and run pip uninstall torch-scatter multiple times.

**Comment by Junyoungpark** [comment]
Oh. I guess I found the issue. As you suggested, I delete preinstalled packages multiple times and I got out of PyTorch-scatter directory and reinstall torch-scatter again trough pip, I magically run.
Thanks for the support!
