### ISSUE TITLE
Unable to import scatter_cuda

### ISSUE THREAD

**Issue by shagunsodhani** [rusty1s/pytorch_scatter#6]
Hey

I tried installing the package via both pip and source.  It works perfectly good on a cpu but when I try to `import scatter_cuda` on a gpu, it gives me the following error:

```
ImportError: /u/sodhanis/anaconda3/envs/torch0.4.1/lib/python3.6/site-packages/torch_scatter-1.0.4-py3.6-linux-x86_64.egg/scatter_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
```

I made sure to setup $PATH and $CPATH. For reference, they look like 

```
$PATH=...anaconda3/envs/torch0.4.1/bin::/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin
```
```
$CPATH=/usr/local/cuda/include
```

I think it might be a PATH issue. Looking at the error, do you have any pointers as to where I should look?

**Comment by shagunsodhani** [comment]
Ohh it turns out I should have imported torch first as suggested [here](https://github.com/pytorch/extension-cpp/issues/6). It works fine now. Should we add this information in the README?

**Comment by rusty1s** [comment]
Thanks, didn't know that. Will add this information to the README.
