### ISSUE TITLE
[Feature Request] Employ with mismatched indices

### ISSUE THREAD

**Issue by sbb-gh** [rusty1s/pytorch_scatter#60]
Thank you very much for the package, incredibly useful.

Would it be possible to implement this with mismatched indices shape for add, 
 e.g. the PyTorch version only requires that index.shape \leq src.shape \forall dim,   index.shape \leq self.shape d \neq dim.

Furthermore, would it also be possible to allow some dimensions to have shape 1, avoiding having to use t.sum, or using more memory with .expand(...).

For example, I have a index shape (B,H,W,D) and src shape (B,C,H,W,D).  I currently need to do:
        index = index.unsqueeze(dim=1).expand(-1,C,-1,-1,-1)
        y = torch_scatter.scatter_add(src=src,
                                        index=index,
                                        dim=2,
                                        dim_size=H_1,
                                        fill_value=0)
        y = t.sum(y,dim=(3,4))

But ideally I could do index = index.unsqueeze(dim=1) and then define y to have shape (B,C,H_1,1,1) to be filled.

**Comment by rusty1s** [comment]
Hi and thank you. I think we should definitely add broadcasting capabilities to the package. I will do this ASAP. Note that expand does not result in more memory, so expand is the right choice here.

I do not understand your second request though, as this would contradict the scatter operation. If you want to scatter in multiple dimensions, you can always reshape your tensors to achieve this.

**Comment by rusty1s** [comment]
I added broadcasting capabilities to the master version of `torch-scatter`. You can now pass shapes such as `(B,1,H,W,D)` and `(B,C,H,W,D)` to all operations. Thank you for great the suggestion!
