### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

### ISSUE THREAD

**Issue by choltz95** [rusty1s/pytorch_scatter#61]
Would really appreciate any help with these installation issues. Manually added non-traditional cuda directory to environment on an LSF cluster.

**via pip:**
$ echo $PATH
:/pkg/nvidia/cuda/9.0/bin/

$ echo $CPATH
:/pkg/nvidia/cuda/9.0/include/

$ echo $LD_LIBRARY_PATH
:/pkg/nvidia/cuda/9.0/lib64:/pkg/nvidia/cuda/9.0/lib64

$ echo $CUDA_HOME
:/pkg/nvidia/cuda/9.0

\> import torch
\> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr2/choltz/venv/lib/python3.6/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/usr2/choltz/venv/lib/python3.6/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/usr2/choltz/venv/lib/python3.6/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

**via src install:**
(venv) choltz@crd-lsf-gpu03:~/pytorch_scatter$ gcc --version

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

/usr/include/c++/6/tuple:502:1: error: body of constexpr function ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_NonNestedTuple() [with _SrcTuple = std::tuple<at::Tensor, at::Tensor, double, long int>&&; bool <anonymous> = true; _Elements = {at::Tensor, at::Tensor, double, long int}]’ not a return-statement
     }
 ^
error: command '/pkg/nvidia/cuda/9.0/bin/nvcc' failed with exit status 1

**Comment by choltz95** [comment]
Possibly related:
https://github.com/pytorch/pytorch/issues/3807#issuecomment-400171950

**Comment by choltz95** [comment]
Attempting to install with v 8.0 cuda:

**via pip:**
Still no 'torch_scatter.scatter_gpu' found

**via src:**
>>> import torch
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr2/choltz/pytorch_scatter/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/usr2/choltz/pytorch_scatter/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/usr2/choltz/pytorch_scatter/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ModuleNotFoundError: No module named 'torch_scatter.scatter_cpu'

**Comment by choltz95** [comment]
Hmmm... looks like it managed to work itself out somehow. Uncommented the setup.py edit & made sure all versions were uninstalled.

**Comment by rusty1s** [comment]
Awesome, happy hacking!
