### ISSUE TITLE
Derivative issue when using scatter_max

### ISSUE THREAD

**Issue by 0oshowero0** [rusty1s/pytorch_scatter#63]
When I use _scatter_max()_ in my code, I run into some backward issue, which says the backward is not defined. 

I wrote a sample code is here:

```python
import numpy as np
import torch
from torch_scatter import scatter_max
from torch_geometric.utils import softmax

a = torch.randn((20,2),requires_grad=True)
index = np.random.randint(0,4,size=20)
index = torch.tensor(index)

result = softmax(a, index)
max_result = scatter_max(result, index, dim=0, dim_size=result.shape[0])[1][0:4,:]
final_result = torch.zeros_like(a).scatter_(0, max_result, 1.0)
```

Then there will be a runtime error when running the last line:

> RuntimeError: the derivative for 'index' is not implemented

with torch 1.1.0, torch-geometric 1.3.0, torch-scatter 1.3.1.

**Comment by rusty1s** [comment]
Well, this is not a bug. The `index` tensor does not have a derivative, similar to how `argmax` does not have a derivative, because they are not continuous. If you want to implement a hard decision with continuous gradients, have a look at the [`gumbel_softmax hard=True` trick](https://pytorch.org/docs/stable/nn.functional.html?highlight=gumbel#torch.nn.functional.gumbel_softmax).

**Comment by 0oshowero0** [comment]
Thank you for your fast response! Actually I am trying to apply _torch.nn.functional.gumbel_softmax()_ in the process of _torch_geometric.nn.MessagePassing.message()_. But since this _message()_ fuction works in scatter manner, I'm trying to adapt _torch.functional.gumbel_softmax()_ to suit this framework. The source code of _gumbel_softmax()_ use _torch.max()_ to get the argmax, and the example code I wrote is trying to change _torch.max()_ to _scatter_max()_. It seems that the argmax generated by _torch.max()_ do have a derivative and I'm a little confused.

[ torch.nn.functional.gumbel_softmax()](https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#gumbel_softmax)

**Comment by rusty1s** [comment]
I see. So what you are doing is generally right:
```python
out = result - result.detach() + final_result
```
should work fine. If you still encounter gradient issues, you can try to add a `detach()`  to the `max_result` before you use it in the `scatter_` op.
