### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qjzhzw** [rusty1s/pytorch_scatter#65]
![image](https://user-images.githubusercontent.com/20254865/64932194-e23b0900-d86f-11e9-9b9b-97d48f6ae21f.png)

**Comment by qjzhzw** [comment]
`Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from torch_scatter import scatter_max
>>> src = torch.tensor([[2, 0, 1, 4, 3], [0, 2, 1, 3, 4]])
>>> index = torch.tensor([[4, 5, 4, 2, 3], [0, 0, 2, 2, 1]])
>>> out, argmax = scatter_max(src, index, fill_value=0)
Segmentation fault (core dumped)`

**Comment by rusty1s** [comment]
This seems to be an installation error, eventually caused by gcc 7.3. can you post the installation log and/or try downgrading to gcc 5.4?

**Comment by kouhonglady** [comment]
Is it solved? I encountered the same problem, gcc is 3.7.4

**Comment by rusty1s** [comment]
It was always solved and is just caused by unsupported compiler versions I have no influence about.

**Comment by qjzhzw** [comment]
> Is it solved? I encountered the same problem, gcc is 7.3.0

I solved it by installing a docker environment:
https://github.com/rusty1s/pytorch_geometric/tree/master/docker

**Comment by alvitawa** [comment]
I have this issue.

Code 
```
In [6]: t = torch.tensor([[1.,2.],[1.,3.]])

In [7]: s = torch.tensor([0,1])

In [8]: torch_scatter.scatter_max(t, s, dim=0)
Segmentation fault (core dumped)
```

System:

```
(venv) ook@archT7:~/proj/x$ pip show torch_scatter
Name: torch-scatter
Version: 2.0.9
Summary: PyTorch Extension Library of Optimized Scatter Operations
Home-page: https://github.com/rusty1s/pytorch_scatter
Author: Matthias Fey
Author-email: matthias.fey@tu-dortmund.de
License: MIT
Location: /home/ook/.local/lib/python3.10/site-packages
Requires:
Required-by:
(venv) ook@archT7:~/proj/x$ pip show torch
Name: torch
Version: 1.12.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/lib/python3.10/site-packages
Requires: typing_extensions
Required-by: clip, pytorch-lightning, timm, torchmetrics, torchvision
(venv) ook@archT7:~/proj/x$ python --version
Python 3.10.6
```

scatter_mean and scatter_std work fine

**Comment by rusty1s** [comment]
It looks like there was an issue with installing our internal `scatter` kernel. How did you install `torch-scatter` (manually/wheel)? Can you share the installation log when running `pip install --verbose ...`?

**Comment by alvitawa** [comment]
Thank you, I had installed torch-scatter previously using the instructions in torch-geometric [1]. After removing it and reinstalling through pip it works now.

[1] https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html
