### ISSUE TITLE
ImportError: /apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

### ISSUE THREAD

**Issue by anncute** [rusty1s/pytorch_scatter#66]
pytorch 1.1.0
cuda 10.1
gcc 4.9.1

I have successfully installed pytorch_scatter. However, when I import it, there comes the import error as

>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in <module>
    import torch_scatter.scatter_cpu
ImportError: /apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
>>> 

It seems to be a problem about gcc version? Which version should be used?

**Comment by rusty1s** [comment]
It is generally a problem with either gcc (try version 5.4) or with multiple PyTorch versions installed.

**Comment by jacklin18** [comment]
@anncute Hi, have you solve the previous problem? I get the same error when I run some code on Linux server.
pytorch 1.0.1
cuda 9.2
gcc 7.3.0
ImportError: /home/xzeng2/.conda/envs/xl/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

**Comment by btbbtzhang** [comment]
> pytorch 1.1.0
> cuda 10.1
> gcc 4.9.1
> 
> I have successfully installed pytorch_scatter. However, when I import it, there comes the import error as
> 
> > > > import torch_scatter
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/**init**.py", line 3, in 
> > > > from .mul import scatter_mul
> > > > File "/apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in 
> > > > from torch_scatter.utils.ext import get_func
> > > > File "/apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 2, in 
> > > > import torch_scatter.scatter_cpu
> > > > ImportError: /apps/anaconda3/envs/pytorch_1_1/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs
> 
> It seems to be a problem about gcc version? Which version should be used?

@rusty1s I have the same "undefined symbol" issue, when I was trying python version <3.7. However when I was using python version >=3.7, <3.8, this "undefined symbol" issue will be gone, but another issue came out, which is "ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found". I m pretty sure that I used the same version of gcc complied pytorch and its extensions. I feel there are some compatibility issues between the packages and python instead of dependency issue.
