### ISSUE TITLE
Repeat tensor by index in a data batch

### ISSUE THREAD

**Issue by tommycwh** [rusty1s/pytorch_scatter#67]
First of all, thank you so much for your wonderful package.    

I have been trying to construct some model that is adaptable to batch of data entries with different size, like those example models provided with PyTorch Geometric library. But for my application, I would like to repeat each data entry by different numbers of times. So, I would like to implement some "scatter_repeat" function like:
```
# I have a batch with 2 feature vectors from two data entry:
feats = torch.tensor([[1,2,3],[4,5,6]])
index = torch.tensor([[0],[1]])
# I would like to repeat the feature vector by different number of times
rep = torch.tensor([[2],[3]])
# And the expected outcome would be sth like:
#  tensor([ [1, 2.,3],
#                [1, 2.,3],
#                [4, 5, 6],
#                [4, 5, 6],
#                [4, 5, 6] ])
# and probably new index:
# torch.tensor([[0], [0], [1], [1], [1]])
```
But I only have little idea on implementing it. I tried to take reference from the implemented functions, but I only understand that the gen(...) function is mainly used for prepare a buffer for output (I hope I am making it right). May I ask for some suggestion on how to implement this idea?

Thank you in advance for any help.

**Comment by rusty1s** [comment]
You can do this via normal indexing, *e.g.*:
```python
feats = torch.tensor([[1,2,3],[4,5,6]])
index = torch.tensor([0, 0, 1, 1, 1])
out = feats[index]
```
The only problem remains how to build `index` from the tensors `[0, 1]` and `[2, 3]`.

**Comment by tommycwh** [comment]
Thank you so much for your solution. It works in my application, which is a conv, network and it has a step requiring repeating feature within data batch according to the index. Some of the codes are given here as a reference:
```
class Net(torch.nn.Module):
    def __init__(self, out_channels, k=20, aggr='max'):
        super(Net, self).__init__()
        # ...

    def forward(self, data):
        pos, batch = data.pos, data.batch
        # For example:
        #     data.batch: [0,0,1,1,1,2]

        ##### Convolutions #####
        x1 = self.conv1(pos, batch)
        x2 = self.conv2(x1, batch)
        x3 = self.conv3(x2, batch)
        # MLP
        feat = self.lin1(x3)
        # Max pooling
        feat = global_max_pool(feat, batch)
        
        # Repeat by batch
        feat_rep = feat[data.batch]
        # print("feat_rep.shape: ", feat_rep.shape)
        # e.g.: feat_rep.shape: torch.Size([6, feat_size])
        # as the example input batch has: 2 (index 0) + 3 (index 1) + 1 (index 2) = 6 entries
        
        # ......
```
Here, the data batch is generated using Data, Batch classes from torch_geometric.data.

This code is only tested the data index provided by torch_geometric.data.Batch class. I am afraid that I will not generalize this code for other situations, e.g. unordered index, more than one vector to repeat for each index, etc.

Anyway, thanks again for your solution!

**Comment by jhultman** [comment]
Hi @tommycwh, you may want  to use `torch.repeat_interleave` which is meant for this purpose. 

```
import torch

feats = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
index = torch.LongTensor([0, 1])
rep = torch.LongTensor([2, 3])

feats_repeated = torch.repeat_interleave(feats, rep, axis=0)
index_repeated = torch.repeat_interleave(index, rep, axis=0)

print(feats_repeated)
>> tensor([[1., 2., 3.],
        [1., 2., 3.],
        [4., 5., 6.],
        [4., 5., 6.],
        [4., 5., 6.]])

print(index_repeated)
>> tensor([0, 0, 1, 1, 1])
```

**Comment by tommycwh** [comment]
Thank you @jhultman! This is the function I am seeking.

I think @rusty1s and @jhultman give two nice solutions so I am closing this issue. Thank you for the help.
