### ISSUE TITLE
Scattering NxD tensors

### ISSUE THREAD

**Issue by VitorGuizilini** [rusty1s/pytorch_scatter#69]
I am having issues scattering a [NxD] source tensor (D > 1) into a [MxD] output tensor, using a [N] index tensor. I have no issue when the source tensor is [N] and the output tensor is [M], am I supposed to be able to scatter under these conditions?

**Comment by rusty1s** [comment]
Yes! Please show me an example code :)

**Comment by vguizilini** [comment]
Not fully functional, but I have these tensors:

feats = [9x1]
idx = [9]
out = [441x1]

and when I run:

out = scatter_mean(feats, idx, out=out)

I get this error: "shape '[1, 1]' is invalid for input of size 9"

Now, if I switch feats to [9] and out to [441], removing the extra dimension that will be scattered then it works fine, but now I cannot extend it to D > 1.

**Comment by rusty1s** [comment]
You need to scatter along dimension `0`: `out = scatter_mean(feats, idx, out=out, dim=0)`
