### ISSUE TITLE
Scatter_logaddexp

### ISSUE THREAD

**Issue by justinchiu** [rusty1s/pytorch_scatter#71]
Would it be possible to add support for the logaddexp binary operation?

**Comment by rusty1s** [comment]
So you mean a numerical stable version of `scatter_add(src.exp(), index).log()`? This should work just fine:
```python
max_value = scatter_max(src, index, dim, dim_size)[0][index]
out = scatter_add((out - max_value).exp(), index, dim, dim_size)
out = torch.log(out + 1e-16)
```
If you know of a better way to implement it, please let me know :)

**Comment by justinchiu** [comment]
That should do it, thanks
