### ISSUE TITLE
Mixing cuda and cpu tensor gives Segmentation Fault.

### ISSUE THREAD

**Issue by Whadup** [rusty1s/pytorch_scatter#75]
I've accidentally done the following:

	indices = torch.arange(data.batch.shape[0], dtype=torch.int64)
	_, roots = scatter_min(indices, data.batch)

where `indices` is a cpu tensor and `data` resides on the gpu.

Usually if you do this kind of thing in pytorch, you end up with a meaningful error message /Runtime Error.
I got a Segmentation fault, which is terrible to debug.

Maybe future releases could adopt similar runtime errors (if performance doesn't suffer too much)

**Comment by rusty1s** [comment]
Should be fixed in master :) Thank you!
