### ISSUE TITLE
use multi times, but in the last time , very slow

### ISSUE THREAD

**Issue by yzl96** [rusty1s/pytorch_scatter#83]
Hi, rustyls, pytorch_scatter is an excellent job, I use it in my project.
I need to do multi times pytorch_scatter,  around 5 times.
the first 4 times, scatter_max run very fast, 0.002s, but in the last time,  it need 0.13s. 
if I add time.sleep(2) before the last time scatter_max, the scatter_max can run 0.002s, the gpu memory is enough, so I don't know why.  

something very strange is that gpu sometimes out of memory:
RuntimeError: CUDA out of memory. Tried to allocate 458.75 GiB 
the memory is so big, I don't know why.

my scatter_max's input'shape is  [20000,64]

**Comment by rusty1s** [comment]
GPU calls run asynchronous in PyTorch, so you need to measure the time consumption by running `torch.cuda.synchronize()` before and after each call.

**Comment by yzl96** [comment]
> GPU calls run asynchronous in PyTorch, so you need to measure the time consumption by running `torch.cuda.synchronize()` before and after each call.

ok , I try it

**Comment by yzl96** [comment]
> GPU calls run asynchronous in PyTorch, so you need to measure the time consumption by running `torch.cuda.synchronize()` before and after each call.

voxel maxpooling time:  0.0031311511993408203
bev_fc_output: torch.float32
fv dense time:  0.0011219978332519531
bev dense time:  0.0004258155822753906
fv_resnet time:  0.0034284591674804688
bev_resnet time:  0.004384040832519531
fv maxpooling time
0.15114998817443848
, in voxel maxpooling time, I do two times maxpooling,
in fv maxpooling time, I do one time

**Comment by yzl96** [comment]
sorry, it looks like time.time() is not very accurate.
