### ISSUE TITLE
support batch scatter_max

### ISSUE THREAD

**Issue by zilongyuan** [rusty1s/pytorch_scatter#85]
Hi, rusty1s, thanks you for so excellent job, I wonder if scatter_max support batch scatter_max, for example:
input: (N1+N2, 3)
indices(N1+N2, 2)
N1 means my first tensor shape is (N1,3), N2, my second tensor is (N2,3), I cat the two tensor , get input (N1+N2, 3)
element in indice's (N1+N2,0) has two value, 0 and 1, 0 means the indice belong to first tensor, 1 means the indices belong to second tensor. for example,  k belongs to [0,N1+N2), indices[k,:] = [0,155], means input[k,:] belongs to first tensor, and input[k,:] 's index is 155.

finally I can get a list or tuple, list[0] represent first tensor scatter result, list[1] represent second tensor scatter result.

I want to do is that do scatter_max for a batch , and samples in a batch have different shape.

**Comment by rusty1s** [comment]
What prevents you from simple calling `scatter_max` on the concatenated inputs and indices? Isn't this exactly what `scatter_max` is trying to do or am I misunderstanding something?
