### ISSUE TITLE
Failed to install on Mac

### ISSUE THREAD

**Issue by Stevring** [rusty1s/pytorch_scatter#87]
Hi rusty1s! Thanks for your helpful work. I got some issue when I tried to install your package on macOS 10.14.6 with the following command `pip install torch-scatter` and got the error output:

/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py:172: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++) is not compatible with the compiler Pytorch was
built with for this platform, which is clang++ on darwin. Please
use clang++ to to compile your extension. Alternatively, you may
compile PyTorch from source using g++, and then you can also use
g++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  platform=sys.platform))
building 'torch_scatter.scatter_cpu' extension
creating build/temp.macosx-10.7-x86_64-3.7
creating build/temp.macosx-10.7-x86_64-3.7/cpu
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -I/anaconda3/lib/python3.7/site-packages/torch/include -I/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/anaconda3/lib/python3.7/site-packages/torch/include/TH -I/anaconda3/lib/python3.7/site-packages/torch/include/THC -I/anaconda3/include/python3.7m -c cpu/scatter.cpp -o build/temp.macosx-10.7-x86_64-3.7/cpu/scatter.o -Wno-unused-variable -DVERSION_GE_1_3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library
      instead [-Wstdlibcxx-not-found]
In file included from cpu/scatter.cpp:1:
In file included from /anaconda3/lib/python3.7/site-packages/torch/include/torch/extension.h:4:
In file included from /anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:3:
/anaconda3/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/cuda.h:5:10: fatal error: 'cstddef'
      file not found
#include <cstddef>
         ^~~~~~~~~
1 warning and 1 error generated.
error: command 'gcc' failed with exit status 1

I downloaded the source code and running `python setup.py install --cpu`, but got the same error. Could you please help me solve this? Thanks in advance.

**Comment by rusty1s** [comment]
This is a typical error message when installing on macOS. Following [this advice](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#c-cuda-extensions-on-macos) should fix it.

**Comment by Stevring** [comment]
It works. Thx a lot.
