### ISSUE TITLE
Recommendations for parallel MLP

### ISSUE THREAD

**Issue by jlevy44** [rusty1s/pytorch_scatter#88]
Hey, finally started implementing some scatter code, which has been a big speed-up for me over other implementations like a for loop of a module list. I managed to have a parallel single layer perceptron up and running quickly (~20k Perceptrons with trainable parameters), but am looking for a quick way to implement scattered parallel MLPs. Do you have any recommendations?

**Comment by rusty1s** [comment]
If I understand you correctly, you want to apply *different* MLPs for different indices, is this correct? The only way I can think of without writing some kernel functions is to map the respective MLP to each index, but this is far from memory-efficient. Basically what I mean:
```python
x = [num_examples, num_in_features]
index = [num_examples]
weight = [num_indices, num_in_features, num_out_features]
out = x @ weight[index]
```

**Comment by jlevy44** [comment]
Yeah another issue is that the number of input features is not fixed. Imagining if the features were broken into groups and the mlps parallel process each feature group

**Comment by knightBoy** [comment]
I also met this problem. I map the MLP to each index, but it raises OOM error on my 12GB machine because I have 5,40,000+ examples, 500+ MLPs and the `num_in_features` and `num_out_features` are 200. I have no idea how to save memory except for-loop.
