### ISSUE TITLE
Default torch arch list when there is NO docker container

### ISSUE THREAD

**Issue by mingloo** [rusty1s/pytorch_scatter#91]
I saw the below installation instructions when install `torch-scatter` when there is NO nvidia driver available in docker environment.

> When running in a docker container without nvidia driver, PyTorch needs to evaluate the compute capabilities and may fail. In this case, ensure that the compute capabilities are set via TORCH_CUDA_ARCH_LIST

> export` TORCH_CUDA_ARCH_LIST = "6.0 6.1 7.2+PTX 7.5+PTX"

But on my side, I can use `torch-scatter` in GPU mode in Titan Xp but NOT for RTX 2080Ti. Is there any default TORCH_CUDA_ARCH_LIST be set when installing in NO CUDA docker environment?

**Comment by mingloo** [comment]
@rusty1s  

Could you please help double check it?

**Comment by rusty1s** [comment]
Maybe @CeadeS can help?

**Comment by mingloo** [comment]
Is it related to `pytorch` version?
