### ISSUE TITLE
Bitwise scatter operators

### ISSUE THREAD

**Issue by rubenwiersma** [rusty1s/pytorch_scatter#92]
I'm working on an application where bitwise scatter operations (bitwise or, xor, etc.) would be very helpful. As far as I understand, there is no sensical way to compute a gradient for bitwise operations, so it makes sense that these operations are not in this package. On the other hand, as a utility/data processing tool, though, these operations might be useful. What do you think? I can spend some time on a pull request if others are interested.

**Comment by rusty1s** [comment]
I wouldn't mind integrating those into `torch-scatter`. Feel free to open a PR so we can discuss the details. Thanks in advance!

**Comment by rubenwiersma** [comment]
Unfortunately, I've not had time to work on this yet. On the plus-side: I've found a much easier solution by thinking about it just a bit more. The add operation suffices, as I only needed an OR operation :man_facepalming: Thanks for your incredible work on this package and Pytorch Geometric! I hope to open a pull request to the latter soon with what I've been working on.
