### ISSUE TITLE
Scatter matmul

### ISSUE THREAD

**Issue by ThyrixYang** [rusty1s/pytorch_scatter#95]
Hi,

I have many matrix w1, w2, w3...wn with shape (k\*n1, k\*n2, k\*n3...k\*nn) and x1, x2, x3...xn with shape (n1\*m, n2\*m, n3\*m...nn\*m), I want to get w1@x1, w2@x2, w3@x3 repectively.

The resulting matrix is multiple k\*m matrices and can be concatenated into a large matrix with shape ((k\*n)\*m).

I think it's very similar to the scatter operation where a batch index is given, however, I didn't find this here. Would you please give me some help?

**Comment by rusty1s** [comment]
Interesting application. It is indeed related but a bit out of scope for this package since it is mostly about permutation-invariant aggregations. I believe the best approach to tackle this would be the usage of torch.split.

**Comment by ThyrixYang** [comment]
Split and multiply them one by one will be batch_size times slower than a vectorized solution, however, this one seems vectorizable at first glance. 

Thanks for your kind help.
