### ISSUE TITLE
Support half precision

### ISSUE THREAD

**Issue by innerlee** [rusty1s/pytorch_scatter#97]
Which can save some gpu memory in some case.

**Comment by cswinter** [comment]
+1, now that automatic mixed precision is part of PyTorch half precision would be a nice addition to this awesome library.
Currently, using torch.cuda.amp.autocast won't work out of the box for networks using torch_scatter and results in this runtime error:

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/clemens/miniconda3/envs/dcc/lib/python3.7/site-packages/torch_scatter/scatter.py", line 72, in scatter_max
                dim_size: Optional[int] = None
                ) -> Tuple[torch.Tensor, torch.Tensor]:
    return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: "scatter" not implemented for 'Half'

```

**Comment by rusty1s** [comment]
It's on the roadmap for PyG 1.7.0, see [here](https://github.com/rusty1s/pytorch_geometric/issues/1465).

**Comment by yl-guo-working** [comment]
> It's on the roadmap for PyG 1.7.0, see [here](https://github.com/rusty1s/pytorch_geometric/issues/1465).

@rusty1s Do you have any plans for releasing?

**Comment by rusty1s** [comment]
We are still waiting for better PyTorch half-precision support: https://github.com/rusty1s/pytorch_scatter/pull/137
Nonetheless, a few GNNs should work fine with half-precision by now. It's best to just try it out if your current GNN supports it or not :)

**Comment by yl-guo-working** [comment]
@rusty1s Thanks for the swift reply. I am actually using torch-scatter and facing the same error:

**Comment by karthi0804** [comment]
> @rusty1s Thanks for the swift reply. I am actually using `scatter_max` in torch-scatter with pytorch-1.8.0 and cuda11. Facing the same error:
> `RuntimeError: "scatter" not implemented for 'Half' `

I also use the same and get same error

**Comment by rusty1s** [comment]
Installing `torch-scatter` from master now supports `torch.half` :)

**Comment by karthi0804** [comment]
> Installing `torch-scatter` from master now supports `torch.half` :)

By any chance, is it available via Pip Wheels?

**Comment by rusty1s** [comment]
@karthi0804 I will do some further testing and will release new binaries ASAP (probably next week or the week after).

**Comment by rusty1s** [comment]
pip and conda packages are now available for the new version `torch-scatter==2.0.8`.

**Comment by karthi0804** [comment]
@rusty1s Thanks. Btw, I would like to know if there is a way to profile and calculate flops of torch-geometric module?

**Comment by rusty1s** [comment]
You should be able in doing so using the [`torch.Profiler`](https://pytorch.org/docs/stable/profiler.html).

**Comment by karthi0804** [comment]
> You should be able in doing so using the [`torch.Profiler`](https://pytorch.org/docs/stable/profiler.html).

Thanks @rusty1s . Unfortunately, It did not display the values. [DeepSpeed](https://github.com/microsoft/DeepSpeed) helped to calculate FLOPs.

**Comment by tjcarroll11** [comment]
Are there plans to support `bfloat16`?

**Comment by rusty1s** [comment]
`bfloat16` support should be there for CPU kernels. If you want it for GPU as well, you might find success in using the `torch.scatter_reduce_` which is now natively supported in PyTorch.
